"""Worked, source-specific packs. Independent derivations, not NTA answer keys."""
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from core import parse_bank,export_bank
raw={q['id']:q for q in json.loads((ROOT/'data/raw_questions.json').read_text())}
packs=[]
def add(n,track,topic,difficulty,prompt,options,correct,hints,solution,theory,examples,*,pid='2020-june-26nov'):
 qid=f'{pid}-q{n:03d}';src=raw[qid]
 packs.append(dict(id=qid,source_type='official_exam',paper_id=src['paper_id'],question_number=n,
  part=src['part'],track=track,topic=topic,difficulty=difficulty,prompt=prompt,
  options=dict(zip('ABCD',options)),correct_options=list(correct),hints=hints,
  solution=solution,theory=theory,similar_questions=[dict(prompt=p,solution=s) for p,s in examples],
  review_status='reviewed',source_note='Transcribed from the attached paper; independently worked solution.',
  answer_source=f'Independent mathematical derivation in this learning pack; original question {n}, PDF page {src["page"]}. Not checked against an NTA final key.',
  page=src['page'],image=src['image'],classification_status='reviewed'))
add(3,'Shared','Aptitude','Easy',
 'Rice A and B cost ₹30 and ₹90 per kg; pulses C and D cost ₹100 and ₹120 per kg. Buy at least 1 kg each of A and B and 0.5 kg each of C and D. Find the minimum and maximum costs of 5 kg.',
 ['₹150 and ₹600','₹260 and ₹530','₹290 and ₹470','₹370 and ₹460'],'C',
 ['First purchase the compulsory quantities.','Allocate every remaining kilogram to the cheapest item for the minimum and the costliest item for the maximum.'],
 r'The compulsory 3 kg costs $30+90+0.5(100)+0.5(120)=230$. There are 2 kg left. The cheapest choice adds $2(30)=60$, giving ₹290. The costliest adds $2(120)=240$, giving ₹470. Both allocations satisfy every lower bound. Hence **C**.',
 r'For a linear cost $\sum c_i x_i$ with $x_i\ge l_i$ and $\sum x_i=W$, write $x_i=l_i+z_i$. Then $z_i\ge0$ and $\sum z_i=R=W-\sum l_i$. The variable cost is a weighted average of the coefficients times $R$, so it lies between $R\min c_i$ and $R\max c_i$. These bounds are attained by putting all excess mass in an extremal item. Check feasibility $W\ge\sum l_i$ first. Upper limits on quantities would require allocating the remainder in price order rather than all to one item.',
 [('Two items cost ₹20 and ₹50/kg. At least 1 kg of each is required; buy 4 kg. Find the cost range.','The compulsory cost is ₹70 and 2 kg remain. The range is ₹110–₹170.'),('When is the minimum unique?','If the cheapest coefficient is unique and positive remainder is available, all remainder must go to that item. Equal cheapest prices give multiple minima.')])
add(6,'Shared','Aptitude','Easy','A 7 m tube of inner diameter 2 cm is full of water. It is emptied into a bucket of inner base area 200 cm². Find the approximate water height.',
 ['22 cm','44 cm','9 cm','11 cm'],'D',['Convert the tube length to centimetres.','Use conservation of volume: tube volume = bucket base area × height.'],
 r'The tube radius is 1 cm and length is 700 cm. Its volume is $\pi(1)^2(700)=700\pi\ \mathrm{cm}^3$. Thus $h=700\pi/200=3.5\pi\approx11.0$ cm. **D**.',
 r'The volume of a cylinder is $\pi r^2L$. After pouring without losses, volume is conserved. A vessel with constant cross-section $A$ has water height $V/A$. Use inner dimensions, divide diameter by two, and convert every length to the same unit before multiplying. If a receiving vessel has varying cross-section, $V=\int_0^h A(z)\,dz$ instead.',
 [('A tube of radius 2 cm and length 100 cm drains into a bucket with base area 100 cm². Find the height.',r'$V=400\pi$ cm³, so $h=4\pi$ cm.'),('What happens if the tube diameter doubles?',r'At fixed length and bucket area, volume and water height multiply by $2^2=4$.')])
add(8,'Shared','Aptitude','Moderate','A square board is divided into 9 equal squares. Three independent uniformly random shots hit the board. What is the probability that at least two hit the same small square?',
 ['$1/3$','$56/81$','$25/81$','$2/3$'],'C',['Use the complementary event: all three shots hit different squares.','The second shot must avoid one square; the third must avoid two.'],
 r'All distinct has probability $1\cdot(8/9)\cdot(7/9)=56/81$. The requested event is its complement: $1-56/81=25/81$. **C**. The assumptions are independent shots and equal hit probabilities for all nine squares.',
 r'The occupancy or birthday calculation for $k$ independent choices among $m$ equally likely cells is $P(\text{all distinct})=(m)_k/m^k$ for $k\le m$, where $(m)_k=m(m-1)\cdots(m-k+1)$. At least one collision is its complement. For $k>m$, collision is certain by the pigeonhole principle. Exactly one pair and at least one pair are different events when $k\ge4$. With unequal cell probabilities, the simple product formula no longer applies.',
 [('Three shots hit four equal cells. Find the collision probability.',r'$1-(4\cdot3\cdot2)/4^3=5/8$.'),('For the original board, find the probability all three hit the same square.',r'There are 9 choices for the shared square, each with probability $(1/9)^3$, so the result is $1/81$.')])
add(12,'Shared','Aptitude','Moderate','Clock A loses 4 minutes per real hour; C gains 3 minutes per real hour. Both agree with the correct clock at Monday 8 pm. When C reads Wednesday 2 pm, what does A read?',
 ['7:20 am','8:40 am','9:20 am','10:40 am'],'C',['C has advanced 42 displayed hours since synchronisation.','Convert C time to real elapsed time, then apply A’s rate.'],
 r'Clock C runs at $63/60$ of real speed. Its displayed elapsed time is 42 h, so real elapsed time is $42(60/63)=40$ h. A advances $40(56/60)=37\frac13$ h. Adding 37 h 20 min to Monday 8 pm gives Wednesday **9:20 am**, option C.',
 r'A clock gaining $g$ minutes per hour has rate $(60+g)/60$; a clock losing $l$ has rate $(60-l)/60$. Displayed elapsed time equals rate times real elapsed time. Compare elapsed times from the synchronisation point rather than subtracting clock errors from a displayed calendar time. Between clocks, the ratio of elapsed readings is $(60-l)/(60+g)$. Keep day changes and fractional hours explicit.',
 [('C gains 6 min/hour and shows 11 elapsed hours. A loses 3 min/hour. How far has A advanced?',r'Real elapsed time is $11/1.1=10$ h, so A advances $10(57/60)=9.5$ h.'),('Two clocks run at 59 and 61 minutes per real hour. How far apart are they after 12 real hours?','The gap grows at 2 minutes per hour, hence 24 minutes.')])
add(13,'Shared','Aptitude','Easy','A class needs one pencil per two students, one eraser per three, and one ruler per four. The total number of these items is 65. Find the class size.',
 ['55','60','65','70'],'B',['If there are N students, write the three item counts.','Add the fractions using denominator 12.'],
 r'For the stated exact ratios, $N/2+N/3+N/4=65$, so $13N/12=65$ and $N=60$. This gives 30 pencils, 20 erasers, and 15 rulers, totalling 65. **B**.',
 r'For exact resource ratios, item counts add: $N\sum_i(1/d_i)=T$. Solve for $N$ and verify it is an integer compatible with each denominator. If the wording requires whole items rounded up instead, use ceilings $\sum_i\lceil N/d_i\rceil=T$, which can have several solutions; exact ratios and rounding are different models.',
 [('One item is needed per 2 students and another per 5. There are 42 items. Find N.',r'$N(1/2+1/5)=42$, so $N=60$.'),('Verify the original class size by counting items.','For 60 students, 30+20+15=65 items, and all sharing ratios are integral.')])
add(15,'Shared','Aptitude','Easy','Active cases are 990, 1000, 1030, 1060, 1090 on days 0, 1, 4, 7, 10; recovered cases are 760, 800, 920, 1040, 1160. If both linear trends continue, on which day are recoveries twice active cases?',
 ['61','62','63','64'],'A',['Find each daily rate from the table.','Set recovered count equal to twice the active count.'],
 r'The trends are $A(d)=990+10d$ and $R(d)=760+40d$. Solve $760+40d=2(990+10d)$: $20d=1220$, giving $d=61$. At that time, $A=1600$ and $R=3200$. **A**.',
 r'A linear trend is $y(d)=y(0)+md$ with constant slope $m=\Delta y/\Delta d$. Unequally spaced table days require dividing by the actual day interval. For $R(d)=kA(d)$, solve $(m_R-km_A)d=kA(0)-R(0)$. If the coefficient is zero, either the equality holds always or never. A negative crossing time lies before day zero. Here extrapolation is an explicit assumption in the problem.',
 [('Active cases are 100+2d and recoveries 20+6d. When are recoveries twice active cases?',r'$20+6d=200+4d$, so $d=90$.'),('When are the two original counts equal?',r'$760+40d=990+10d$ gives $d=23/3$ days.')])
add(22,'Mathematics','Real Analysis','Easy',r'A bounded function $f:\mathbb N\to\mathbb N$ is given. Which statement is NOT true?',
 [r'$\limsup f(n)\in\mathbb N$',r'$\liminf f(n)\in\mathbb N$',r'$\liminf(f(n)+n)\in\mathbb N$',r'$\limsup(f(n)+n)\notin\mathbb N$'],'C',
 ['A bounded integer sequence takes values in a finite set.','What happens to f(n)+n as n grows?'],
 r'Because $f$ is bounded and integer-valued, its tail extrema stabilise at integers: the largest and smallest values occurring infinitely often. Thus A and B hold. Since $f(n)+n\to+\infty$, its liminf and limsup are both $+\infty$ in the extended real line. Infinity is not a natural number, so C is false and D is true. **C**.',
 r'For a real sequence, $\limsup a_n=\lim_{N\to\infty}\sup_{n\ge N}a_n$ and similarly for infimum. These limits can be infinite. A bounded sequence need not converge, but its liminf and limsup are finite and equal exactly when it converges. For a finite-valued sequence, they are the smallest and largest values appearing infinitely often. Adding a sequence tending to positive infinity to a uniformly bounded sequence forces divergence to positive infinity; this follows from two-sided bounds.',
 [('Let f(n)=1 for even n and 3 for odd n. Find its liminf and limsup.','They are 1 and 3, respectively.'),('If |a_n|≤5, what is the limit of n+a_n?',r'$n-5\le n+a_n\le n+5$, hence the limit is $+\infty$.')])
add(23,'Mathematics','Topology','Hard',r'Which statement about continuous maps $\mathbb R^2\to\mathbb R$ is true?',
 ['At most countably many continuous maps','At most finitely many continuous surjections','Infinitely many continuous injections','No continuous bijections'],'D',
 ['Constant maps disprove the first claim; shifted coordinate projections disprove the second.','Restrict a proposed injection to a circle and use compactness and connectedness.'],
 r'Every real constant gives a different continuous map, so A is false. The maps $(x,y)\mapsto x+c$ are distinct continuous surjections, so B is false. Suppose an injection existed. Its restriction to $S^1$ is a continuous injection from a compact space into a Hausdorff space, hence a homeomorphism onto its image. The image is a nondegenerate compact interval in $\mathbb R$. Removing an interior point disconnects that interval, while removing one point from $S^1$ leaves a connected space. Contradiction. No continuous injection exists, so C is false and **D** holds.',
 r'A continuous bijection is not automatically a homeomorphism. It is one if its domain is compact and target Hausdorff, because compact sets have closed images. Connected subsets of the real line are intervals. Removing a point can distinguish topological spaces: a circle minus one point is homeomorphic to a line, while an interval minus an interior point has two components. Restricting a proposed map to a convenient compact subset often turns a difficult global problem into a topological invariant argument. Set-theoretic bijections between R and R² do exist; continuity is the obstruction here.',
 [('Can there be a continuous injection from a circle into the line?','No. Its compact connected image would be an interval homeomorphic to the circle, contradicted by puncturing at an interior image point.'),('Give a continuous surjection from R² to R.',r'The projection $(x,y)\mapsto x$ is continuous and surjective.')])
add(24,'Mathematics','Real Analysis','Moderate',r'For which domain does $\sum_{n=1}^{\infty}(-1)^n\sin(nx)/n^{\log_e n}$ converge uniformly?',
 ['Only x=0',r'Only $[-\pi,\pi]$',r'Only $\mathbb R\setminus\{n\pi:n\in\mathbb Z\}$',r'All $\mathbb R$'],'D',
 [r'Bound $|\sin(nx)|$ independently of x.',r'For sufficiently large n, $\log n\ge2$.'],
 r'For all real x, $|(-1)^n\sin(nx)/n^{\log n}|\le n^{-\log n}$. For $n\ge\lceil e^2\rceil$, $n^{-\log n}\le n^{-2}$. The majorant series converges, and finitely many initial terms do not affect convergence. The Weierstrass M-test gives absolute and uniform convergence on the entire real line. **D**.',
 r'The M-test: if $|f_n(x)|\le M_n$ for every x in a domain and $\sum M_n<\infty$, then $\sum f_n$ converges uniformly and absolutely there. Uniform convergence controls tails simultaneously for every x; pointwise convergence alone does not. Here $n^{-\log n}=\exp[-(\log n)^2]$ eventually decays faster than any fixed power $n^{-p}$. The alternating sign is unnecessary because an absolute majorant already works. A uniformly convergent sum of continuous functions is continuous; termwise differentiation requires additional conditions on derivatives.',
 [(r'Does $\sum \cos(nx)/n^2$ converge uniformly on R?',r'Yes: $|\cos(nx)/n^2|\le1/n^2$ and the M-test applies.'),(r'For which p does the M-test apply to $\sum \sin(nx)/n^p$?',r'The bound $1/n^p$ is summable for $p>1$. Failure for p≤1 does not by itself prove absence of uniform convergence.')])
add(25,'Mathematics','Real Analysis','Hard',r'For an arbitrary real sequence $(a_n)$, which assertion always holds?',
 [r'$\sum(-1)^n a_n/(1+|a_n|)$ converges',r'Some subsequence makes $\sum a_{n_k}/(1+|a_{n_k}|)$ converge',r'Some b makes $\sum|b-a_n/(1+|a_n|)|(-1)^n$ converge',r'Some b and subsequence make $\sum|b-a_{n_k}/(1+|a_{n_k}|)|$ converge'],'D',
 [r'The transformed sequence $b_n=a_n/(1+|a_n|)$ is bounded.','After finding a convergent subsequence, select an even faster one with error at most 2⁻ᵏ.'],
 r'Put $b_n=a_n/(1+|a_n|)$, so $|b_n|<1$. By Bolzano–Weierstrass, some subsequence converges to a real b. Thin it further to ensure $|b-b_{n_k}|<2^{-k}$. Therefore the nonnegative series in D is bounded by a convergent geometric series. A fails for $a_n=(-1)^n$, giving constant terms 1/2. B fails for $a_n=1$. For C, again take $a_n=(-1)^n$: the term magnitudes alternate between $|b-1/2|$ and $|b+1/2|$ and cannot both tend to zero. **D**.',
 r'Every bounded real sequence has a convergent subsequence. Given convergence to b and any positive summable error sequence ε_k, choose increasing indices n_k with distance below ε_k. This strengthens subsequential convergence to summability along a further subsequence. It does not force convergence of a series of the values themselves: those may approach a nonzero limit. For every convergent series, its individual terms must tend to zero. Alternating signs alone never guarantee convergence; the standard alternating-series test also needs magnitudes decreasing to zero.',
 [('Show every bounded real sequence has a subsequence whose successive differences are absolutely summable.',r'Choose a subsequence with $|b_{n_k}-b|<2^{-k}$. Then $|b_{n_{k+1}}-b_{n_k}|\le2^{-(k+1)}+2^{-k}$, a summable bound.'),('Must every convergent sequence have summable errors from its limit?',r'No: $1/n\to0$, but $\sum1/n$ diverges. A thinner subsequence $n_k=2^k$ has summable errors.')])
add(26,'Mathematics','Real Analysis','Easy',r'Continuous f,g on [0,1] satisfy f(0)=f(1)=0, g(0)=g(1)=1, and f(1/2)>g(1/2). What must hold?',
 ['No point has f(t)=g(t)','Exactly one point has f(t)=g(t)','At least two points have f(t)=g(t)','Always infinitely many points have f(t)=g(t)'],'C',
 ['Apply the intermediate value theorem to h=f−g.','Use [0,1/2] and [1/2,1] separately.'],
 r'The continuous function h=f−g has h(0)=h(1)=−1 and h(1/2)>0. IVT gives a zero in (0,1/2) and another in (1/2,1), so they are distinct. **C**. To rule out D, take g=1 and f=8t(1−t); the equality is a quadratic with exactly two roots.',
 r'IVT states that a continuous real function on an interval takes every value between its endpoint values. Opposite endpoint signs guarantee an interior zero. Applying IVT on disjoint open subintervals guarantees distinct roots. It gives a lower bound on root count, not uniqueness. Strict monotonicity can establish uniqueness on each interval. Continuity is essential: a jump can cross from negative to positive without attaining zero.',
 [('A continuous h has signs +,−,+ at x=0,1,2. How many zeros are guaranteed?','At least two, one in (0,1) and one in (1,2).'),('Give a discontinuous sign-changing function without zeros.',r'$h(x)=-1$ for x<0 and $h(x)=1$ for x≥0 changes sign but never equals zero.')])
add(27,'Mathematics','Linear Algebra','Moderate',r'An n×n matrix A has exactly r distinct nonzero eigenvalues. Which assertion is always true?',
 [r'$\operatorname{rank}A\le r$',r'If r=0, then $\operatorname{rank}A<n-1$',r'$\operatorname{rank}A\ge r$',r'$A^2$ has r distinct nonzero eigenvalues'],'C',
 ['Eigenvectors for distinct eigenvalues are linearly independent.','For nonzero λ, an eigenvector v lies in the image of A because v=A(v/λ).'],
 r'Choose one eigenvector for each distinct nonzero eigenvalue. They are independent and all lie in im A, so its dimension, rank A, is at least r. **C**. A fails for A=I₂ (rank 2, r=1). B fails for a nilpotent Jordan block of rank n−1. D fails for diag(1,−1), whose square is I₂ and merges the two eigenvalues.',
 r'The rank is the dimension of the image, while nullity is the dimension of the kernel; their sum is n. Distinct eigenvalues give independent eigenvectors, but eigenvalue multiplicities and Jordan blocks mean that the number of distinct eigenvalues does not determine rank. All eigenvalues zero implies nilpotence over a field in which the characteristic polynomial splits, not the zero matrix. Polynomial functions of a matrix map eigenvalues through the polynomial; distinct values may collide, as λ and −λ do under squaring.',
 [('What is the rank of a single nilpotent Jordan block J₄?',r'It has ones on the superdiagonal, rank 3, nullity 1, and only eigenvalue 0.'),('For a diagonal matrix, how do you find its rank?','Count its nonzero diagonal entries, including repetitions, rather than distinct nonzero values.')])
add(28,'Mathematics','Linear Algebra','Easy','For arbitrary 2×2 matrices A and B, which determinant identity holds?',
 [r'$\det(A+B)+\det(A-B)=\det A+\det B$',r'$\det(A+B)+\det(A-B)=2\det A-2\det B$',r'$\det(A+B)+\det(A-B)=2\det A+2\det B$',r'$\det(A+B)-\det(A-B)=2\det A-2\det B$'],'C',
 ['The determinant of a 2×2 matrix is quadratic in its entries.','Expand both determinants; mixed A–B terms cancel in the sum.'],
 r'Write $A=(a_{ij})$, $B=(b_{ij})$. Expanding gives $\det(A+B)=\det A+\det B+M$, where $M=a_{11}b_{22}+b_{11}a_{22}-a_{12}b_{21}-b_{12}a_{21}$. Replacing B by −B changes M to −M and leaves det B unchanged. Adding gives $2\det A+2\det B$. **C**.',
 r'The determinant is multilinear in columns, but is not linear as a function of the whole matrix. In dimension two it is a homogeneous quadratic form and satisfies the parallelogram identity Q(u+v)+Q(u−v)=2Q(u)+2Q(v). The degree matters: in general det(cA)=cⁿdet(A), and this particular identity need not hold in other dimensions. Expanding a polynomial and cancelling odd mixed terms is a useful method for matrix identities.',
 [('Check the identity for A=I₂, B=2I₂.','The left side is det(3I₂)+det(−I₂)=9+1=10; the right side is 2(1)+2(4)=10.'),('Does det(A+B)=det A+det B generally hold?','No: for A=B=I₂, the two sides are 4 and 2.')])
add(29,'Mathematics','Linear Algebra','Moderate',r'Find $A^{20}$ for $A=\begin{pmatrix}3&-2\\2&-1\end{pmatrix}$.',
 [r'$\begin{pmatrix}41&40\\-40&-39\end{pmatrix}$',r'$\begin{pmatrix}41&-40\\40&-39\end{pmatrix}$',r'$\begin{pmatrix}41&-40\\-40&-39\end{pmatrix}$',r'$\begin{pmatrix}41&40\\40&-39\end{pmatrix}$'],'B',
 ['Compute N=A−I.','Check N², then apply the binomial formula to (I+N)²⁰.'],
 r'$N=\begin{pmatrix}2&-2\\2&-2\end{pmatrix}$ satisfies N²=0. Since I commutes with N, $(I+N)^{20}=I+20N$; every higher-power term vanishes. This equals $\begin{pmatrix}41&-40\\40&-39\end{pmatrix}$. **B**.',
 r'For A=λI+N with Nᵏ=0, powers truncate: $A^m=\sum_{j=0}^{k-1}\binom mj\lambda^{m-j}N^j$ for nonnegative integer m, interpreting the original binomial expression when λ=0. A repeated eigenvalue does not imply diagonalizability; a nonzero nilpotent part produces a Jordan block. Here the characteristic polynomial is (t−1)² and Cayley–Hamilton gives (A−I)²=0. This avoids twenty repeated matrix multiplications.',
 [('If N²=0, find (2I+N)⁵.',r'$32I+5\cdot16N=32I+80N$.'),('Find the inverse of I+N when N²=0.',r'$(I+N)(I-N)=I-N^2=I$, so the inverse is I−N.')])
add(30,'Mathematics','Linear Algebra','Easy','A real 2×2 matrix A has determinant 1 and trace 3. Find trace(A²).',
 ['2','10','9','7'],'D',['Use the characteristic polynomial for a 2×2 matrix.','Take the trace of A²−3A+I=0, remembering trace(I₂)=2.'],
 r'Cayley–Hamilton gives A²−3A+I₂=0. Taking traces yields tr(A²)−3·3+2=0, hence tr(A²)=7. **D**. Equivalently, if eigenvalues are λ₁,λ₂, then λ₁²+λ₂²=(λ₁+λ₂)²−2λ₁λ₂=9−2.',
 r'For every 2×2 matrix, $\chi_A(t)=t^2-(\operatorname{tr}A)t+\det A$. Cayley–Hamilton substitutes A into this polynomial. Thus $\operatorname{tr}(A^2)=(\operatorname{tr}A)^2-2\det A$. It holds without diagonalizability. Traces of powers satisfy a recurrence: s_m=T s_{m−1}−D s_{m−2}, with s₀=2 and s₁=T. Distinguish trace(A²) from (trace A)².',
 [('If a 2×2 matrix has trace 4 and determinant 3, find trace(A²).','It is 16−6=10.'),('For the original matrix, find trace(A³).','Use s₃=3s₂−s₁=3·7−3=18.')])
add(52,'Statistics','Probability Distributions','Easy','X is uniform on [0,100] and Y=⌊X⌋. Which statement is true?',
 [r'$P(Y\le25)=1/4$',r'$P(Y\le25)=26/100$',r'$E(Y)=50$',r'$E(Y)=101/2$'],'B',
 ['Y≤25 is the event X<26.','The point X=100 has probability zero.'],
 r'For k=0,…,99, $P(Y=k)=P(k\le X<k+1)=1/100$. Therefore $P(Y\le25)=26/100$, so **B**. Also $E(Y)=(0+99)/2=49.5$, ruling out C and D.',
 r'A continuous random variable can become discrete under a floor transformation. Derive masses by preimages: P(⌊X⌋=k)=P(k≤X<k+1). For X uniform on [0,m], integer m, the floor is discrete uniform on 0,…,m−1; the endpoint m has zero mass. Its mean is (m−1)/2 and variance (m²−1)/12. Endpoints of continuous intervals have probability zero, but inclusive thresholds for the resulting integer variable change how many cells are counted.',
 [('X is uniform on [0,10]. Find P(⌊X⌋≤3).','Four unit cells contribute, giving 4/10.'),('For the original Y, find Var(Y).',r'For uniform integers 0,…,99, the variance is $(100^2-1)/12=9999/12$.')])
add(53,'Statistics','Statistical Inference','Moderate',r'An iid sample has pdf $f(x\mid\theta)=(\log\theta)\theta^x/(\theta-1)$ for 0<x<1, θ>1. Classify $T=\sum X_i$.',
 ['Sufficient but not complete','Sufficient but not minimal sufficient','Complete sufficient','Neither complete nor sufficient'],'C',
 ['Write the joint density using η=log θ.','The natural parameter η ranges over the open interval (0,∞).'],
 r'Let η=log θ>0. The joint density is $[\eta/(e^\eta-1)]^n\exp(\eta T)\mathbf1_{(0,1)^n}$. Factorization makes T sufficient. This is a full one-parameter exponential family with fixed support and natural parameter space containing an open interval, so its natural statistic T is complete. Hence **C**. The likelihood ratio for two sample points is parameter-independent exactly when their sums agree, also showing minimal sufficiency.',
 r'A statistic is sufficient when the likelihood factors into a data-only part and a part depending on the data through that statistic. It is complete if Eθ[g(T)]=0 for every θ implies g(T)=0 almost surely for every θ, whenever those expectations exist. Full exponential families with parameter-independent support and a natural parameter space containing a nonempty open set have complete natural statistics. Completeness is not automatic for curved families or arbitrary sufficient statistics. Combined with sufficiency, it supports unique unbiased estimators via the Lehmann–Scheffé theorem.',
 [('For iid Poisson(λ), is the sample sum complete sufficient?','Yes. The joint density is a full exponential family with natural parameter log λ ranging over R. The sum is complete sufficient.'),('Why does the product indicator not break sufficiency here?','The support (0,1)ⁿ does not depend on θ and belongs to the data-only factor.')])
add(54,'Statistics','Statistical Inference','Hard',r'One observation has logistic location pdf $f(x\mid\theta)=e^{x-\theta}/(1+e^{x-\theta})^2$. Find a UMP size-α test of H₀:θ≤θ₀ versus H₁:θ>θ₀.',
 [r'Reject X>k with $\alpha=P_{\theta_0}(X>k)$',r'Reject X<k with $\alpha=P_{\theta_0}(X>k)$',r'Reject X>k with $\alpha=P_{\theta_0}(X<k)$',r'Reject X<k with $\alpha=P_{\theta_0}(X<k)$'],'A',
 ['Larger θ shifts the distribution to the right.','Show the likelihood ratio for θ₁>θ₀ is increasing in x, then calibrate the upper tail.'],
 r'For θ₁>θ₀, the derivative of the log likelihood ratio with respect to x is $2[s(x-\theta_0)-s(x-\theta_1)]>0$, where $s(u)=e^u/(1+e^u)$. Thus the family has monotone likelihood ratio in X. The upper-tail test is most powerful for every θ₁>θ₀ and the same threshold works for all alternatives. Choose $P_{\theta_0}(X>k)=\alpha$, giving $k=\theta_0+\log((1-\alpha)/\alpha)$ for 0<α<1. For θ≤θ₀ its rejection probability is at most α. **A**.',
 r'Neyman–Pearson compares likelihood ratios for simple hypotheses. A monotone likelihood ratio family yields a common one-sided rejection region for every alternative, giving a uniformly most powerful test by the Karlin–Rubin argument. Size for a composite null is the supremum rejection probability over the null, here attained at θ₀. The logistic CDF is Fθ(x)=s(x−θ). Reversing the alternative reverses the tail. UMP tests for two-sided alternatives generally do not follow from this one-sided argument.',
 [('For θ₀=0 and α=0.05, find the critical value.',r'$k=\log19\approx2.944$; reject above k.'),('What is the rejection probability at θ₁>θ₀?',r'$P_{\theta_1}(X>k)=1/[1+e^{k-\theta_1}]$, which exceeds α and increases with θ₁.')])
add(55,'Statistics','Statistical Inference','Easy','For 35 iid observations split into 15 X observations and 20 Y observations, let R be the sum of ranks of the X observations in the pooled sample. Find E(R).',
 ['270','300','360.5','330.5'],'A',['Each pooled rank has mean (35+1)/2 under the iid assumption.','Use linearity of expectation; the ranks are not independent.'],
 r'Each X observation is exchangeable with every pooled observation. With the usual no-tie ranking (or midranks for ties), its expected rank is $(35+1)/2=18$. Summing 15 expectations gives E(R)=15·18=270. **A**. Independence between the ranks is unnecessary.',
 r'For two iid groups of sizes m and n with N=m+n, the null expected Wilcoxon rank sum is m(N+1)/2. The pooled ranks sum to N(N+1)/2 and exchangeability allocates the same expected rank to every observation. With a continuous distribution, ties have probability zero and Var(R)=mn(N+1)/12. Ties require a variance correction, though midrank assignment preserves the mean. The Mann–Whitney statistic U=R−m(m+1)/2 has mean mn/2. Different sampling distributions invalidate the iid null expectation.',
 [('For group sizes 10 and 12, find the expected first-group rank sum.',r'$10(23)/2=115$.'),('Find E(U) for the original groups.',r'$E(U)=15\cdot20/2=150$; equivalently 270−15·16/2=150.')])
add(57,'Statistics','Regression and Multivariate Analysis','Moderate',r'Independent $X_1,X_2\sim N_p(\mu,\Sigma)$ have positive-definite Σ. Which expression always has a central chi-square distribution?',
 [r'$\frac12(X_1-X_2)^T(X_1-X_2)$',r'$2(X_1-X_2)^T(X_1-X_2)$',r'$2(X_1-X_2)^T\Sigma^{-1}(X_1-X_2)$',r'$\frac12(X_1-X_2)^T\Sigma^{-1}(X_1-X_2)$'],'D',
 ['The difference has mean zero and covariance 2Σ.','Whiten the difference to obtain independent standard normal coordinates.'],
 r'$D=X_1-X_2\sim N_p(0,2\Sigma)$. Hence $Z=(2\Sigma)^{-1/2}D\sim N_p(0,I_p)$ and $Z^TZ\sim\chi_p^2$. This quadratic form is $D^T(2\Sigma)^{-1}D=\frac12D^T\Sigma^{-1}D$. **D**. C is four times this chi-square variable; A and B fail to account for arbitrary Σ.',
 r'For a multivariate normal vector W with mean m and invertible covariance V, the squared Mahalanobis distance (W−m)ᵀV⁻¹(W−m) has a central chi-square distribution with p degrees of freedom. Whitening is a linear transform to unit covariance, after which normal components are independent. For an uncentered form with a nonzero mean, the distribution is noncentral chi-square. Covariances add for independent differences; for correlated vectors, cross-covariance terms must be included. Ordinary Euclidean squared length works only for a matching scalar identity covariance.',
 [('W∼N₃(0,4I). What is ||W||²/4 distributed as?',r'$\chi_3^2$.'),('What is the expected value of the correct form in this question?',r'A $\chi_p^2$ variable has mean p and variance 2p.')])
add(59,'Statistics','Sampling and Design of Experiments','Hard','In a complete randomized block design with b blocks and k treatments under the usual independent equal-variance additive error model, which claim holds?',
 ['Any two estimated treatment contrasts are uncorrelated','Error sum of squares has bk−1 degrees of freedom','Every estimated treatment contrast is uncorrelated with every estimated block contrast','Two estimated treatment contrasts always have negative correlation'],'C',
 ['A contrast has coefficients summing to zero.','Compute the covariance between a treatment row-mean contrast and a block column-mean contrast.'],
 r'Write treatment contrast $T=\sum_i c_i\bar y_{i\cdot}$ and block contrast $B=\sum_j d_j\bar y_{\cdot j}$, with Σcᵢ=Σdⱼ=0. Since $\operatorname{Cov}(\bar y_{i\cdot},\bar y_{\cdot j})=\sigma^2/(bk)$, $\operatorname{Cov}(T,B)=\sigma^2(\sum c_i)(\sum d_j)/(bk)=0$. **C**. Two treatment contrasts instead have covariance $(\sigma^2/b)\sum c_i a_i$, not necessarily zero or negative. Error degrees of freedom are (b−1)(k−1), so B is false.',
 r'A contrast is a linear combination of factor effects whose coefficients sum to zero, eliminating the overall mean. Balanced complete block designs make treatment and block contrast subspaces orthogonal. Orthogonality under spherical independent errors gives zero covariance; normal errors further give independence. Treatment contrasts are mutually orthogonal only when their coefficient vectors have zero dot product. Total degrees of freedom bk−1 decompose into treatment k−1, block b−1, and residual (b−1)(k−1). Missing cells and unequal variances can destroy these simple properties.',
 [('With b=4 and k=3, find residual degrees of freedom.','(4−1)(3−1)=6.'),('Are contrasts with coefficients (1,−1,0) and (1,1,−2) uncorrelated?',r'Yes: their dot product is 1−1+0=0 under the balanced equal-variance model.')])
add(60,'Mathematics','Operations Research','Easy',r'Find the maximum and minimum of 5x+7y subject to |x|+|y|≤1.',
 ['5 and −5','5 and −7','7 and −5','7 and −7'],'D',
 ['Bound the absolute value by 5|x|+7|y|.','Try the vertices (0,1) and (0,−1).'],
 r'$|5x+7y|\le5|x|+7|y|\le7(|x|+|y|)\le7$. The upper bound is attained at (0,1), the lower at (0,−1). The extrema are 7 and −7, so **D**.',
 r'The constraint is the unit ℓ₁ ball, a diamond with vertices (±1,0),(0,±1). A linear objective reaches extrema at vertices of a compact polytope. More generally, max over Σ|xᵢ|≤R of a·x equals R max|aᵢ|, the duality between ℓ₁ and ℓ∞ norms. The minimum is its negative because the feasible set is symmetric. With a Euclidean ball instead, the maximum is R||a||₂, so the shape of the constraint matters.',
 [('Find max(3x−4y) for |x|+|y|≤2.','The maximum is 2·4=8, attained at (0,−2).'),('Find max(5x+7y) for x²+y²≤1.',r'By Cauchy–Schwarz the maximum is $\sqrt{74}$, attained at $(5,7)/\sqrt{74}$.')])
add(61,'Mathematics','Discrete Mathematics','Moderate',r'Which sets are in bijection with $\mathbb R$?',
 [r'All maps {0,1}→N',r'All maps N→{0,1}',r'All subsets of N',r'All subsets of R'],'BC',
 ['A binary sequence corresponds uniquely to a subset of N.','Cantor’s theorem makes the power set of R strictly larger than R.'],
 r'A map {0,1}→N is determined by an ordered pair of natural numbers, so A is countable. A map N→{0,1} is a binary sequence, and its positions with value 1 give a bijection with P(N). Both B and C have cardinality $2^{\aleph_0}$, the continuum, and hence match R. Cantor’s theorem gives $|P(R)|>|R|$, so D does not. The complete correct set is **B,C**.',
 r'Finite products of countable sets remain countable, but the set of all infinite binary sequences is uncountable. Characteristic functions give a bijection P(S)↔{0,1}ˢ. To identify continuum cardinality rigorously, map binary sequences into the Cantor set using ternary digits 0 and 2, giving an injection into R, and encode real numbers via rational lower cuts for an injection into P(N); Cantor–Schröder–Bernstein gives equality. Direct binary expansions require care with nonunique dyadic representations. Cantor’s diagonal argument proves no set surjects onto its own power set.',
 [('Is N×N countable?','Yes. Enumerate pairs by increasing sum, then within each finite diagonal.'),('Which is larger: P(N) or P(P(N))?','The second is strictly larger by Cantor’s theorem applied to P(N).')])
add(62,'Mathematics','Real Analysis','Moderate','Which of the following series converge?',
 [r'$\sum_{n\ge1}(-1)^n/\sqrt n$',r'$\sum_{n\ge1}(-1)^n/(\sqrt n+n)$ is absolutely convergent',r'$\sum_{n\ge1}\{[1+(-1)^n]\sqrt n+\log n\}/n^{3/2}$',r'$\sum_{n\ge1}\{(-1)^n\sqrt n+1\}/n^{3/2}$'],'AD',
 ['Use the alternating-series test for A, and examine absolute values for B.','Split C and D into simpler series. In C the even-indexed harmonic part remains positive.'],
 r'A converges by the alternating-series test since 1/√n decreases to zero. B is not absolutely convergent: for n≥1, n≤n+√n≤2n, so its absolute terms are at least 1/(2n). In C, the summand is $(1+(-1)^n)/n+(\log n)/n^{3/2}$; its even-indexed first part is 1/k at n=2k and diverges, while all terms are nonnegative. D is $\sum(-1)^n/n+\sum1/n^{3/2}$, the sum of two convergent series. Thus **A,D**.',
 r'The alternating-series test needs nonincreasing nonnegative magnitudes tending to zero. Absolute convergence implies convergence, while conditional convergence means the original series converges but its absolute-value series diverges. Positive series admit comparison and limit comparison tests; p-series converge exactly when p>1. Splitting into a sum of series is justified when the component series converge, or when divergent behavior can be established from nonnegative components. The term (log n)/nᵖ is summable for p>1 because log n grows slower than any positive power. Adding a summable positive perturbation to an alternating harmonic series preserves convergence but may not give absolute convergence.',
 [(r'Classify $\sum(-1)^n/n^{3/4}$.','It converges conditionally: alternating test applies, while the absolute p-series has p=3/4≤1.'),(r'Does $\sum[(-1)^n/n+1/n^2]$ converge?',r'Yes, by summing a convergent alternating harmonic series and a convergent p-series. It remains conditionally convergent.')])
if __name__=='__main__':
 from additional_packs import extend
 extend(add)
 ids={p['id'] for p in json.loads((ROOT/'data/papers.json').read_text())}
 parsed=parse_bank({'schema_version':1,'questions':packs},ids)
 (ROOT/'data/exam_questions.json').write_text(export_bank(parsed))
 (ROOT/'data/import_example.json').write_text(export_bank(parsed[:1]))
 print('Curated packs:',len(parsed))
