from pack_writer import Writer, ROOT, RAW
import json,sys
sys.path.insert(0,str(ROOT))
from core import load_project_bank
W=Writer('2022-june','-q091-120')
pending={q.question_number for q in load_project_bank(ROOT,False) if q.paper_id=='2022-june' and q.review_status=='pending'}
def add(n,topic,prompt,opts,ans,hints,sol,theory,ex,status='reviewed',note=''):
 if n not in pending and not any(q['question_number']==n for q in W.packs): return
 W.add(n,'Statistics' if topic in ['Probability','Probability Distributions','Statistical Inference','Stochastic Processes','Regression and Multivariate Analysis','Sampling and Design of Experiments'] else 'Mathematics',topic,'Moderate',prompt,opts,ans,hints,sol,theory,ex,status,note)
add(91,'Ordinary Differential Equations',r'Let $A\in M_3(\mathbb R)$ be skew-symmetric and let $x:[0,\infty)\to\mathbb R^3$ solve $x\prime(t)=Ax(t)$. Which statements are true?',
 [r'$\|x(t)\|=\|x(0)\|$ for every $t>0$.',r'For some nonzero $a\in\mathbb R^3$, $\|x(t)-a\|=\|x(0)-a\|$ for every $t>0$.',r'$x(t)-x(0)\in\operatorname{im}A$ for every $t>0$.',r'$\lim_{t\to\infty}x(t)$ exists.'],'ABC',
 [r'Differentiate the squared norm and use $v^TAv=0$.',r'An odd-dimensional skew-symmetric matrix has a nonzero kernel vector; integrate $x\prime=Ax$.'],
 r'Skew symmetry gives $d\|x\|^2/dt=2x^TAx=0$, proving A. Since $\det A=\det(-A^T)=(-1)^3\det A$, the determinant is zero and a nonzero $a\in\ker A$ exists. Then $(x-a)\prime=A(x-a)$, and the same norm argument proves B. Also $x(t)-x(0)=\int_0^tAx(s)ds=A\int_0^tx(s)ds\in\operatorname{im}A$, proving C. D is false: for $A=\begin{pmatrix}0&-1&0\\1&0&0\\0&0&0\end{pmatrix}$ and $x(0)=(1,0,0)$, the solution is $(\cos t,\sin t,0)$, with no limit as $t\to\infty$. Thus A,B,C are correct. Constant norm guarantees boundedness but does not guarantee convergence.',
 r'A real skew-symmetric matrix generates an orthogonal flow $e^{tA}$, since the derivative of $(e^{tA})^Te^{tA}$ is zero and its initial value is the identity. This conserves Euclidean norms for the linear differential system. Odd-dimensional skew-symmetric matrices are singular, providing fixed directions around which the remaining coordinates may rotate. Translating a solution by a kernel vector leaves the same homogeneous equation, so distances to that fixed vector are conserved as well. Integrating the differential equation locates increments in the range of the matrix, a linear subspace closed under such integrals in finite dimension. Purely imaginary eigenvalues can produce periodic motion, and a zero eigenvalue produces constant components. Conservation and boundedness should not be mistaken for asymptotic stability or convergence.',
 [(r'Solve $x\prime=\begin{pmatrix}0&-2\\2&0\end{pmatrix}x$ with $x(0)=(1,0)$.',r'The solution is $(\cos2t,\sin2t)$, with constant norm one. It is periodic and has no limit.'),(r'For the three-dimensional rotation matrix above, choose a nonzero fixed center $a$.',r'The kernel is the $z$-axis, so take $a=(0,0,1)$. Since $Aa=0$, the translated vector solves the same equation and its Euclidean norm, the distance to $a$, is constant.')])
add(92,'Ordinary Differential Equations',r'Let $y\prime=Ay+h(t)$ with $A=\begin{pmatrix}1&1\\4&-2\end{pmatrix}$ and $h(t)=(3t+1,2t+5)^T$. If a solution satisfies $y(t)/t\to d\in\mathbb R^2$, find $d$.',
 [r'$(-4/3,-5/3)^T$.',r'$(4/3,-5/3)^T$.',r'$(2/3,-5/3)^T$.',r'$(-2/3,-5/3)^T$.'],'A',
 [r'Construct a particular solution $y_p=pt+q$ by matching polynomial coefficients.',r'Its slope is $p=-A^{-1}(3,2)^T$; eliminate any exponentially growing homogeneous component using the given limit.'],
 r'Write $b=(3,2)^T,c=(1,5)^T$ and seek $y_p=pt+q$. Comparing $p=Apt+Aq+bt+c$ gives $Ap+b=0$ and $Aq+c=p$. Since $\det A=-6$, $p=-A^{-1}b=(-4/3,-5/3)^T$. The eigenvalues of $A$ solve $\lambda^2+\lambda-6=0$, so they are 2 and -3. Every solution has the form $y_p+C_+e^{2t}v_++C_-e^{-3t}v_-$. A finite limit of $y(t)/t$ forces $C_+=0$. The constant particular term divided by $t$ and the decaying term divided by $t$ both vanish, so $d=p$, option A. This proof avoids incorrectly assuming $y\prime(t)\to d$ merely from $y(t)/t\to d$.',
 r'A linear constant-coefficient system with polynomial forcing admits a polynomial particular solution when the system matrix is invertible, found by matching coefficients. The general solution adds homogeneous modes determined by eigenvalues and generalized eigenvectors. Positive real eigenvalues create exponentially growing modes, negative ones create decaying modes, and their compatibility with a specified asymptotic limit determines allowable constants. When considering a ratio $y(t)/t$, its finite limit does not by itself justify differentiating the limit or applying l’Hôpital in reverse. An explicit solution decomposition gives a rigorous alternative. Invertibility is needed here to solve the slope and constant equations; a zero eigenvalue can raise the degree of the particular solution. Signs in $Ap+b=0$ matter because forcing is canceled at the leading polynomial order, not simply copied into the slope.',
 [(r'Solve the asymptotic slope for $y\prime=-2y+3t$ if $y(t)/t$ has a limit.',r'A particular solution is $y_p=(3/2)t-3/4$. The homogeneous term $Ce^{-2t}$ decays, so every solution has slope limit $3/2$.'),(r'For $y\prime=2y+t$, which initial value gives a finite slope limit?',r'A particular solution is $y_p=-t/2-1/4$, and the full solution is $y_p+Ce^{2t}$. Finite slope requires $C=0$, hence $y(0)=-1/4$, with slope limit $-1/2$.')])
add(93,'Ordinary Differential Equations',r'Consider (I) $y\prime(x)=y(x)^{1/3}$, $y(0)=0$, and (II) $y\prime(x)=-y(x)^{1/3}$, $y(0)=0$, using real cube roots. Which statements are true?',
 [r'I is uniquely solvable.',r'II is uniquely solvable.',r'I has multiple solutions.',r'II has multiple solutions.'],'CD',
 [r'Both admit the zero solution, and separation gives nonzero branches of magnitude $(2|x-a|/3)^{3/2}$.',r'Check whether solutions are required only for $x\ge0$ or on a two-sided neighborhood of zero.'],
 r'For I, a nonzero forward branch is $y(x)=(2x/3)^{3/2}$ for $x\ge0$, joined to zero for $x\le0$. It is $C^1$ at zero and satisfies the equation, so I is not unique and C is true. For II, the backward branch $y(x)=(-2x/3)^{3/2}$ for $x\le0$, joined to zero for $x\ge0$, is likewise $C^1$ and satisfies $y\prime=-y^{1/3}$. Hence on a two-sided neighborhood II also has multiple solutions, so D is true and B false. If the intended meaning is forward solutions on $[0,\varepsilon)$ only, II is unique: $(y^2)\prime=-2|y|^{4/3}\le0$ and $y(0)=0$ force zero. Under that extra convention the intended labels become B,C. The printed source does not restrict the independent variable to nonnegative values, so the ordinary two-sided local truth set C,D is retained with this conditional diagnosis.',
 r'Continuity of the right-hand side ensures local existence but not uniqueness when local Lipschitz continuity fails. The cube-root function is continuous but has an unbounded slope near zero, enabling solutions that remain zero for a waiting period and then depart. Separation away from zero finds power-law branches, and their first derivatives tend to zero at the joining point, permitting classical $C^1$ gluing. A vector field directed toward zero gives forward uniqueness at zero via a nonnegative Lyapunov function, but backward time reverses the direction and may permit departure. Consequently forward uniqueness and uniqueness on a two-sided interval are different assertions. Local initial-value problems are usually considered on an interval containing the initial point, unless a time half-line is stated. The solution domain must be included when resolving this apparent contradiction.',
 [(r'Give a waiting-time solution of $y\prime=y^{1/3}$ for $x\ge0$.',r'For any $a\ge0$, set $y=0$ on $[0,a]$ and $y=[2(x-a)/3]^{3/2}$ for $x\ge a$. Its derivative joins continuously at zero, and direct differentiation verifies the equation.'),(r'Prove forward uniqueness for $y\prime=-y^{1/3}$, $y(0)=0$.',r'The square $v=y^2$ satisfies $v\prime=-2|y|^{4/3}\le0$. Starting at $v(0)=0$, nonnegativity implies $v=0$ at every later time, hence $y=0$. Backward branches do not violate this forward argument.')],status='source_issue',note='Source does not state a forward-time domain. Literal two-sided local IVPs both have multiple C1 solutions, labels C,D. If restricted to x>=0, intended answer is B,C. Explicit branches and the forward uniqueness proof are provided; official comparison is recorded separately after derivation.')
add(94,'Partial Differential Equations',r'Let $u$ solve $u_x+xu_y=0$ with $u(x,0)=e^x$. Which statements are true?',
 [r'$u(2,1)=e^2$.',r'$u(1,1/2)=1$.',r'$u(-2,1)=e^{-\sqrt2}$.',r'$u(-2,1)=e^{\sqrt2}$.'],'BC',
 [r'Characteristics satisfy $dy/dx=x$, so $y-x^2/2$ is constant.',r'Check the boundary data at the characteristic tangency $(0,0)$ before assuming a global classical solution.'],
 r'Characteristics have $y-x^2/2=c$. In the region $x>0$, $x^2>2y$, the characteristic meets $y=0$ at $s=\sqrt{x^2-2y}$, giving $u=e^{\sqrt{x^2-2y}}$. On the negative side it meets at $s=-\sqrt{x^2-2y}$ and gives $u=e^{-\sqrt{x^2-2y}}$. Thus the intended characteristic values are $u(2,1)=e^{\sqrt2}$ and $u(-2,1)=e^{-\sqrt2}$; A and D are false, C true. At $(1,1/2)$ the positive branch has continuous limiting value $e^0=1$, giving intended B. However no classical solution exists in a neighborhood of $(0,0)$ satisfying all printed data: the boundary trace gives $u_x(0,0)=1$, while the PDE there gives $u_x(0,0)=0$. Moreover the branch derivatives blow up as $x^2-2y\downarrow0$, so B is a continuous trace at the characteristic boundary, not a classical interior evaluation. Labels B,C are conditional intended answers; the source omits domain and regularity qualifications needed to make them literal.',
 r'The method of characteristics reduces a first-order transport PDE to ordinary differential equations along curves on which the solution is constant. For $u_x+a(x,y)u_y=0$, characteristic curves satisfy $dy/dx=a(x,y)$. Initial data determine a local classical solution near a noncharacteristic curve, where the transport direction is transverse to the data curve. If tangency occurs, compatibility conditions may fail or uniqueness may break down. For data on $y=0$ and transport vector $(1,x)$, tangency occurs at the origin. A characteristic invariant can distinguish branches, and one must select the boundary intersection lying on the same connected branch of the chosen solution domain. Continuous extension to a characteristic boundary is weaker than differentiability there. Singular derivatives and contradictory tangential data should be identified explicitly rather than hidden by a formal square-root expression.',
 [(r'Solve $u_x+u_y=0$ with $u(x,0)=e^x$.',r'The invariant is $x-y$. Every characteristic intersects the data line transversely, so $u(x,y)=e^{x-y}$ is a global smooth solution and direct differentiation gives $u_x+u_y=0$.'),(r'For $u_x+xu_y=0$ with data $u(x,0)=x^2$, find a smooth solution.',r'The invariant is $x^2-2y$, so take $u=x^2-2y$. It has the required trace and satisfies $u_x+xu_y=2x+x(-2)=0$. Unlike $e^x$, the data derivative at the origin is zero and satisfies compatibility.')],status='source_issue',note='Printed PDE/data admit no classical solution near (0,0): data require u_x=1 there but PDE requires u_x=0. Intended B,C follow characteristic branch formulas and a continuous boundary trace; missing domain/regularity assumptions are diagnosed.')
add(95,'Partial Differential Equations',r'Let $u:\mathbb R^3\to\mathbb R$ satisfy $\Delta u=0$ and define $v(x)=u(Mx)$, where $M=\begin{pmatrix}0&-1&0\\1&0&0\\0&0&1\end{pmatrix}$. Which statements are necessarily true?',
 [r'$\Delta v=0$.',r'$\Delta v=v$.',r'$\operatorname{div}(M^TM\nabla v)=0$.',r'$\operatorname{div}(M^TM\nabla v)=v$.'],'AC',
 [r'The matrix is orthogonal, so $M^TM=I$.',r'The Hessian transforms as $H_v=M^TH_u(Mx)M$; take its trace.'],
 r'The matrix rotates the first two coordinates by $\pi/2$ and fixes the third; $M^TM=MM^T=I$. By the chain rule, $H_v=M^TH_u(Mx)M$, so $\Delta v=\operatorname{tr}(H_v)=\operatorname{tr}(H_uMM^T)=\Delta u(Mx)=0$, proving A. Since $M^TM=I$, $\operatorname{div}(M^TM\nabla v)=\operatorname{div}\nabla v=\Delta v=0$, proving C. B and D fail for the harmonic constant $u=1$, for which $v=1$ but both differential expressions are zero. Thus A,C are correct. This invariance relies on orthogonality; an arbitrary invertible matrix would generally transform the Laplacian into an anisotropic operator.',
 r'The Laplacian is the trace of the Hessian and is invariant under orthogonal coordinate transformations. For a constant linear substitution $y=Mx$, gradients transform by $M^T$ and Hessians by congruence, $H_v=M^TH_uM$. Cyclicity of trace and $MM^T=I$ then preserve the Laplacian. A harmonic function is one with zero Laplacian; it need not itself vanish, as constants show. Divergence of a constant matrix times a gradient represents a second-order operator, and when that matrix is the identity it is exactly the Laplacian. Orthogonal transformations include rotations and reflections and preserve lengths and angles. General linear transformations need a corresponding coefficient matrix to preserve the transformed PDE. Testing constant harmonic functions is an efficient way to disprove claims that incorrectly equate the Laplacian to the original function.',
 [(r'If $u(x,y)=x^2-y^2$ and $v(x,y)=u(-y,x)$, is $v$ harmonic?',r'$v=y^2-x^2$, so $v_{xx}+v_{yy}=-2+2=0$. The rotation preserves harmonicity.'),(r'Does $v(x,y)=u(2x,y)$ preserve harmonicity for the same $u$?',r'Here $v=4x^2-y^2$, whose Laplacian is $8-2=6$. Unequal coordinate scaling is not orthogonal and does not generally preserve the ordinary Laplacian.')])
add(96,'Numerical Analysis',r'Let $\alpha=(1+\sqrt5)/2$, $\beta=(1-\sqrt5)/2$, and $F_n=(\alpha^n-\beta^n)/(\alpha-\beta)$. Let $p$ have degree at most 2 and satisfy $p(1)=F_1,p(3)=F_3,p(5)=F_5$. Which statements are true?',
 [r'$F_n=F_{n-1}+F_{n-2}$ for $n\ge3$.',r'$p(7)=13$.',r'$F_n=F_{n-1}+2F_{n-2}$ for $n\ge5$.',r'$p(7)=10$.'],'AD',
 [r'Both $\alpha$ and $\beta$ satisfy $r^2=r+1$.',r'The interpolation data are $1,2,5$ at equally spaced arguments; use their second differences.'],
 r'The roots satisfy $r^2=r+1$, so multiplying by $r^{n-2}$ and subtracting the equations for the two roots proves the Fibonacci recurrence in A. Initial values are $F_1=F_2=1$, so $F_3=2,F_5=5$. For interpolation at arguments 1,3,5, the values are 1,2,5, with successive differences 1 and 3 and second difference 2. A quadratic has constant second differences, so the next difference at argument 7 is 5 and $p(7)=5+5=10$, proving D and disproving B. Explicitly $p(x)=x^2/4-x/2+5/4$. C already fails at $n=5$: $F_5=5$ but $F_4+2F_3=3+4=7$. Correct labels A,D. Interpolating three Fibonacci values does not make the quadratic reproduce all later Fibonacci terms.',
 r'Closed-form sequences built from powers of roots of a polynomial satisfy the linear recurrence associated with that polynomial. If $r^2=r+1$, each geometric sequence $r^n$ satisfies the Fibonacci recurrence, and any linear combination does as well. Polynomial interpolation at distinct nodes has a unique solution of degree below the number of nodes. For equally spaced nodes, a quadratic is characterized by constant second finite differences, allowing extrapolation without explicitly solving coefficients. The interpolation polynomial is a different object from the original sequence and need not match additional sequence values. Uniqueness follows because the difference of two degree-two polynomials with three distinct roots must vanish. Care is needed to use the spacing of the interpolation arguments rather than assuming consecutive integer inputs. Evaluating both an explicit polynomial and its difference table provides a useful consistency check.',
 [(r'Interpolate values 2,5,10 at arguments 0,1,2 and find the value at 3.',r'First differences are 3 and 5, so the constant second difference is 2. The next first difference is 7, giving value 17. The polynomial is $x^2+2x+2$.'),(r'If $r$ is a root of $r^2=3r+2$, what recurrence does $a_n=r^n$ satisfy?',r'Multiplying by $r^{n-2}$ gives $r^n=3r^{n-1}+2r^{n-2}$. Thus $a_n=3a_{n-1}+2a_{n-2}$, and linear combinations of the two root-power sequences satisfy it too.')])
add(97,'Numerical Analysis',r'For the smooth ODE $\dot x=f(t,x)$, a second-order Runge–Kutta formula is $x(t+h)=x(t)+w_1hf(t,x)+w_2hf(t+\alpha h,x+\beta hf(t,x))+O(h^3)$. Which tuples $(w_1,w_2,\alpha,\beta)$ are correct?',
 [r'$(1/2,1/2,1,1)$.',r'$(1/2,1,1/2,1)$.',r'$(1/4,3/4,2/3,2/3)$.',r'$(0,1,1,1)$.'],'AC',
 [r'Expand the second stage through its terms of order $h$.',r'Match the exact expansion $x+hf+(h^2/2)(f_t+f_xf)$.'],
 r'The second stage expands as $f(t+\alpha h,x+\beta hf)=f+h(\alpha f_t+\beta f_xf)+O(h^2)$. The numerical step is therefore $x+h(w_1+w_2)f+h^2w_2(\alpha f_t+\beta f_xf)+O(h^3)$. The exact Taylor expansion requires $w_1+w_2=1$, $w_2\alpha=1/2$, and $w_2\beta=1/2$. A satisfies all three. C satisfies $1/4+3/4=1$ and $(3/4)(2/3)=1/2$ for both derivative terms. B has weight sum $3/2$ and $w_2\beta=1$; D has the second-order coefficients 1 instead of $1/2$. Hence A,C are correct. Smoothness ensures the Taylor remainders used here are legitimate.',
 r'Runge–Kutta methods approximate an ODE solution through weighted evaluations of its vector field at intermediate stages. Order conditions follow by expanding the stages and matching the exact solution Taylor series for a general sufficiently smooth vector field. For a nonautonomous scalar equation, the second derivative is $x\prime\prime=f_t+f_xf$, so both time displacement and state displacement must be matched independently. First-order consistency requires that the weights sum to one. A two-stage explicit second-order scheme requires the second-stage weight times each stage displacement to equal one half. These conditions produce a family of methods, including explicit trapezoidal and midpoint forms. Testing only autonomous equations can miss an incorrect time coefficient. Local error of order $h^3$ corresponds to global order two under standard stability and regularity assumptions.',
 [(r'Verify the explicit midpoint tuple $(0,1,1/2,1/2)$.',r'The weights sum to one, and the second weight times either stage displacement is $1/2$. It satisfies all second-order conditions and uses the slope at an approximate midpoint.'),(r'Apply Heun’s tuple to $x\prime=x$ for one step from $x_0$.',r'First slope is $x_0$ and the endpoint predictor is $x_0+hx_0$. The averaged-slope step is $x_0+h[x_0+(1+h)x_0]/2=x_0(1+h+h^2/2)$, matching $e^hx_0$ through order two.')])
add(98,'Calculus of Variations',r'Let $X=\{u\in C^1[0,1]:u(0)=u(1)=0\}$ and $I(u)=\int_0^1e^{-(u\prime(t))^2}dt$. Put $M=\sup_XI$ and $m=\inf_XI$. Which statements are true?',
 [r'$M=1,m=0$.',r'$1=M>m>0$.',r'$M$ is attained.',r'$m$ is attained.'],'AC',
 [r'The integrand is positive and at most one; the zero function attains the upper bound.',r'Scale $u(t)=t(1-t)$ by a parameter tending to infinity and use dominated convergence.'],
 r'For every admissible $u$, $0<e^{-(u\prime)^2}\le1$, so $0<I(u)\le1$. The zero function gives $I(0)=1$, hence $M=1$ and it is attained. Take $u_n(t)=nt(1-t)$, whose derivative is $n(1-2t)$. The integrand tends to zero for every $t\ne1/2$, is bounded by one, and the exceptional singleton has measure zero. Dominated convergence gives $I(u_n)\to0$, so $m=0$. No fixed $C^1$ function attains this infimum: its derivative is bounded by some $K$, making $I(u)\ge e^{-K^2}>0$. Therefore A and C are true and B,D false. The noncompact admissible set permits an unattained infimum even though each individual functional value is positive.',
 r'A variational functional may have a supremum or infimum without possessing an extremizing admissible function. Pointwise bounds on its integrand provide initial bounds on its values, but sharpness requires an admissible function or a sequence approaching the bound. Dominated convergence applies when the integrands converge almost everywhere and are bounded by one common integrable function. Scaling a fixed zero-endpoint function can drive derivative-dependent integrands to zero except at finitely many stationary points. An individual $C^1$ function on a compact interval has bounded derivative, providing a positive lower bound for its own exponential integrand, yet that bound need not be uniform over all admissible functions. Existence theorems require compactness or coercivity conditions that are absent here. The terms maximum and minimum imply attainment, while supremum and infimum do not.',
 [(r'For $J(u)=\int_0^1e^{-2(u\prime)^2}dt$ on the same space, find supremum and infimum.',r'The zero function attains the supremum 1. Scaling $nt(1-t)$ and applying dominated convergence gives infimum 0, unattained because each fixed derivative is bounded.'),(r'If additionally $|u\prime|\le1$, can the same infimum be zero?',r'No. Pointwise $e^{-(u\prime)^2}\ge e^{-1}$, so every functional value is at least $e^{-1}>0$. The earlier scaling sequence violates this derivative constraint.')])
add(99,'Calculus of Variations',r'If $y$ is stationary for $J[y]=\int_{-1}^1(1-x^2)(y\prime)^2dx$, with $y(-1)=y(1)=1$, subject to $\int_{-1}^1y^2dx=1$, which statements are true?',
 [r'$y$ is unique.',r'$y$ is always a polynomial of even degree.',r'$y$ is always a polynomial of odd degree.',r'No such $y$ exists.'],'D',
 [r'The isoperimetric multiplier gives the Legendre differential equation.',r'Regularity at both endpoints forces a Legendre polynomial; compare its boundary values and squared norm with the constraint.'],
 r'For a classical stationary curve the nontrivial constraint derivative permits a Lagrange multiplier. The Euler–Lagrange equation is $[(1-x^2)y\prime]\prime+\lambda y=0$. A solution regular at both endpoints must be $cP_n(x)$ with $\lambda=n(n+1)$, where $P_n$ is a Legendre polynomial. To justify this, multiply the equation by each $P_k$ and integrate twice by parts; the weighted endpoint terms vanish, giving $(\lambda-k(k+1))\int yP_k=0$. Completeness of polynomials in $L^2[-1,1]$ forces one matching eigenvalue and $y=cP_n$. Since $P_n(1)=1$ and $P_n(-1)=(-1)^n$, the endpoint data force $c=1$ and even $n$. But $\int_{-1}^1P_n^2dx=2/(2n+1)$, which never equals 1 for any integer $n$. Hence no stationary curve satisfies all the data, D. A–C presume the existence of such a curve; the explicit nonexistence alternative is the intended meaningful answer.',
 r'An isoperimetric variational problem adds an integral constraint to fixed endpoint conditions. Under a nonvanishing constraint derivative, a stationary curve satisfies the Euler–Lagrange equation for the original integrand minus a constant multiplier times the constraint integrand. Here this produces a Sturm–Liouville equation with weight coefficient $1-x^2$, the Legendre operator. Regular eigenfunctions on the closed interval are the Legendre polynomials, with eigenvalues $n(n+1)$ and norm squared $2/(2n+1)$. Their endpoint values determine parity and scale. The coefficient vanishes at the endpoints, so regularity must be included when excluding singular second solutions. A boundary-compatible eigenfunction can still fail the prescribed integral normalization. Existence of admissible curves is not the same as existence of stationary curves, and a variational problem with degeneracy need not attain an extremum.',
 [(r'With endpoint data $y(\pm1)=1$ and normalization $\int y^2=2/5$, exhibit a stationary curve.',r'Take $y=P_2=(3x^2-1)/2$. Its endpoints are one, its norm squared is $2/(2\cdot2+1)=2/5$, and it satisfies the multiplier equation with $\lambda=6$.'),(r'Can $P_1(x)=x$ satisfy the original endpoint data?',r'No. It has values -1 and 1 at the two endpoints. Multiplying by a scalar cannot make both values equal to 1. Its squared norm $2/3$ also differs from the prescribed one.')])
add(100,'Integral Equations',r'Consider $\varphi_1(x)=\sin x+\int_0^x\varphi_2(t)dt$ and $\varphi_2(x)=1-\cos x-\int_0^x\varphi_1(t)dt$. Which statements are true?',
 [r'$\varphi_1$ vanishes at at most countably many points.',r'$\varphi_1$ vanishes at uncountably many points.',r'$\varphi_2$ vanishes at at most countably many points.',r'$\varphi_2$ vanishes at uncountably many points.'],'AD',
 [r'Differentiate and record both initial values at zero.',r'Check the candidate pair $(\sin x,0)$ and use uniqueness of the resulting linear ODE system.'],
 r'At zero both functions equal zero. Differentiation gives $\varphi_1\prime=\cos x+\varphi_2$ and $\varphi_2\prime=\sin x-\varphi_1$. The pair $\varphi_1=\sin x,\varphi_2=0$ solves this system with those initial values. Linear ODE uniqueness makes it the unique solution, and direct substitution into the original equations confirms it: the integral of sine is $1-\cos x$, canceling the second forcing term. Thus the zeros of $\varphi_1$ are $k\pi$, $k\in\mathbb Z$, a countable set, while $\varphi_2$ is zero at every real point, an uncountable set. A,D are true and B,C false. A function identically zero must be distinguished from a nonzero analytic function with isolated zeros.',
 r'Volterra integral equations with variable upper limits can often be differentiated to ordinary differential equations using the fundamental theorem of calculus. The integral equations also encode initial values at the lower endpoint, which must be carried into the differential system. Conversely, a differential solution with the correct initial values reproduces the integral equations by integration. Linear systems with continuous coefficients have unique solutions for specified initial values, permitting a simple candidate to establish the exact pair. Analytic functions that are not identically zero have isolated zeros, and their real zero sets are at most countable; an identically zero function has the entire domain as its zero set. Countability is a property of the number of zero points, not of how often a graph crosses an axis visually. Omitting the initial conditions can introduce extraneous solutions after differentiation.',
 [(r'Solve $f(x)=x+\int_0^xg(t)dt$, $g(x)=-\int_0^xf(t)dt$.',r'Differentiate to $f\prime=1+g$, $g\prime=-f$, with $f(0)=g(0)=0$. Then $f\prime\prime=-f$ and $f\prime(0)=1$, so $f=\sin x$, and $g=\cos x-1$.'),(r'How many real zeros does $1-\cos x$ have?',r'It vanishes exactly when $\cos x=1$, i.e. $x=2k\pi$ for integers $k$. This is countably infinite, unlike the zero function, whose zeros are all real numbers.')])
add(101,'Integral Equations',r'Let $g$ solve $g(s)=1+\int_0^s(s-t)g(t)dt$ for all $s\ge0$. What are the possible values of $g(1)$?',
 [r'$2e$.',r'$e-1/e$.',r'$e+1/e$.',r'$2/e$.'],[],
 [r'Differentiate twice and extract the initial values from the integral equation.',r'The resulting equation is $g\prime\prime=g$, with $g(0)=1$ and $g\prime(0)=0$.'],
 r'The equation gives $g(0)=1$. Leibniz differentiation yields $g\prime(s)=\int_0^sg(t)dt$, so $g\prime(0)=0$ and $g\prime\prime(s)=g(s)$. The unique solution is $g(s)=\cosh s=(e^s+e^{-s})/2$, and direct integration verifies the original equation. Thus $g(1)=(e+1/e)/2$, absent from the four printed options. C is twice the correct value; A, B, and D are also unequal. No literal option is correct. The exact official final key drops question422, agreeing that no listed answer can be selected. If the forcing constant were 2 rather than the printed 1, then $g=2\cosh s$ and C would be correct; alternatively inserting a missing factor $1/2$ into C repairs that option, but neither change is silently made.',
 r'A Volterra equation with kernel $s-t$ integrates its unknown twice. Differentiation converts it into a second-order ODE, while the forcing and first derivative at the lower endpoint supply the two initial conditions. The factor in the forcing controls the normalization of the solution and cannot be discarded when identifying hyperbolic functions. The ODE $g\prime\prime=g$ has general solution $ae^s+be^{-s}$; equal initial derivative zero forces $a=b$, and the initial value then fixes their common magnitude. Reconstructing the integral equation from the ODE requires both initial conditions. Such a kernel also admits a power-series solution $1+s^2/2!+s^4/4!+\cdots$, another route to $\cosh s$. Checking the value at zero is a quick way to catch the common missing factor of two.',
 [(r'Solve $g(s)=2+\int_0^s(s-t)g(t)dt$.',r'The ODE is $g\prime\prime=g$ with $g(0)=2,g\prime(0)=0$. Hence $g=2\cosh s$, and $g(1)=e+e^{-1}$.'),(r'Solve $g(s)=s+\int_0^s(s-t)g(t)dt$.',r'Differentiating gives $g\prime\prime=g$, $g(0)=0,g\prime(0)=1$. Thus $g=\sinh s=(e^s-e^{-s})/2$, with $g(1)=(e-e^{-1})/2$.')],status='source_issue',note='Exact source has forcing1 and no factor1/2 in optionC. Unique derivation gives cosh(1), absent from all options. Official exact-ID final key drops question422. Conditional repairs are explained without altering transcription.')
add(102,'Classical Mechanics',r'Let $P_1=(x_1,y_1)$, $P_2=(x_2,y_2)$ with $x_1\ne x_2$ and $y_1>y_2$. A curve is written $C=\{z:z(x_1)=P_1,z(x_2)=P_2\}$. A particle slides under gravity from $P_1$ to $P_2$, taking time $T$. Which statements are true?',
 [r'$T=\int_{x_1}^{x_2}\sqrt{[1+(z\prime(x))^2]/[2gz(x)]}\,dx$.',r'$T=\int_{x_1}^{x_2}\sqrt{1+(z\prime(x))^2}/[2gz(x)]\,dx$.',r'$T$ is minimized by a straight line.',r'The minimizing curve cannot be a straight line.'],'AD',
 [r'For release from rest without friction, energy gives speed $\sqrt{2g\times\text{vertical drop}}$.',r'The brachistochrone is a cycloid; verify whether the source defines $z$ as drop and specifies orientation.'],
 r'Under the usual brachistochrone assumptions of frictionless release from rest, if $z(x)=y_1-y(x)$ denotes downward displacement and $x_2>x_1$, then $v=\sqrt{2gz}$ and $ds=\sqrt{1+(z\prime)^2}dx$, giving A. B has speed squared instead of speed in the denominator. The Beltrami identity for $F=\sqrt{1+z\prime{}^2}/\sqrt{2gz}$ is $F-z\prime F_{z\prime}=1/\sqrt{2gz(1+z\prime{}^2)}=\text{constant}$, so $z(1+z\prime{}^2)$ is constant. A nonvertical straight line has constant finite slope but changing $z$, so cannot satisfy this condition; the minimizer is a cycloidal arc and D is true, C false. However the printed source defines $z$ as a curve taking vector values $P_1,P_2$, not as scalar drop, omits release from rest and friction assumptions, and permits $x_2<x_1$, making A negative if read literally. For an upward height graph $y(x)$ and initial speed $v_0$, the correct time is $\int\sqrt{1+y\prime{}^2}\,|dx|/\sqrt{v_0^2+2g(y_1-y)}$. A,D are conditional intended labels, with these source limitations explicitly retained.',
 r'The brachistochrone problem minimizes travel time under gravity rather than arc length. With a point particle released from rest on a frictionless fixed track, conservation of mechanical energy relates speed to vertical drop. Dividing the arc-length element by this speed gives a variational functional. The downward displacement must be distinguished from absolute upward height, and a positive path measure handles either horizontal orientation. Because the integrand has no explicit horizontal-coordinate dependence, the Beltrami first integral reduces the Euler–Lagrange equation and identifies cycloidal extremals. A straight line minimizes geometric distance but generally not travel time, since a steeper initial descent builds speed sooner. Initial velocity and dissipation alter the functional. Vector curve notation cannot be substituted into a scalar denominator without defining a component or displacement, so coordinate and physical conventions are material hypotheses.',
 [(r'Find descent time down a straight track of horizontal span $L>0$ and drop $H>0$, released from rest.',r'Use $z=Hx/L$, $0\le x\le L$. Then $T=\sqrt{1+(H/L)^2}\int_0^L[2gHx/L]^{-1/2}dx=\sqrt{2(L^2+H^2)/(gH)}$.'),(r'Parametrize a cycloid and show its brachistochrone first integral is constant.',r'Let $x=a(\theta-\sin\theta)$ and $z=a(1-\cos\theta)$. Then $dz/dx=\sin\theta/(1-\cos\theta)=\cot(\theta/2)$. Therefore $z(1+z\prime{}^2)=2a\sin^2(\theta/2)\csc^2(\theta/2)=2a$, constant.')],status='source_issue',note='Intended A,D require scalar z=downward displacement, frictionless release from rest, and x2>x1. Exact source defines vector-valued curve z and permits reverse horizontal orientation without absolute path measure, and omits initial-speed convention. Correct general formula and conditional intended derivation are provided.')
add(103,'Stochastic Processes',r'Let the one-step transition matrix be $P=\begin{pmatrix}1/2&1/2&0&0&0\\1/2&1/2&0&0&0\\1/5&1/5&1/5&1/5&1/5\\1/4&1/4&1/4&1/4&0\\0&0&0&0&1\end{pmatrix}$. Which statements are true?',
 [r'All states have the same period.',r'All states are transient.',r'Some states are transient.',r'All states are recurrent.'],'AC',
 [r'Every diagonal entry is positive, so every state can return in one step.',r'Identify closed communicating classes and the class that can leave for them.'],
 r'Every $p_{ii}>0$, so each state has return time one with positive probability and hence period one. Thus A holds. The class $\{1,2\}$ is closed and finite, so its states are recurrent; state 5 is absorbing and recurrent. States 3 and 4 communicate, but this class is not closed: each can reach 1 or 2, and once there can never return. They are transient. More explicitly, from either 3 or 4 the one-step chance to enter $\{1,2,5\}$ is at least $1/2$, so probability of remaining in the class for $n$ steps is at most $2^{-n}$ and eventual exit has probability one. Thus C is true, B,D false. Correct labels A,C. Here the source’s use of stationary is interpreted as time-homogeneous transition probabilities, not an initial distribution eliminating transient states.',
 r'A communicating class of a Markov chain consists of states mutually reachable by paths with positive probability. A class is closed if no transition can leave it. In a finite-state chain, closed irreducible classes are recurrent, whereas states outside all closed classes are transient. An absorbing state is a closed one-state class. The period of a state is the greatest common divisor of its possible positive return times; a positive self-transition immediately makes its period one, whether the state is recurrent or transient. Thus aperiodicity does not imply recurrence. A direct geometric bound on remaining inside a nonclosed class can also establish transience when each step has a uniformly positive chance of permanent exit. The transition graph and diagonal entries answer different parts of the classification and should both be inspected.',
 [(r'Classify $P=\begin{pmatrix}1&0\\1/2&1/2\end{pmatrix}$.',r'State1 is absorbing and recurrent. State2 eventually moves to1, with probability of remaining for $n$ steps $(1/2)^n$, and cannot return afterward, so it is transient. Both periods are one due to self-loops.'),(r'Can a transient state have period one?',r'Yes, state2 in that matrix has $p_{22}=1/2>0$, so return time1 is possible and its period is1, but eventual absorption elsewhere makes it transient.')])
add(104,'Stochastic Processes',r'Let $P=\begin{pmatrix}0&1&0&0\\1&0&0&0\\0&0&0&1\\0&0&1&0\end{pmatrix}$ be a homogeneous Markov chain transition matrix. Which statements are true?',
 [r'The chain is irreducible.',r'All states are recurrent.',r'$\lim_{n\to\infty}P^n$ exists.',r'All states have the same period.'],'BD',
 [r'The chain consists of two disjoint deterministic two-cycles.',r'Compute $P^2$ and the possible return times to each state.'],
 r'There are two closed communicating classes, $\{1,2\}$ and $\{3,4\}$, so the whole chain is reducible and A false. Every state returns to itself deterministically after two steps and repeatedly thereafter, hence all states are recurrent, proving B. The matrix satisfies $P^2=I_4$, so $P^{2k}=I_4$ and $P^{2k+1}=P$. Since $P\ne I_4$, these two subsequences have different limits, disproving C. Return times are exactly the positive even integers, whose greatest common divisor is two, so every state has period two, proving D. The correct labels are B,D. Reducibility does not prevent all states from being recurrent, and recurrence does not guarantee convergence of transition powers.',
 r'A finite Markov chain is irreducible when every state can reach every other state; a direct sum of closed classes is reducible. Each finite closed irreducible class is positive recurrent, so all states of a reducible chain can still be recurrent when no transient states are present. Periodicity concerns the arithmetic pattern of return times and can obstruct convergence of transition probabilities. A deterministic cycle of length $d$ has period $d$, with transition powers cycling through $d$ matrices. Aperiodicity combined with finite irreducibility gives convergence within a class, but recurrence alone is insufficient. Stationary distributions may exist even when powers do not converge: uniform mass on a deterministic cycle is stationary. Multiple closed classes permit mixtures of their stationary distributions, another distinction from irreducibility.',
 [(r'For the deterministic three-cycle, do transition powers converge?',r'No. Its matrix has $P^3=I$, and the powers cycle among $I,P,P^2$. Every state is recurrent with period three.'),(r'What are stationary distributions for the displayed two-cycle-pair chain?',r'The mass must be equal within each pair. Thus $\pi=(a/2,a/2,(1-a)/2,(1-a)/2)$ for any $0\le a\le1$. These exist despite the lack of a matrix-power limit.')])
add(105,'Probability Distributions',r'Let $X_1,X_2$ be iid standard normal. Which statements are correct?',
 [r'$E\max(X_1,X_2)=1/\sqrt\pi$.',r'$E[X_1\mid X_1+X_2]=(X_1+X_2)/2$.',r'$X_1-X_2$ and $X_1+X_2$ are independent.',r'$X_1^2+X_2^2$ and $X_1/X_2$ are independent.'],'ABCD',
 [r'Use $\max(a,b)=(a+b+|a-b|)/2$ and Gaussian sum-difference independence.',r'In polar coordinates the bivariate standard normal has independent radius and uniform angle; the ratio depends only on angle.'],
 r'Put $S=X_1+X_2,D=X_1-X_2$. Both are centered normal with variance2 and covariance $1-1=0$. Joint Gaussianity therefore gives independence, proving C. Since $X_1=(S+D)/2$, conditioning on $S$ gives $E[X_1\mid S]=S/2$, proving B. Also $\max(X_1,X_2)=(S+|D|)/2$. For $D\sim N(0,2)$, $E|D|=\sqrt2\sqrt{2/\pi}=2/\sqrt\pi$, giving A. In polar coordinates $(X_1,X_2)=(R\cos\Theta,R\sin\Theta)$, the density factors as $r e^{-r^2/2}$ times $1/(2\pi)$, so $R$ and $\Theta$ are independent. The square sum is $R^2$ and the ratio is $\cot\Theta$, defined almost surely since $P(X_2=0)=0$. Thus D also holds. All four options are correct.',
 r'Independent standard normal coordinates form a rotationally symmetric multivariate Gaussian vector. Linear transformations remain jointly Gaussian, and for jointly Gaussian variables zero covariance implies independence; this implication is false for arbitrary distributions. Conditional means of Gaussian components can be obtained by an independent sum-difference decomposition. The absolute first moment of a centered normal variable with standard deviation $\sigma$ is $\sigma\sqrt{2/\pi}$, obtained by integrating its half-normal density. A maximum of two real numbers decomposes into their sum and absolute difference, linking order statistics to that moment. Polar coordinates separate the Gaussian radius from its uniform angle, including the radial Jacobian factor. Statistics depending only on radius are independent of those depending only on angle, even if an angular statistic such as a normal ratio has no finite mean.',
 [(r'For iid $N(0,\sigma^2)$ variables, find the expected maximum.',r'The difference has standard deviation $\sqrt2\sigma$, so its expected absolute value is $2\sigma/\sqrt\pi$. Half of that is $\sigma/\sqrt\pi$.'),(r'Find $E[X_1\mid X_1-X_2]$.',r'The sum is independent of the difference and has mean zero. Since $X_1=(S+D)/2$, conditioning on $D$ gives $D/2=(X_1-X_2)/2$.')])
add(106,'Probability',r'Let the distribution of $X$ be symmetric about -2. Which statements are true?',
 [r'If discrete with $P(X=-2)=2/3$, then $P(X>-2)=1/6$.',r'If discrete with $P(X=-2)=1/2$, then $P(X>-2)=1/2$.',r'If absolutely continuous, $P(X>-2)=0$.',r'If absolutely continuous, $P(X>-2)=1/2$.'],'AD',
 [r'Reflection about -2 gives equal probabilities strictly above and strictly below that point.',r'Subtract any atom at the center before dividing the remaining probability equally.'],
 r'Symmetry means $X+2$ and $-(X+2)$ have the same distribution. Thus $P(X>-2)=P(X<-2)=p$. Let $q=P(X=-2)$. The partition of the sample space gives $2p+q=1$, so $p=(1-q)/2$. With $q=2/3$, $p=1/6$, proving A. With $q=1/2$, $p=1/4$, disproving B. An absolutely continuous law has no point atoms, hence $q=0$ and $p=1/2$, proving D and disproving C. Correct labels A,D. Symmetry does not require that a mean exist; it is a distributional reflection property and the calculation works without any moment assumptions.',
 r'A distribution symmetric about a center $c$ is invariant under reflection $X\mapsto2c-X$. Corresponding events on opposite sides of the center have equal probabilities. The total mass outside a possible center atom is split equally between the strict half-lines. Absolute continuity implies every singleton has probability zero, but a discrete symmetric law may put substantial mass at its center. Consequently strict-tail probabilities need not equal one half in the discrete case. A center of symmetry is a median, though medians may be nonunique, and it equals the expectation only when that expectation exists. Heavy-tailed symmetric laws show why no integrability assumption should be inserted. Care with strict versus nonstrict inequalities is essential: adding the central atom changes $P(X\ge c)$ while leaving $P(X>c)$ unchanged.',
 [(r'A symmetric law about 0 has $P(X=0)=0.4$. Find $P(X<0)$ and $P(X\le0)$.',r'Each strict side has probability $(1-0.4)/2=0.3$. Thus $P(X<0)=0.3$ and $P(X\le0)=0.3+0.4=0.7$.'),(r'For a Cauchy law centered at -2, find $P(X>-2)$ and discuss the mean.',r'The law is continuous and symmetric, so the probability is $1/2$. Its expectation does not exist, showing that this probability conclusion does not rely on a finite mean.')])
add(107,'Probability Distributions',r'Let $X$ have density $e^{-x}$ for $x>0$ and zero otherwise. Set $Y=\lfloor X\rfloor$. Which statements are correct?',
 [r'$P(Y=2)=0$.',r'$P(Y<1.2)=1-e^{-2}$.',r'$E(Y^2)=(e+1)/(e-1)^2$.',r'$E(Y)=1/(e-1)$.'],'BCD',
 [r'$Y=k$ means $k\le X<k+1$, giving geometric probability masses.',r'Use geometric-series first and second moments, and remember $Y$ is integer-valued.'],
 r'For $k=0,1,\ldots$, $P(Y=k)=\int_k^{k+1}e^{-x}dx=(1-e^{-1})e^{-k}$. Thus $Y$ is geometric on nonnegative integers with ratio $q=e^{-1}$. In particular $P(Y=2)=e^{-2}-e^{-3}>0$, so A is false. Because $Y$ is an integer, $Y<1.2$ means $Y=0$ or1, equivalently $X<2$, giving B. The mean is $q/(1-q)=1/(e-1)$, proving D. Its second moment is $q(1+q)/(1-q)^2=(e+1)/(e-1)^2$, proving C. These formulas follow by differentiating $\sum_{k\ge0}q^k=(1-q)^{-1}$ once and twice. Correct labels B,C,D. The transformed variable has atoms although the original variable is continuous.',
 r'A many-to-one transformation of a continuous random variable can produce a discrete distribution. The floor transformation groups each unit interval into one integer value, so its mass function is obtained by integrating the original density over that interval. For an exponential law, the memoryless structure produces a geometric distribution. The nonnegative-support geometric convention has mean $q/(1-q)$ and variance $q/(1-q)^2$, where masses are $(1-q)q^k$; the alternative convention counting trials begins at one and has a different mean. Integer-valued inequalities must be converted carefully, since a noninteger threshold selects whole support points. Second moments equal variance plus the squared mean. Power-series differentiation is justified for $|q|<1$ and yields the sums of $kq^k$ and $k^2q^k$. A point event for the transformed variable corresponds to an interval event for the original one.',
 [(r'If $X$ has exponential rate2, find the mass of $\lfloor X\rfloor$ at1.',r'$P(1\le X<2)=e^{-2}-e^{-4}$. The full mass function is $(1-e^{-2})e^{-2k}$.'),(r'For the unit-rate case find $\operatorname{Var}(Y)$.',r'The geometric variance is $q/(1-q)^2$ with $q=e^{-1}$, so it is $e/(e-1)^2$. Subtracting the squared mean from the stated second moment gives the same value.')])
add(108,'Probability Distributions',r'Let $X_1,\ldots,X_{10}$ be iid Uniform$(0,1)$ with order statistics $X_{(1)},\ldots,X_{(10)}$. Which statements are true?',
 [r'$X_{(2)}\sim\operatorname{Beta}(2,9)$.',r'$X_{(10)}-X_{(1)}\sim\operatorname{Beta}(11,2)$.',r'$E[X_{(2)}]=2/11$.',r'$\operatorname{Var}(X_{(2)})=3/242$.'],'ACD',
 [r'The $k$th order statistic from $n$ uniforms has Beta$(k,n+1-k)$ law.',r'Use beta moments; the sample range instead has Beta$(n-1,2)$ law.'],
 r'The second order statistic has density $10!/[1!8!]\,x(1-x)^8=90x(1-x)^8$, the Beta$(2,9)$ density, proving A. Beta$(a,b)$ mean is $a/(a+b)$ and variance $ab/[(a+b)^2(a+b+1)]$. Thus the mean is $2/11$, proving C, and variance is $18/(121\cdot12)=3/242$, proving D. The range density is $n(n-1)r^{n-2}(1-r)$ on $(0,1)$: integrate the joint min-max density $n(n-1)(v-u)^{n-2}$ over $u\in(0,1-r)$. For $n=10$ this is Beta$(9,2)$, not Beta$(11,2)$, so B is false. Correct labels A,C,D.',
 r'Order statistics arrange a sample in increasing order and have distributions determined by counting observations below and above a threshold. For iid uniforms, the $k$th order statistic is beta with parameters $k$ and $n+1-k$. The extra one in the parameter sum arises from the density at the selected observation and should not be omitted. Beta moments follow from ratios of beta integrals, giving mean $a/(a+b)$ and variance $ab/[(a+b)^2(a+b+1)]$. The sample range is a difference of dependent extrema, so its law cannot be found by subtracting independent beta variables. Its density is obtained from the joint minimum and maximum or the uniform spacings, and is Beta$(n-1,2)$. Checking parameter sums and expected range values can catch off-by-two errors. Continuity ensures ties have probability zero.',
 [(r'For five uniforms, find the law and mean of the minimum.',r'The minimum is Beta$(1,5)$, with density $5(1-x)^4$ and mean $1/6$.'),(r'For five uniforms, find the range distribution and expectation.',r'The range is Beta$(4,2)$ with density $20r^3(1-r)$, so its mean is $4/(4+2)=2/3$. This equals the difference of mean maximum $5/6$ and mean minimum $1/6$.')])
add(109,'Statistical Inference',r'Let $(X_i)$ be iid Bernoulli with $P(X_i=1)=p\in(0,1)$. Which estimator sequences are consistent for $p$?',
 [r'$n^{-1}\sum_{i=1}^nX_i$.',r'$0.5(X_n+X_{n+1})$.',r'$n^{-1}\sum_{i=1}^nX_i^i$.',r'$n^{-1}\sum_{i=1}^nX_{2i-1}X_{2i}$.'],'AC',
 [r'Use the law of large numbers and $0^i=0$, $1^i=1$.',r'The last estimator averages independent pair-products with mean $p^2$, while B always uses only two trials.'],
 r'A converges almost surely, hence in probability, to $E X_i=p$ by the law of large numbers. Since each $X_i$ is 0 or1 and $i\ge1$, $X_i^i=X_i$ exactly, so C is identical to A and consistent. B takes values 0,1/2,1 with a distribution independent of $n$ and nonvanishing spread. For example the event $X_n=X_{n+1}=0$ has probability $(1-p)^2>0$, and on it the error is $p$; therefore $P(|B-p|>p/2)\ge(1-p)^2$ for every $n$. D averages iid Bernoulli$(p^2)$ pair-products from disjoint independent pairs, so it converges to $p^2\ne p$ for $0<p<1$. Thus only A,C are consistent. Unbiasedness of the two-observation average does not compensate for its fixed variance.',
 r'Consistency means convergence in probability to the parameter for each allowed parameter value as sample size increases. The law of large numbers gives consistency of averages of iid integrable observations for their population means. It also applies to derived observations formed from disjoint independent blocks, but their mean may be a different parameter function. Bernoulli variables are idempotent under positive integer powers, so apparently changing powers can leave an estimator exactly unchanged. An estimator using a fixed number of fresh observations has a nondegenerate error distribution that does not shrink with the index, even if it is unbiased. To disprove consistency, exhibit a fixed positive error threshold with probability bounded away from zero. A bias limit different from the target also invalidates consistency. Independence of nonoverlapping pairs matters when applying the ordinary iid law of large numbers.',
 [(r'Is the average of iid products $X_{2i-1}X_{2i}$ consistent for $p^2$?',r'Yes. The pair-products are iid with success probability $p^2$, so their sample average tends almost surely to $p^2$.'),(r'Can taking the square root of that average estimate $p$ consistently?',r'Yes. The average converges to $p^2$, and square root is continuous on nonnegative values. The continuous mapping theorem gives convergence to $\sqrt{p^2}=p$, since $p>0$.')])
add(110,'Probability',r'Let $X_i$ be iid with $P(X_i=1)=P(X_i=3)=1/2$, and $Y_n=\sum_{i=1}^nX_i$. Which statements are correct?',
 [r'$Y_n/n\to2$ in probability.',r'$\operatorname{Var}(Y_n/n^{2/3})\to0$.',r'$Y_n/n^{2/3}\to c$ in probability for some finite $c>0$.',r'$Y_n/n^2\to0$ in probability.'],'ABD',
 [r'Compute $EX_i$ and $\operatorname{Var}X_i$.',r'Small variance concerns deviation from a possibly divergent mean; also use the deterministic bound $n\le Y_n\le3n$.'],
 r'$EX_i=2$, $EX_i^2=5$, and variance is1. Hence $EY_n=2n$ and $\operatorname{Var}Y_n=n$. The law of large numbers proves A. For B, $\operatorname{Var}(Y_n/n^{2/3})=n/n^{4/3}=n^{-1/3}\to0$. C is false despite this shrinking variance: $Y_n\ge n$ surely, so $Y_n/n^{2/3}\ge n^{1/3}\to\infty$, ruling out every finite limit. D holds even deterministically, because $0\le Y_n/n^2\le3/n\to0$. Correct labels A,B,D. This example separates concentration around an expectation from convergence to a fixed finite constant; the expectation of the B-scaled variable is $2n^{1/3}$ and diverges.',
 r'The law of large numbers normalizes sums by their number of terms and identifies the limit as the common expectation. Variance of an independent sum is the sum of variances, and multiplying a variable by a scalar multiplies variance by its square. A variance tending to zero shows concentration around the sequence of means, but those means may themselves diverge. To infer convergence to a constant from variance decay, the means must also converge to that constant. Deterministic support bounds can be stronger than probabilistic inequalities and prove convergence or divergence uniformly over all outcomes. For positive bounded observations, different powers of sample size produce zero, finite, or infinite scaled limits depending on whether the power is above, equal to, or below one. Chebyshev inequality is useful for random fluctuation control but cannot correct an inappropriate deterministic normalization.',
 [(r'For these variables, find $\operatorname{Var}(Y_n/n)$ and the limit.',r'The variance is $n/n^2=1/n$, and the mean is2. Chebyshev therefore yields convergence in probability to2.'),(r'What happens to $(Y_n-2n)/n^{2/3}$?',r'It has mean zero and variance $n^{-1/3}\to0$, so Chebyshev gives convergence in probability to zero. Centering removes the diverging deterministic mean present in the uncentered version.')])
add(111,'Statistical Inference',r'Let $X_1,\ldots,X_{10}$ have density $f_\theta(x)=e^{\theta-x}$ for $x\ge\theta$ and zero otherwise. Test $H_0:\theta\le3$ versus $H_1:\theta>3$. Write $x_{(1)}=\min_i x_i$ and $L(\theta)$ for the likelihood. Which statements are correct?',
 [r'If $x_{(1)}\le3$, $\sup_{\theta\le3}L(\theta)=e^{10x_{(1)}}e^{-\sum_i x_i}$.',r'If $x_{(1)}>3$, $\sup_{\theta\le3}L(\theta)=e^{10x_{(1)}}e^{-\sum_i x_i}$.',r'The size-$\alpha$ LRT rejects for $x_{(1)}\ge1/3-10\log\alpha$.',r'The size-$\alpha$ LRT rejects for $x_{(1)}\ge3-(1/10)\log\alpha$.'],'AD',
 [r'The likelihood is increasing on its feasible region $\theta\le x_{(1)}$.',r'The minimum has shifted exponential rate10; the largest null rejection probability occurs at $\theta=3$.'],
 r'The likelihood is $e^{10\theta-\sum_i x_i}\mathbf1_{\{\theta\le x_{(1)}\}}$. Its unconstrained maximum occurs at $\theta=x_{(1)}$; under the null the maximum occurs at $\min(3,x_{(1)})$. Thus A is true, whereas for $x_{(1)}>3$ the null maximum is $e^{30-\sum_i x_i}$, disproving B. The likelihood ratio equals1 when $x_{(1)}\le3$ and $e^{-10(x_{(1)}-3)}$ when $x_{(1)}>3$, so reject for a large minimum. Under parameter $\theta$, $X_{(1)}-\theta$ is exponential of rate10. For a cutoff $c>3$, the supremum null rejection probability is $e^{-10(c-3)}$, attained at $\theta=3$. Setting it equal to $\alpha$ gives $c=3-(1/10)\log\alpha$, proving D and disproving C. Correct labels A,D.',
 r'A likelihood-ratio test compares the maximum likelihood under a restricted null parameter set with the unrestricted maximum. Parameter-dependent support introduces an indicator restricting feasible parameter values, which must be included before optimization. For shifted exponential data the likelihood rises with the shift until it reaches the sample minimum, so both maxima lie on boundaries. The statistic is the minimum rather than the sample mean. A composite-null test size is the supremum rejection probability across the null set, and stochastic monotonicity locates the least favorable parameter at its largest allowed value. The minimum excess has rate equal to sample size times the individual rate, yielding an exact cutoff. Logarithm signs matter because $\log\alpha<0$ for a significance level between zero and one, so the rejection threshold lies above the null boundary.',
 [(r'At sample size10 and $\alpha=0.05$, express the critical minimum.',r'The cutoff is $3-\log(0.05)/10=3+\log20/10$, approximately3.2996. Reject when the minimum exceeds this value.'),(r'For sample size $n$ and known exponential rate $\lambda$, with null boundary $\theta_0$, find the cutoff.',r'The minimum excess has rate $n\lambda$. Size equation $e^{-n\lambda(c-\theta_0)}=\alpha$ gives $c=\theta_0-\log\alpha/(n\lambda)$.')])
add(112,'Statistical Inference',r'Let $X_1,\ldots,X_n$ be iid $N(\mu,\sigma^2)$ and $(\widehat\mu,\widehat\sigma^2)$ their maximum likelihood estimators. Which statements are correct?',
 [r'$(n-1)\widehat\sigma^2/\sigma^2\sim\chi^2_{n-1}$.',r'$\widehat\sigma^2$ is unbiased for $\sigma^2$.',r'$\operatorname{Var}(\widehat\sigma^2)\to0$ as $n\to\infty$.',r'$n^2\widehat\sigma^4/[(n-1)(n+1)]$ is unbiased for $\sigma^4$.'],'CD',
 [r'The MLE variance has denominator $n$, not $n-1$.',r'Use $Q=n\widehat\sigma^2/\sigma^2\sim\chi^2_{n-1}$ and its first two moments.'],
 r'For $n\ge2$, $\widehat\mu=\bar X$ and $\widehat\sigma^2=n^{-1}\sum_i(X_i-\bar X)^2$. The exact chi-square pivot is $Q=n\widehat\sigma^2/\sigma^2\sim\chi^2_{n-1}$, not the $(n-1)$-scaled quantity, so A is false. Since $EQ=n-1$, $E\widehat\sigma^2=(n-1)\sigma^2/n$, disproving B. The variance is $(\sigma^4/n^2)\operatorname{Var}Q=2(n-1)\sigma^4/n^2\to0$, proving C. A chi-square variable with $\nu$ degrees has second moment $\nu(\nu+2)$. Hence $E\widehat\sigma^4=\sigma^4(n-1)(n+1)/n^2$, and D is unbiased. Correct labels C,D. The fourth-power notation means $(\widehat\sigma^2)^2$; the sample-size-one degenerate MLE case is outside the usual positive-variance estimation formula and is irrelevant to the stated asymptotic assertion.',
 r'Normal variance estimation distinguishes the maximum likelihood estimator from the unbiased sample variance. The MLE divides residual sum of squares by $n$, while unbiasedness requires $n-1$ after estimating the mean. Orthogonal projection of a Gaussian sample onto the mean-zero contrast subspace leaves $n-1$ squared standard-normal coordinates, giving the chi-square pivot. Its mean is the degrees of freedom and its variance is twice that value. These moments determine bias and variance of the MLE and a correction for estimating the squared variance parameter. A vanishing estimator variance does not itself prove unbiasedness, and in this case the finite-sample bias persists while tending to zero asymptotically. Powers of an estimator require second moments rather than simply squaring its expectation. Denominator conventions must remain consistent throughout the pivot, bias, and higher-moment calculations.',
 [(r'For $n=5$, find $E\widehat\sigma^2$ and its variance.',r'The expectation is $4\sigma^2/5$ and the variance is $2\cdot4\sigma^4/25=8\sigma^4/25$.'),(r'Express an unbiased estimator of $\sigma^4$ using the unbiased sample variance $S^2$.',r'Since $(n-1)S^2/\sigma^2\sim\chi^2_{n-1}$, $E(S^2)^2=\sigma^4(n+1)/(n-1)$. Multiply by $(n-1)/(n+1)$ to obtain unbiasedness.')])
add(113,'Statistical Inference',r'For $x=1,2,3,4,5,6,7$, the null masses are $(0.01,0.01,0.01,0.01,0.01,0.01,0.94)$ and alternative masses $(0.06,0.05,0.04,0.03,0.02,0.01,0.79)$. Which statements are correct for testing $H_0$ against $H_1$?',
 [r'The most powerful size-0.04 critical region is $\{x:x\le4\}$.',r'The most powerful size-0.04 critical region is $\{x:3\le x\le6\}$.',r'The most powerful size-0.04 test has power 0.18.',r'A most powerful size-0.04 test does not exist.'],'AC',
 [r'Rank the likelihood ratios $f_1(x)/f_0(x)$.',r'Four of the highest-ratio support points use exactly 0.04 of null probability.'],
 r'The likelihood ratios at points1 through7 are $6,5,4,3,2,1,79/94$, strictly decreasing. Neyman–Pearson therefore allocates rejection probability first to1,2,3,4. Their total null mass is0.04, so this nonrandomized test has exactly the required size and is most powerful, proving A. Its power is $0.06+0.05+0.04+0.03=0.18$, proving C. The region3 through6 has the same size but power $0.04+0.03+0.02+0.01=0.10$, so B is false. The exhibited test disproves D. Correct labels A,C. Point7 is strongly likely under both hypotheses but has the smallest ratio and should not receive rejection probability in a small-size test.',
 r'For simple hypotheses on a finite support, Neyman–Pearson testing selects outcomes by decreasing alternative-to-null likelihood ratio. The size constraint is a budget of null probability, while power is the corresponding alternative probability. This is a finite allocation problem in which the likelihood ratio measures power gain per unit size. If the highest-ranked outcomes exactly fill the requested size, a nonrandomized most powerful test exists. If they overshoot, randomization at the boundary outcome can produce exact size. Absolute alternative mass alone is not the correct ranking criterion; an outcome common under both hypotheses can have a small ratio. Comparing equal-size candidate regions provides a direct power check. Distinct ratios ensure the optimal ordering is unambiguous, though sets outside the support have no effect on either size or power.',
 [(r'For the displayed masses, find the most powerful size-0.03 test and its power.',r'Reject at1,2,3, whose null masses sum to0.03 and ratios are the largest. The power is0.06+0.05+0.04=0.15.'),(r'Find a most powerful size-0.025 test.',r'Reject surely at1 and2, spending0.02, and reject with probability1/2 at3 to add0.005. The power is0.06+0.05+0.5(0.04)=0.13. No lower-ratio outcome can improve that allocation.')])
add(114,'Statistical Inference',r'Let $X_1,\ldots,X_n$ be iid $N(\theta,\sigma^2)$ with known variance, and prior $\theta\sim N(\mu,\tau^2)$. Which statements are correct?',
 [r'Under squared-error loss, the Bayes estimator is the posterior mean.',r'Under squared-error loss, the Bayes estimator is the posterior median.',r'Under absolute-error loss, the Bayes estimator is the posterior median.',r'Under absolute-error loss, the Bayes estimator is the posterior mean.'],'ABCD',
 [r'Normal likelihood and normal prior give a normal posterior.',r'The general Bayes rules differ by loss, but posterior mean and median coincide in this model.'],
 r'The posterior is normal with variance $V=(n/\sigma^2+1/\tau^2)^{-1}$ and mean $m=V[n\bar X/\sigma^2+\mu/\tau^2]$. Under squared error, posterior expected loss is $(a-m)^2+V$ and is uniquely minimized at $a=m$, proving A. Under absolute error, a posterior median minimizes expected loss, proving C. A normal posterior is continuous and symmetric about $m$, with unique median also $m$. Therefore the estimator described as the posterior median is also the squared-error minimizer, proving B; the estimator described as the posterior mean is also the absolute-error minimizer, proving D. All four labels are true for this specifically normal model. The general mean-versus-median rules alone would miss B and D because here they denote the same number.',
 r'Bayesian point estimation minimizes posterior expected loss after observing the data. Squared-error loss selects the posterior mean when the second moment exists, by completing the square. Absolute-error loss selects any posterior median; for a continuous positive density the unique median is the point where its cumulative probability is one half. A normal prior is conjugate to a normal mean likelihood with known variance, giving a normal posterior whose precision is the sum of prior and data precisions. Its mean is a weighted average of the prior mean and sample mean. Because a normal distribution is symmetric, mean and median coincide, so the two different loss functions produce the same estimator in this model. Statements true for a specific posterior should not be rejected merely because they are not general rules for every distribution.',
 [(r'With one observation $x=4$, $\sigma^2=1$, and prior $N(0,1)$, find both Bayes estimators.',r'The posterior variance is $1/(1+1)=1/2$ and mean is $(4+0)/2=2$. Its median is2, so both squared-error and absolute-error estimators are2.'),(r'For an exponential posterior of rate1, compare the two Bayes estimators.',r'The posterior mean is1, while its median solves $1-e^{-m}=1/2$, giving $m=\log2$. Squared error selects1 and absolute error selects$\log2$, showing coincidence is special to symmetric posteriors.')])
