from pack_writer import Writer, ROOT, RAW
import json,sys
sys.path.insert(0,str(ROOT))
from core import load_project_bank
W=Writer('2022-june','-q091-120')
pending={q.question_number for q in load_project_bank(ROOT,False) if q.paper_id=='2022-june' and q.review_status=='pending'}
def add(n,topic,prompt,opts,ans,hints,sol,theory,ex,status='reviewed',note=''):
 if n not in pending and not any(q['question_number']==n for q in W.packs): return
 W.add(n,'Statistics' if topic in ['Probability','Probability Distributions','Statistical Inference','Stochastic Processes','Regression and Multivariate Analysis','Sampling and Design of Experiments'] else 'Mathematics',topic,'Moderate',prompt,opts,ans,hints,sol,theory,ex,status,note)
add(115,'Regression and Multivariate Analysis',r'Consider $Y_i=\sum_{j=1}^p\beta_jx_{ij}+\varepsilon_i$, with mean-zero uncorrelated errors of common variance $\sigma^2$. Let $\widehat y_i$ be least-squares fits and $\widehat\varepsilon_i$ residuals. Which statements are always correct?',
 [r'$\sum_i\widehat\varepsilon_i=0$ and $\sum_i\widehat y_i\widehat\varepsilon_i=0$.',r'$\sum_ix_{ij}\widehat\varepsilon_i=0$ for every $j$.',r'$\sum_i\widehat\varepsilon_i=0$ and $\sum_ix_{ij}\widehat\varepsilon_i=0$ for every $j$.',r'$\sum_i\widehat y_i\widehat\varepsilon_i=0$.'],'BD',
 [r'Least-squares normal equations make the residual orthogonal to every design column.',r'The fitted vector lies in their span; zero residual sum requires a constant column, which is not stated.'],
 r'In matrix notation the least-squares fitted vector is the orthogonal projection $\widehat y$ of $y$ onto $\operatorname{col}X$. Its residual $e=y-\widehat y$ is orthogonal to that column space, so $X^Te=0$, proving B. Because $\widehat y\in\operatorname{col}X$, also $\widehat y^Te=0$, proving D. A and C additionally require $\mathbf1^Te=0$, which need not hold without an intercept or a constant vector in the design span. For example take one predictor $x=(1,2)^T$ and observed $y=(1,0)^T$. The least-squares coefficient is $1/5$, fit $(1/5,2/5)$ and residual $(4/5,-2/5)$, whose sum is $2/5\ne0$, although its dot products with $x$ and the fit are zero. Hence A,C are not always correct. The error-distribution assumptions are unnecessary for these algebraic identities. Correct labels B,D.',
 r'Ordinary least squares minimizes squared Euclidean residual length. Its normal equations express orthogonality of the residual to the design matrix column space, including every predictor and every linear combination of predictors such as the fitted vector. This geometric conclusion holds even if the coefficient estimates are not unique because the design is rank-deficient; the fitted projection itself remains unique. The often-quoted identity that residuals sum to zero depends on including an intercept, or more generally having the constant vector in the design span. Mean-zero random errors imply unbiasedness under suitable rank assumptions, but do not force the observed residual sum to vanish in a no-intercept fit. Uncorrelated equal-variance errors underpin Gauss–Markov variance results, a different issue from the deterministic normal equations. Separating algebraic fit identities from probabilistic expectations prevents overgeneralization.',
 [(r'For $x=(1,1,1)^T$ and $y=(1,2,6)^T$, compute the fitted vector and residual sum.',r'The only predictor is constant, so its coefficient is the sample mean3. The fit is $(3,3,3)$ and residual is $(-2,-1,3)$, summing to zero.'),(r'If the design has dependent columns, does fit-residual orthogonality still hold?',r'Yes. Least squares projects onto the same column space regardless of redundant columns. Every minimizing coefficient vector gives the same fitted vector, and the residual is orthogonal to that vector and to each column.')])
add(116,'Regression and Multivariate Analysis',r'Let $(X,Y,Z)^T\sim N_3(0,\Sigma)$ with $\Sigma=\begin{pmatrix}1&\rho&0\\\rho&1&0\\0&0&1\end{pmatrix}$, $|\rho|<1$. Which statements are true?',
 [r'$\operatorname{Cor}(X^2,Y^2)=\rho^2$.',r'$\operatorname{Cor}(X^2,Y)=0$.',r'$\operatorname{Cor}(X^2,Z^2)=0$.',r'$\operatorname{Cor}(X^2,Y^2+Z^2)=\rho^2$.'],'ABC',
 [r'Use $Y=\rho X+\sqrt{1-\rho^2}U$ with an independent standard normal $U$.',r'For D the variance of the sum $Y^2+Z^2$ is4 rather than2.'],
 r'For standard normal $X$, $EX^2=1$, $EX^4=3$, so $\operatorname{Var}(X^2)=2$. Writing $Y=\rho X+\sqrt{1-\rho^2}U$ gives $E(X^2Y^2)=3\rho^2+(1-\rho^2)=1+2\rho^2$. Thus covariance is $2\rho^2$ and correlation is $\rho^2$, proving A. Centered Gaussian odd moments vanish, so $E(X^2Y)=0$ and B holds. The block-diagonal covariance makes $Z$ independent of $(X,Y)$; its square is independent of $X^2$, proving C. Finally $\operatorname{Cov}(X^2,Y^2+Z^2)=2\rho^2$ but $\operatorname{Var}(Y^2+Z^2)=2+2=4$, so correlation is $2\rho^2/\sqrt{2\cdot4}=\rho^2/\sqrt2$. Therefore D is false as a general parameterized identity, though it coincides at $\rho=0$. Correct labels A,B,C.',
 r'For a centered Gaussian vector, linear uncorrelated blocks are independent, and the fourth moments can be computed through independent-normal representations or Gaussian moment formulas. A standard normal square has mean one and variance two. Correlation between squared correlated normals is the square of their original correlation, so squaring removes its sign. Odd total-degree centered Gaussian moments vanish by symmetry, giving zero covariance between a square and a linear coordinate even when they are dependent. Independence of one coordinate from a vector persists under measurable transformations. Adding an independent square to one side changes its variance without changing its covariance with the other side, thereby reducing the correlation. Correlation requires dividing covariance by both standard deviations; using a covariance identity alone misses this normalization. General parameter identities should be checked away from special values where alternatives happen to coincide.',
 [(r'If $\rho=1/2$, find $\operatorname{Cor}(X^2,Y^2)$ and $\operatorname{Cor}(X^2,Y^2+Z^2)$.',r'The first is $1/4$. The second is $(1/4)/\sqrt2=1/(4\sqrt2)$, smaller because of independent added variation.'),(r'Are $X^2$ and $Y$ necessarily independent when their covariance is zero?',r'No. For nonzero $\rho$, the conditional variance of $Y$ given $X^2$ is influenced by the magnitude of $X$. Indeed $E(Y^2\mid X^2)=\rho^2X^2+1-\rho^2$, which is nonconstant. Zero correlation does not imply independence for these nonlinear variables.')])
add(117,'Probability Distributions',r'A lifetime random variable has hazard $r(x)=2x/(1+x^2)$ for $x>0$. Which options are correct?',
 [r'$S(x)=1/(1+x^2)$.',r'$S(x)=x^2/(1+x^2)$.',r'The survival function cannot be determined.',r'The survival, density, and distribution functions can all be determined.'],'AD',
 [r'The hazard is $-d\log S(x)/dx$, with lifetime normalization $S(0)=1$.',r'Integrate to obtain cumulative hazard $\log(1+x^2)$, then differentiate survival.'],
 r'For a positive absolutely continuous lifetime, $S(0)=1$ and $r=f/S=-S\prime/S$. Therefore $S(x)=\exp[-\int_0^x2t/(1+t^2)dt]=\exp[-\log(1+x^2)]=1/(1+x^2)$, proving A. The distribution is $F(x)=1-S(x)=x^2/(1+x^2)$ and the density is $f(x)=-S\prime(x)=2x/(1+x^2)^2$, so D holds. B is the distribution function mislabeled as survival; it increases from zero to one instead of decreasing. C is false under the standard lifetime normalization. The cumulative hazard tends to infinity, so survival tends to zero and the density integrates to one, with no probability remaining at infinite lifetime. Correct labels A,D.',
 r'The hazard rate of a continuous lifetime is its conditional instantaneous failure rate, $r(x)=f(x)/S(x)$ when survival is positive. Since $S\prime=-f$, integrating the logarithmic derivative gives $S(x)=\exp[-R(x)]$, where $R(x)$ is the cumulative hazard from zero. The normalization $S(0)=1$ corresponds to a strictly positive lifetime without an atom at zero. Once survival is known, the cumulative distribution is its complement and the density is its negative derivative. A valid survival function is nonincreasing, begins at one, and tends to zero for a proper finite lifetime. A diverging cumulative hazard ensures that final limit. These monotonicity checks quickly detect a distribution function presented as survival. A hazard specified only after a possible mass at zero would require that initial mass separately, but the conventional continuous positive lifetime model supplies the stated normalization.',
 [(r'If $r(x)=\lambda$ for $x>0$, find survival and density.',r'The cumulative hazard is $\lambda x$, so $S=e^{-\lambda x}$ and $f=\lambda e^{-\lambda x}$, the exponential lifetime law.'),(r'If $r(x)=3x^2$ for $x>0$, find the distribution.',r'Integrating gives $R=x^3$, so $S=e^{-x^3}$, $F=1-e^{-x^3}$, and $f=3x^2e^{-x^3}$. The cumulative hazard diverges, ensuring total mass one.')])
add(118,'Statistical Inference',r'Observe $X\sim N(\mu,1)$ with unknown $\mu\in\mathbb R$, and estimate $\mu$ under squared-error loss. Which statements are correct?',
 [r'The Bayes estimator under a proper prior is always biased.',r'Some proper prior has an unbiased Bayes estimator.',r'The Bayes estimator under an improper prior is always biased.',r'Some improper prior has an unbiased Bayes estimator.'],'AD',
 [r'For the full normal location family, $X$ is the unique unbiased estimator as a function of one observation, by completeness.',r'The posterior mean equals $x+m\prime(x)/m(x)$ for the marginal density $m$; equality to $x$ would force a constant marginal.'],
 r'Under squared error the Bayes estimator is the posterior mean $\delta(x)$. The full one-observation normal location family is complete: an integrable function with expectation zero for every real $\mu$ is zero almost everywhere. Since $X$ is unbiased, an unbiased $\delta$ would therefore have to equal $x$ almost everywhere. For a proper prior $\pi$, the marginal density is $m(x)=\int\phi(x-\mu)\pi(d\mu)$, and differentiation gives $m\prime(x)=\int(\mu-x)\phi(x-\mu)\pi(d\mu)$. Hence $\delta(x)=x+m\prime(x)/m(x)$. Equality to $x$ forces $m\prime=0$; a constant positive function cannot be a proper probability density on $\mathbb R$. Thus no proper prior produces an estimator unbiased for all $\mu$, proving A and disproving B. With the improper flat prior $\pi(\mu)\propto1$, the posterior is $N(x,1)$ and $\delta(x)=x$, which is unbiased. Thus D is true and C false. Here biased means failure of global unbiasedness, not nonzero bias at every individual parameter point.',
 r'A proper prior is a probability distribution with total mass one; an improper prior is an unnormalized measure which may still yield a proper posterior. Squared-error Bayes estimation uses the posterior mean. In the normal location model, the derivative of the marginal density gives a formula for the posterior mean’s deviation from the observation. Completeness of the full normal exponential family ensures uniqueness of unbiased estimators based on one observation; it follows from uniqueness of the Laplace transform after multiplying by the normal density. A proper marginal must integrate to one and cannot be a nonzero constant across the whole real line, ruling out an unbiased proper-prior posterior mean. The flat improper prior avoids this marginal normalization and yields the usual observation estimator. Bias is a function of the parameter, and an estimator can be biased overall while its bias vanishes at one parameter value.',
 [(r'For prior $N(0,\tau^2)$, compute the estimator and its bias.',r'The posterior mean is $\delta(X)=\tau^2X/(1+\tau^2)$. Its expectation is $\tau^2\mu/(1+\tau^2)$, so bias is $-\mu/(1+\tau^2)$. It vanishes at0 but the estimator is not globally unbiased.'),(r'For the flat prior on $\mathbb R$, verify posterior propriety and unbiasedness.',r'The likelihood as a function of $\mu$ is proportional to $e^{-(X-\mu)^2/2}$ and integrates to $\sqrt{2\pi}$. Normalization gives posterior $N(X,1)$, so the posterior mean is $X$ and its frequentist expectation is $\mu$.')])
add(119,'Regression and Multivariate Analysis',r'In $Y_i=\beta X_i+\varepsilon_i$, let iid errors be $N(0,\sigma^2)$ and fixed predictors $X_i$ be positive and distinct. Consider $\widehat\beta_1=\sum_i(Y_i-\bar Y)(X_i-\bar X)/\sum_i(X_i-\bar X)^2$ and $\widehat\beta_2=\sum_iY_iX_i/\sum_iX_i^2$. Which statements are correct?',
 [r'Both estimators are unbiased for $\beta$.',r'$\widehat\beta_1$ has larger variance than $\widehat\beta_2$.',r'$\widehat\beta_2$ has larger variance than $\widehat\beta_1$.',r'They have the same variance.'],'AB',
 [r'Expand each estimator as $\beta$ plus a fixed weighted sum of mean-zero errors.',r'Compare $S_{xx}=\sum X_i^2-n\bar X^2$ with $\sum X_i^2$; positivity makes $\bar X>0$.'],
 r'Let $S_{xx}=\sum_i(X_i-\bar X)^2>0$. Since $\sum_i(X_i-\bar X)=0$, $\widehat\beta_1=\beta+\sum_i(X_i-\bar X)\varepsilon_i/S_{xx}$. Also $\widehat\beta_2=\beta+\sum_iX_i\varepsilon_i/\sum_iX_i^2$. Both error sums have mean zero, proving A. Independence gives $\operatorname{Var}\widehat\beta_1=\sigma^2/S_{xx}$ and $\operatorname{Var}\widehat\beta_2=\sigma^2/\sum_iX_i^2$. Because all predictors are positive, $\bar X>0$, so $S_{xx}=\sum_iX_i^2-n\bar X^2<\sum_iX_i^2$. Thus the first variance is strictly larger, proving B and disproving C,D. The no-intercept model supplies extra known structure; fitting an unnecessary intercept remains unbiased for the slope but uses less information. The standard nondegenerate variance assumption $\sigma^2>0$ is understood.',
 r'Linear regression through the origin differs from regression with an estimated intercept. When the true intercept is known to be zero, the uncentered least-squares slope uses the predictor vector directly and is the efficient linear unbiased estimator under equal independent error variances. A centered slope effectively estimates an extra intercept and uses only predictor variation around its mean. Both remain unbiased under the zero-intercept model, but their variances depend on the squared norms of different weight vectors. The identity $\sum(X_i-\bar X)^2=\sum X_i^2-n\bar X^2$ quantifies the information lost by centering. Strict positivity of predictors makes the sample mean nonzero, ensuring strict variance inequality; if their mean were zero the estimators would coincide. Normality is not needed for these first two moments, though it gives exact Gaussian distributions for the estimates.',
 [(r'For fixed predictors1 and2, compare the two variances.',r'$\sum X_i^2=5$ and $S_{xx}=(1-1.5)^2+(2-1.5)^2=1/2$. Thus variances are $2\sigma^2$ for the centered slope and $\sigma^2/5$ for the through-origin slope.'),(r'For predictors -1 and1, do the estimators differ?',r'The predictor mean is0, so centering does not change them and $S_{xx}=\sum X_i^2=2$. Both estimates are $(Y_2-Y_1)/2$ and have variance $\sigma^2/2$.')])
add(120,'Regression and Multivariate Analysis',r'Consider single-linkage agglomerative clustering of $X=(1,0)$, $Y=(0,2)$, $Z=(3,3)$ using squared Euclidean distances, starting with three singleton clusters. Which statements are correct?',
 [r'After the first merge the distance between the two remaining clusters is10.',r'The first merge joins $X$ and $Y$.',r'After the first merge the distance between the two remaining clusters is13.',r'The first merge joins $X$ and $Z$.'],'AB',
 [r'Compute all three squared distances before choosing the nearest pair.',r'Single linkage uses the minimum cross-cluster pairwise distance.'],
 r'The squared distances are $d(X,Y)=(1-0)^2+(0-2)^2=5$, $d(X,Z)=(1-3)^2+(0-3)^2=13$, and $d(Y,Z)=(0-3)^2+(2-3)^2=10$. The unique smallest distance is5, so the first merge forms $\{X,Y\}$, proving B and disproving D. Single-linkage distance from this cluster to $\{Z\}$ is $\min\{d(X,Z),d(Y,Z)\}=\min\{13,10\}=10$, proving A and disproving C. Correct labels A,B. The value13 would be the complete-linkage distance, while using ordinary rather than squared Euclidean distances would yield $\sqrt{10}$ for the same single-linkage merge distance.',
 r'Agglomerative hierarchical clustering starts from singleton clusters and repeatedly joins the two closest clusters under a chosen linkage rule. Single linkage defines intercluster distance as the smallest pairwise distance across the clusters; complete linkage uses the largest, and average linkage uses an average. The first step is common to these rules for singleton clusters, but later merge distances differ. Squared Euclidean distances preserve ordering of individual pairs because squaring is increasing on nonnegative distances, but the numerical merge heights change. Squared distance is not generally a metric because it may fail the triangle inequality; it can nonetheless be used as a specified dissimilarity. Three-point examples make linkage differences transparent after the first merge. One should calculate every pair and then apply the rule explicitly rather than using distance between cluster centroids, which is a different method.',
 [(r'For the displayed points, what is the complete-linkage distance after the first merge?',r'The first merge is still $X,Y$, since singleton distances have minimum5. Complete linkage to $Z$ is $\max\{13,10\}=13$.'),(r'What is the average-linkage squared-distance value after merging $X,Y$?',r'There are two cross-cluster pairs with squared distances13 and10. Their average is $(13+10)/2=11.5$, distinct from single-linkage10 and complete-linkage13.')])
