from pathlib import Path
import json,re,math
from core import parse_bank,export_bank,load_project_bank
root=Path('.')
extra={
4:'For each Sudoku cell, the candidate set is the intersection of missing digits from its row, column, and box. Empty candidate sets reject a branch. A single candidate is forced, and branching only when no forced cell remains yields a complete finite search whose uniqueness can be checked by forbidding the proposed target digit.',
10:'Equality of nonzero standard deviations permits equating the corresponding sums of squares after dividing by the appropriate degrees of freedom. Zero standard deviation implies every observation equals its mean and produces the undefined ratio zero to zero, so the usual ratio calculation requires nondegeneracy.',
22:'The preimage of zero is a set, not an inverse function. Distinct functions may have the same preimage. Counting possible zero sets therefore requires identifying the family of subsets they realize rather than counting the infinitely many functions themselves.',
24:'A subsequence is obtained by restricting indices to an increasing sequence. For a bounded periodic sequence its limsup is its maximum periodic value. Replacing n by 2n or 3n requires re-evaluating every occurrence of the index, including parity-dependent signs.',
25:'A zero is simple in the differentiable sense when its derivative is nonzero. An accumulation of distinct zeros forces a common zero of the function and derivative by continuity and the definition of derivative. Compactness turns an infinite set of zeros in a bounded closed interval into such an accumulation.',
26:'Rolle’s theorem bounds distinct roots of a differentiable function by one more than the number of distinct roots of its derivative. Its use here concerns distinct locations, not multiplicity. Additive constants change an antiderivative’s zero set without changing its derivative, so exact root counts cannot be inferred universally.',
31:'A quadratic form associated with a symmetric bilinear form is Q(v)=(v,v). A nonzero vector with Q(v)=0 is called isotropic. Opposite signs make a real form indefinite; orthogonal positive and negative directions allow an explicit isotropic vector by balancing their squared coefficients.',
32:'Sylvester’s criterion applies to real symmetric matrices: positive definiteness is equivalent to positivity of every leading principal minor. A statement giving a sufficient range need not state the exact necessary threshold. Zero minors must be excluded for strict positive definiteness, even if the matrix remains positive semidefinite.',
33:'For z=x+iy, the exponential e^(iz) has modulus e^(−y) and arbitrary argument x modulo 2π. A set is convex when it contains the entire segment between each pair of its points. Removing the origin from a disk preserves boundedness but destroys convexity because opposite points have midpoint zero.',
35:'The gradient is normal to a regular level curve. Orthogonal gradients therefore give orthogonal regular level curves, but at critical points the ordinary geometric interpretation requires care. Cauchy–Riemann implies this algebraic orthogonality, while orthogonality alone is only one condition and is insufficient to establish holomorphicity.',
40:'A subset is dense if every ambient point is a limit of its elements. An invertible real-linear transformation preserves density and identifies the rational combinations of two real-linearly independent complex numbers with a dense planar grid. Algebraic properties of the field and its Euclidean closure are different questions.',
41:'The logarithmic derivative of a positive differentiable function is f′/f. A global inequality f′≤cf is equivalent on its positive set to an upper bound on that logarithmic derivative. Local vanishing rates near a boundary can force this ratio to infinity even when the function and derivative extend continuously there.',
46:'An admissible variation h vanishes at fixed endpoints and satisfies the linearized integral constraint. The multiplier method is regular here because there are endpoint-vanishing variations with nonzero integral. The energy’s second variation is 2∫(h′)², strictly positive for every nonzero endpoint-vanishing variation, proving strict minimization.',
49:'Factorization of a joint mgf near the origin identifies independence by uniqueness of the transform. A binomial factor’s exponent is the number of trials and its exponential coefficient is the success probability. For a weighted sum of nonnegative integers, describe its small-value complementary event exactly before multiplying probabilities.',
54:'A curved exponential family can still have several necessary sufficient-statistic components. Minimal sufficiency is determined by parameter-independent likelihood ratios, not by simply counting parameters. Independent polynomial powers of the curved parameter force separate equality conditions for the corresponding data summaries.',
61:'Countability is hereditary under taking subsets. A partition of a countably infinite set into countably many nonempty parts can have all parts finite or all parts infinite. Constructing these two cases distinguishes the universal countability conclusion from unsupported size restrictions.',
62:'A sequence is unbounded above exactly when, for every real target, at least one term exceeds that target. Divergence to positive infinity is a sufficient stronger condition. Small-angle limits and growth-rate comparisons establish unboundedness; a bounded sequence can be rejected by choosing a target larger than its supremum.',
63:'A continuous injective real function on an interval is strictly monotone. Surjectivity onto the real line follows when its two end limits are opposite infinities, using the intermediate value theorem. A lower bound on separation proves injectivity first; continuity is essential for ruling out missing intermediate targets.',
64:'Uniform continuity requires one input tolerance valid throughout the domain for each output tolerance. A continuous periodic function is uniformly continuous, and a Lipschitz function satisfies this directly. Composition preserves ordinary continuity, but composition with the nonuniformly continuous squaring map need not preserve uniform continuity on an unbounded interval.',
65:'Uniform convergence means the supremum of the absolute error tends to zero. A continuous endpoint-vanishing factor can repair the nonuniform behavior of x^n near one. Splitting into an interior compact interval and an endpoint neighborhood uses geometric decay in the former and a uniformly small factor in the latter.',
66:'For power integrals, local integrability near zero requires an exponent greater than minus one, whereas tail integrability at infinity requires an exponent less than minus one. The borderline exponent produces logarithmic divergence in both settings. A change of variables puts endpoint singularities into this standard comparison form.',
67:'A removable discontinuity has a finite limiting value that can be assigned to restore continuity. A jump has distinct finite one-sided limits; oscillatory failures of a limit are nonremovable without being jumps. Bounded-variation functions have at most countably many discontinuities, and a product introduces none where both factors are continuous.',
70:'Weierstrass’s approximation theorem states that real polynomials are uniformly dense in continuous functions on a compact interval. Orthogonality to every polynomial then implies orthogonality to the function itself by approximation. A nonnegative continuous function with integral zero is identically zero; parity alone only determines part of the moment information.',
71:'Over a finite field, counting bases can be done by choosing linearly independent vectors successively. In one dimension each nonzero vector alone is a basis, giving exactly q−1 bases. The obstruction to covering by two proper subspaces is structural and works over both finite and infinite fields.',
72:'For a nilpotent linear map, Jordan blocks all have eigenvalue zero. The number of blocks equals kernel dimension and their sizes sum to the ambient dimension. The largest block size is the nilpotency index, bounded by dimension minus nullity plus one. Local eventual annihilation implies nilpotence in finite dimension by testing a finite basis.',
76:'The characteristic polynomial records total algebraic multiplicity for each eigenvalue. The minimal polynomial uses the largest Jordan-block size at that eigenvalue. Geometric multiplicity is the number of corresponding blocks. These three quantities agree only in special cases, so they must be counted separately.',
79:'The identity theorem requires zeros with a limit point inside the holomorphic domain. An uncountable planar set has such a finite limit point because it cannot be locally discrete everywhere. Countably many derivative orders partitioning an uncountable set force one derivative to have uncountably many zeros.',
82:'Locally uniform convergence means uniform convergence on every compact subset. When the limiting holomorphic function has no zeros, its modulus has a positive minimum on each compact set. Eventually the approximation error is smaller than that minimum, forcing approximants to be zero-free there; polynomial roots therefore escape all bounded regions.',
91:'For a locally Lipschitz autonomous field, solutions are unique and cannot cross equilibrium solutions. A bounded solution on a finite time interval extends as long as the field is defined in a neighborhood of its range. Strict monotonicity between equilibria determines endpoint limits while uniqueness excludes finite-time attainment.',
93:'A polynomial ansatz can be simplified by comparing its highest-degree term before expanding every coefficient. If the equation raises degree, the leading coefficient of the raised term must vanish. This identifies the possible degree, after which substitution and normalization conditions determine the remaining coefficients.',
94:'The method of characteristics replaces a first-order quasilinear PDE by ODEs along curves. A classical solution exists while the map from initial coordinates to the current spatial coordinate remains invertible. Characteristic crossing carrying different solution values precludes a single-valued differentiable continuation.',
95:'Fermat’s theorem says the gradient of a differentiable function vanishes at an interior local extremum. The extreme-value theorem supplies extrema on a compact closure. Zero boundary data force a nonzero extremum to be interior, contradicting an eikonal equation that requires a strictly positive squared-gradient expression.',
96:'For equally spaced interpolation nodes, forward differences give Newton coefficients Δ^k y_0/k!. The Newton basis uses falling factorial products, not ordinary powers. To find a specified ordinary-power coefficient, include all higher-degree Newton terms because their expansions also contain lower powers. Uniqueness assumes the standard degree-at-most-four interpolant for five distinct nodes.',
99:'Local extrema of a functional depend on the norm defining the neighborhood. The uniform norm bounds amplitudes but not derivatives; the C^1 norm controls both. High-frequency oscillations can have arbitrarily small amplitude while large derivative energy, so transferring a local-extremum claim between these norms is invalid.',
103:'Combined population variance is the weighted sum of within-group variances plus squared deviations of group means from the overall mean. The percentage coefficient of variation is one hundred times standard deviation divided by the mean, provided that mean is positive. Group means alone bound the combined range from below.',
110:'A sample proportion based on n Bernoulli trials belongs to the finite lattice {0,1/n,…,1}. Comparing tests requires comparing their decisions on this attainable set. Different real rejection thresholds may define exactly the same finite-sample rejection region when no attainable value lies between them; continuous threshold counterexamples then fail.',
111:'Parameter-dependent support must remain in the likelihood: dropping its indicator yields an incorrect maximum-likelihood calculation. The sample minimum has a shifted exponential law with rate multiplied by sample size. Completeness of this location statistic can be checked using the derivative of an exponentially weighted tail integral rather than an open-natural-parameter exponential-family claim.',
115:'An estimable linear parametric function is the expectation of some linear statistic of the observations. It must be invariant under every parameter change leaving the mean vector unchanged. In a redundant one-way model, this gives an exact coefficient condition; imposing an identifying constraint without stating it changes the question.'
}
ids={p['id'] for p in json.loads((root/'data/papers.json').read_text())}
for name in ['2023-december-q001-060.json','2023-december-q061-120.json']:
 path=root/'data/completed_papers'/name;data=json.loads(path.read_text())
 def clean(s):
  for a,b in [('probabilityzero','probability zero'),('requiredzero','required zero'),('coefficient16','coefficient 16'),('forcesa','forces a'),('forcesb','forces b'),('ata=','at a='),('at1','at 1'),('at0','at 0'),('for25','for 25'),('for4','for 4'),('for3','for 3'),('for2','for 2'),('for1','for 1'),('sizeα','size α'),('iffc₀','iff c₀'),('fora','for a'),('witha','with a'),('witht','with t'),('atv=','at v='),('soA','so A'),('soB','so B'),('soC','so C'),('soD','so D'),('provingA','proving A'),('provingB','proving B'),('provingC','proving C'),('provingD','proving D'),('excludingA','excluding A'),('excludingB','excluding B'),('excludingC','excluding C'),('excludingD','excluding D'),('Afails','A fails'),('Bfails','B fails'),('Cfails','C fails'),('Dfails','D fails'),('iszero','is zero'),('isfalse','is false'),('isfinite','is finite'),('ispositive','is positive'),('and0','and 0'),('and1','and 1'),('and2','and 2'),('degree2','degree 2'),('degree3','degree 3'),('degree6','degree 6'),('order3','order 3'),('order6','order 6'),('rank3','rank 3'),('rank2','rank 2')]:
   s=s.replace(a,b)
  s=re.sub(r'\b(if|since|because|hence|so|then|when|where|at|for|with|and|or)(?=[A-Zαβθμσρλφγπχℝℂℚ])',r'\1 ',s)
  return s
 def walk(x):
  if isinstance(x,str):return clean(x)
  if isinstance(x,list):return [walk(y) for y in x]
  if isinstance(x,dict):return {k:walk(v) for k,v in x.items()}
  return x
 for q in data['questions']:
  if q['question_number'] in extra:q['theory']+=' '+extra[q['question_number']]
 data=walk(data)
 parsed=parse_bank(data,ids);path.write_text(export_bank(parsed))
print('validated',sum(len(json.loads((root/'data/completed_papers'/p).read_text())['questions']) for p in ['2023-december-q001-060.json','2023-december-q061-120.json']))
print('Euler value',1+.05*math.sqrt(6)+.05*math.sqrt(3*1.05+2*(1+.05*math.sqrt(6))+1))
