from pack_writer import Writer
w=Writer('2024-december-02mar','-q001-060')
def add(n,p,o,c,h,s,t,e,d='Easy',topic='Aptitude',track='Shared',status='reviewed',note=''):
 w.add(n,track,topic,d,p,o,c,h,s,t,e,status,note)
add(1,'A monkey covers exactly 10 m on ground in each jump. What is the least number of jumps required to reach a distance 1 m away from where the monkey jumps first?',['1','2','3','9'],'B',['Jumps may have different directions; distance from the start is displacement, not total path length.','Can two segments of length 10 form a triangle whose third side is 1?'],
'One jump leaves the monkey exactly 10 m from the start, so A is impossible. Two jumps can form two sides of an isosceles triangle with side lengths 10, 10, 1: the strict triangle inequalities hold. Equivalently, choose the angle θ between the jump vectors so 1²=10²+10²+200cosθ, giving cosθ=−199/200. Thus two jumps suffice and are minimal: B. Three and nine jumps are unnecessary, excluding C and D.',
'Distance travelled is the sum of the lengths of successive motions, whereas displacement is the vector from the starting point to the final point. For two jumps of lengths a and b, their possible resultant lengths fill the interval [|a−b|,a+b], because the cosine rule gives r²=a²+b²+2ab cosθ and cosθ varies continuously from −1 to 1. A nondegenerate triangle exists when the inequalities are strict. Thus long steps can produce a short displacement by nearly cancelling. Do not assume every jump follows a straight line in the same direction; the question imposes only jump length, not direction.',
[('Two jumps have lengths 7 m each. Can the final displacement be 3 m?','Yes: 0≤3≤14. Set cosθ=(9−98)/98=−89/98; this is an admissible angle.'),('A walker takes steps of lengths 8 m and 3 m. What are the least and greatest possible displacements?','The triangle inequality and reverse triangle inequality give 5≤r≤11 m. Opposite directions give 5, and equal directions give 11.')])
add(2,'The cube root of 0.0125% is closest to',['0.005%','0.05%','0.5%','5%'],'D',['First convert the percentage to a number.','0.0125%=0.000125, which is the cube of 0.05.'],
'0.0125%=0.0125/100=0.000125=(0.05)³. Therefore its cube root is 0.05=5%, exactly D. A, B and C represent 0.00005, 0.0005 and 0.005 respectively; none equals 0.05. Taking the cube root of the numeral 0.0125 without converting percent would apply the operation to the wrong number.',
'A percentage p% denotes the dimensionless quantity p/100. Arithmetic operations must be performed on that quantity before converting the answer back to percent. In particular, (p%)^(1/3)=(p/100)^(1/3), and its percentage representation is 100(p/100)^(1/3)%. This is different from taking the cube root of p and appending a percent sign. Positive real numbers have one positive real cube root, and cubing the proposed result provides a direct verification. Decimal place counting is useful: 0.05³=0.000125. Keeping units and representation separate prevents errors in percentage powers, roots and compound growth calculations.',
[('Find the square root of 4%, expressed as a percentage.','4%=0.04; its square root is 0.2=20%.'),('Find the cube root of 0.8%, expressed as a percentage.','0.8%=0.008=0.2³, so the answer is 20%.')])
add(3,'How many 5-digit numbers, using 0 to 9, can be generated such that “123” appears as a string and no digit appears more than once?',['228','108','156','114'],'D',['Treat 123 as one fixed block and identify its possible starting positions.','The other digits come from {0,4,5,6,7,8,9}; a leading zero is forbidden.'],
'The block can start at positions 1, 2 or 3. If it starts at 1, the two remaining ordered digits have 7·6=42 choices. If it starts at 2, the first digit has 6 nonzero choices and the last digit has 6 remaining choices: 36. If it starts at 3, the first digit again has 6 choices and the second has 6: 36. These cases are disjoint because no digit repeats. Total=42+36+36=114, D. Therefore 228, 108 and 156 are excluded.',
'A fixed consecutive string can be treated as an indivisible block, but its internal order is fixed. For a length-m string inside a length-n number, there are n−m+1 starting positions. If digits cannot repeat, filling the remaining positions uses permutations without replacement, not independent powers of ten. A number cannot begin with zero, so placements in which a free digit occupies the first position need a separate count or a leading-zero subtraction. Here uniqueness of the digits ensures the block cannot occur twice, so the position cases do not overlap. Always verify that a block argument preserves consecutiveness and distinguishes numbers from strings.',
[('Count four-digit numbers containing the string 123 with no repeated digits.','The block starts at 1 or 2. At 1 the final digit has 7 choices; at 2 the first digit has 6 nonzero choices. Total 13.'),('Count five-character digit strings containing 123 without repetition, allowing a leading zero.','The block has 3 positions and the other ordered digits have 7·6 choices. Total 126.')],d='Moderate')
add(4,'Two orientations of a die labelled 1 to 6 show (top, front, right)=(3,4,5) and (4,2,5). The number on the face opposite 3',['is 2','is 1','is 6','cannot be determined from the given data'],'A',['Keep the common face 5 fixed and compare the other visible faces.','Rotation around the axis through face 5 moves front 4 to the top; determine which face then moves to the front.'],
'Both views have right face 5. Keeping it fixed, the first front face 4 becomes the second top face 4. This is a quarter-turn about the right-left axis. The original bottom face must then become the second front face, labelled 2. Hence bottom 2 is opposite original top 3. A is correct; 1 and 6 are excluded, and the orientation information does determine the answer, excluding D.',
'A cube has three pairs of opposite faces. At every vertex, three faces meet and their labels are pairwise adjacent. A view of top, front and right faces gives their order as well as adjacency. Comparing views with a shared fixed face reduces the problem to a rotation about the axis through that face and its opposite. A quarter-turn cycles the four surrounding faces; consecutive positions in this cycle are adjacent and positions two steps apart are opposite. It is unsafe to infer that ordinary die labels sum to seven unless that convention is explicitly given. Here the labelled orientations themselves determine the opposition.',
[('A cube shows (top,front,right)=(A,B,C), then (B,D,C). Which face is opposite A?','Keep C fixed. The rotation carrying front B to top B carries bottom D to front D. Thus A and D are opposite.'),('If face A touches B,C,D and E on a cube labelled A through F, what is opposite A?','A face has exactly four adjacent faces and one opposite face. The only remaining label F is opposite A.')])
add(5,'Four containers of equal height have bases that are a circle, a square, a rectangle and an equilateral triangle, all of the same area. Which statement is true?',['Their volumes are equal.','The rectangular container has greater volume than the square container.','The triangular container has smaller volume than the square container.','The square container has greater volume than the circular container.'],'A',['For a cylinder or prism, volume equals base area times height.','Both quantities in that product are equal for all four containers.'],
'For the pictured type of straight-sided containers, V=Ah. All four bases have the same area A and all heights equal h, so all volumes equal Ah. A is true. B, C and D each claim an inequality between two equal volumes and are false. The perimeter or shape of the base does not enter this volume formula.',
'A prism has identical parallel cross sections, and a cylinder is its circular counterpart. Their volume is base area multiplied by perpendicular height. This follows by integrating the constant cross-sectional area: V=∫₀ʰA dz=Ah. The principle holds for any base shape as long as the cross sections remain congruent throughout the height; it does not hold for a cone or pyramid with tapering sections, whose volume is Ah/3. Equal areas do not imply equal perimeters, but perimeters affect lateral surface area rather than volume. Check which geometric quantity is requested before comparing circle, square, rectangle or triangle bases.',
[('A cylindrical and a square prism container each have base area 12 cm² and height 7 cm. Compare volumes.','Both have V=12·7=84 cm³.'),('A prism and a pyramid have equal base area 18 cm² and height 5 cm. Find volumes.','The prism volume is 90 cm³ and pyramid volume is 30 cm³; constant cross sections are essential.')])
add(6,'The graphs show price per carat (in lakh rupees) versus weight w (carats): diamond rate=2w and emerald rate=w. A person buys a diamond and emerald of identical weight for ₹6,75,000. What is that weight?',['1 carat','1.5 carat','2 carat','2.5 carat'],'B',['The graph shows a rate per carat, not the total stone price.','Multiply each rate by its weight; the combined price is 3w² lakh rupees.'],
'The diamond line joins (0,0) to (2.5,5), so its rate is 2w lakh/car​at; emerald joins (0,0) to (2.5,2.5), so its rate is w lakh/car​at. Total price=(2w)w+(w)w=3w² lakh. Thus 3w²=6.75, giving w²=2.25 and positive w=1.5, B. The costs for A,C,D are 3,12,18.75 lakh, respectively, so none matches.',
'A graph may display a unit rate rather than a total amount. If a commodity of quantity w has rate r(w) per unit, purchasing one indivisible item of that quantity costs w·r(w). A line through the origin has slope equal to rate divided by quantity, so r(w)=aw and the total price is aw². When two stones have equal weight, their total costs add; the weights themselves are not added before applying the separate rates. Units expose the distinction: lakh rupees per carat times carats gives lakh rupees. Do not integrate a rate describing the price of an entire stone as if it were a marginal price.',
[('Two same-weight stones have rates 3w and 2w lakh/car​at. Total price is 20 lakh. Find w.','Price=5w²=20, so w=2 carats.'),('A stone weighs 2 carats and its price per carat is 1.5 lakh. What is its total price?','The price is 2·1.5=3 lakh rupees; the rate is not the total price.')],d='Moderate')
add(7,'If A is B’s daughter, B is C’s brother and D is C’s father, then what is A to D?',['Grandfather','Grandmother','Grandson','Granddaughter'],'D',['B and C belong to the same generation.','D is B’s father in the standard family interpretation; A is B’s female child.'],
'B is C’s brother, so D, C’s father, is also B’s father under the ordinary sibling convention. A is B’s daughter, placing A two generations below D. Since A is female, A is D’s granddaughter, D. Grandfather and grandmother reverse the generational direction, while grandson has the wrong gender.',
'Family relation puzzles combine generation and gender. A parent-child link changes the generation by one; siblings share a generation. Grandchildren are children of children and lie two generations below the reference person. Daughter and sister imply female, whereas son and brother imply male. A small family tree or a chain of directed parent arrows avoids reversing the relation: asking what A is to D differs from asking what D is to A. These puzzles ordinarily use siblings with the stated common parent unless a half-sibling or step-family distinction is explicitly introduced. Only infer gender from words that actually supply it.',
[('P is Q’s son, Q is R’s sister, and S is R’s mother. What is P to S?','S is Q’s mother; P is Q’s male child. Therefore P is S’s grandson.'),('M is N’s father and N is O’s mother. What is M to O?','M is a male parent two generations above O, so M is O’s grandfather.')])
add(8,'A 4 m × 3 m × 2 m marble block is cut, without wastage, into square tiles of side 1 m and thickness 10 cm. How many tiles result?',['120','240','360','480'],'B',['Express the thickness in metres before computing volumes.','The block volume is 24 m³; each tile volume is 0.1 m³.'],
'Thickness 10 cm=0.1 m. A tile has volume 1·1·0.1=0.1 m³, and the block has volume 4·3·2=24 m³. With no wastage, the number is 24/0.1=240, B. This can be realized as 4·3 tiles in each of 20 layers. Options 120,360,480 would require total volumes 12,36,48 m³, so A,C,D are excluded.',
'When a solid is partitioned without waste, total volume is conserved. For rectangular blocks, V=length·width·height, and for rectangular tiles the same formula applies using thickness as the third dimension. All factors must first be expressed in compatible units: 10 cm=0.1 m, and a cubic metre contains one million cubic centimetres. Dividing large volume by small volume yields a count only if the pieces can actually fit the dimensions; here each dimension is an integer multiple of the corresponding tile dimension, so a grid realizes the ratio exactly. Surface area alone cannot determine the number of tiles from a three-dimensional block.',
[('A 2 m × 2 m × 1 m block is cut into 0.5 m × 0.5 m × 0.1 m tiles. How many?','Large volume=4 m³ and tile volume=0.025 m³; 4/0.025=160 tiles, realized by 4·4·10.'),('How many 20 cm cubes can be cut from a 1 m cube?','Each side contains 100/20=5 cubes, so 5³=125 cubes.')])
add(9,'A lady walks one-tenth of the total distance at 3 km/h, runs one-sixth at 5 km/h and one-fifth at 6 km/h, and cycles the remaining 16 km at 16 km/h. What is the total distance?',['14 km','16 km','24 km','30 km'],'D',['The speed information is unnecessary for the distance partition.','The first three fractions add to 7/15, leaving 8/15.'],
'Let total distance be D km. The first three portions total (1/10+1/6+1/5)D=(3+5+6)D/30=7D/15. Thus remaining distance is 8D/15=16, giving D=30 km, D. Options 14,16,24 produce remaining distances 112/15,128/15,12.8 km rather than 16. The speeds would matter for travel time, but not for this total-distance equation.',
'Partition problems describe parts of one common whole. If fractions f₁,...,fᵣ of the total are assigned, the remaining fraction is 1−Σfᵢ, provided the parts are disjoint and refer to the same total. A known remaining quantity R then gives total R/(1−Σfᵢ). Find a common denominator before adding fractions. A speed is a distance per unit time; it enters time calculations through time=distance/speed, but it need not appear in an equation that only divides the total distance into specified fractions. Distinguish a fraction of the original whole from a fraction of the amount remaining after earlier stages.',
[('A traveller covers 1/4 and 1/3 of a route, leaving 10 km. Find its length.','The remaining fraction is 1−1/4−1/3=5/12; total=10·12/5=24 km.'),('Half of a route is covered at 4 km/h and half at 8 km/h. Find average speed.','For total D, time=D/8+D/16=3D/16; average speed=D/time=16/3 km/h, not 6.')])
add(10,'An OTP has six digits using 0 to 9. Three digits and their positions are known. What is the probability, in percentage, of discovering the full PIN within 100 trials?',['10%','20%','30%','40%'],'A',['Only the three unknown positions create uncertainty.','There are 10³ equally likely completions; use distinct guesses.'],
'There are 10³=1000 possible fillings of the three unknown positions. Testing 100 distinct completions succeeds for 100 of these equally likely PINs, so probability=100/1000=0.1=10%, A. B,C,D would require 200,300,400 distinct guesses. If guesses were independently sampled with replacement, the probability would instead be 1−(999/1000)^100≈9.52%, still closest to A; the natural search uses no repeated guesses.',
'The multiplication principle counts ordered strings by multiplying the number of choices at each position. An OTP may begin with zero and may repeat digits unless restrictions are stated, so three unknown decimal positions yield 10³ possibilities. Under a uniform secret and k distinct guesses among N possibilities, success probability is k/N for k≤N. Repeated guesses waste trials: independent sampling with replacement gives 1−(1−1/N)^k instead. Known positions must be removed from the uncertainty count; knowing only which digits occur without knowing positions would be a different problem. The search model and uniformity assumption explain why a count becomes a probability.',
[('A four-digit PIN has two unknown positions. Find success probability for 15 distinct guesses.','There are 10²=100 completions. Probability=15/100=15%.'),('There are 100 possible passwords. Two independent guesses allow repetitions. Find success probability.','Failure on both is (99/100)², so success=1−0.9801=0.0199=1.99%.')])
add(11,'Ramesh is taller than Rajesh but not taller than Rupesh. Suresh’s height is the average of Naresh’s and Rajesh’s heights. Rajesh is taller than Naresh. Who is shortest?',['Suresh','Naresh','Rupesh','Cannot be determined'],'B',['The average of two distinct heights lies strictly between them.','Arrange the inequalities beginning with Naresh < Rajesh < Ramesh ≤ Rupesh.'],
'Let heights be N,J,M,P,S for Naresh,Rajesh,Ramesh,Rupesh,Suresh. Given N<J<M≤P, and S=(N+J)/2, we have N<S<J<M≤P. Thus Naresh is uniquely shortest: B. Suresh lies above Naresh, Rupesh lies above Rajesh, and the complete comparison excludes D.',
'Ordering puzzles translate words into inequalities. “Taller than” is strict, while “not taller than” allows equality and becomes ≤. For real a<b, their arithmetic mean satisfies a<(a+b)/2<b; this follows by subtracting a and b respectively. Inserting an average into an existing chain can establish a full ordering without numerical values. Equality at the top of a chain does not affect a strict minimum at the bottom. Pay attention to the direction of each comparison and the names involved; replacing a non-strict inequality with a strict one can unnecessarily assume more than the question gives.',
[('A<B and C=(A+B)/2. Order A,B,C.','C−A=(B−A)/2>0 and B−C=(B−A)/2>0, so A<C<B.'),('Heights satisfy P>Q≥R>S. Who is shortest, and must Q exceed R?','S is shortest. Q need not exceed R because equality Q=R is allowed.')])
add(12,'Find the value of (1−1/2025)(1−1/2024)(1−1/2023)⋯(1−1/2001).',['1−1/79','1−1/80','1−1/81','1−1/82'],'C',['Write each factor as (n−1)/n.','Consecutive numerator and denominator terms cancel.'],
'The product is (2024/2025)(2023/2024)⋯(2000/2001)=2000/2025=80/81=1−1/81, C. The other options equal 78/79,79/80 and81/82, which differ from80/81. There are25 factors; their reciprocals cannot simply be added because multiplication introduces cross terms.',
'A telescoping product is one in which most factors cancel after rewriting. For integers b≥a≥2, ∏ₙ₌ₐᵇ(1−1/n)=∏ₙ₌ₐᵇ(n−1)/n=(a−1)/b. The cancellation is valid because every denominator is nonzero, and the adjacent numerator values match earlier denominator values. Factor order does not matter for scalar multiplication, so a decreasing presentation has the same result as an increasing one. Preserve both endpoints: the surviving numerator is a−1, not a, and the surviving denominator is b, not b+1. Products of factors near one must not be replaced by one minus the sum without explicitly invoking an approximation.',
[('Evaluate ∏ₙ₌₂¹⁰(1−1/n).','It equals (1/2)(2/3)⋯(9/10)=1/10.'),('Evaluate (1−1/11)(1−1/12)⋯(1−1/20).','Telescoping leaves10/20=1/2.')])
add(13,'A rhombus has side 13 cm and one diagonal 24 cm. Its area is',['90 cm²','100 cm²','110 cm²','120 cm²'],'D',['The diagonals of a rhombus bisect one another at right angles.','A half diagonal is12; use a right triangle with hypotenuse13.'],
'If the other diagonal is d, a quarter of the rhombus is a right triangle with legs12 and d/2 and hypotenuse13. Thus (d/2)²=169−144=25, so d=10. Area=24·10/2=120 cm², D. The values90,100,110 fail the diagonal area formula.',
'A rhombus is a parallelogram with all sides equal. Its diagonals bisect each other, and equal side lengths imply that these diagonals are perpendicular. Joining their intersection to two adjacent vertices produces a right triangle whose hypotenuse is a rhombus side and whose legs are half the diagonals. Therefore s²=(d₁/2)²+(d₂/2)², and area=d₁d₂/2, obtained by summing the four right-triangle areas. Unlike a square, a general rhombus need not have equal diagonals. Using the full given diagonal as a leg would violate the bisection property and lead to an impossible triangle.',
[('Find the area of a rhombus with side5 and one diagonal6.','Half diagonal3, so the other half is√(25−9)=4. Other diagonal8; area=6·8/2=24.'),('A rhombus has diagonals10 and24. Find its side and area.','The side is√(5²+12²)=13, and area=10·24/2=120.')])
add(14,'Two fair dice are thrown independently. What is the probability that the average of their upper-face values is4?',['5/36','1/6','7/36','2/9'],'A',['Average4 means the sum is8.','List ordered pairs with each coordinate between1 and6.'],
'The36 ordered pairs are equally likely. Sum8 occurs at(2,6),(3,5),(4,4),(5,3),(6,2): five outcomes. Probability=5/36, A. The other proposed values correspond to6,7 and8 favourable outcomes among36, respectively, so B,C,D are false.',
'For independent fair dice, the joint sample space is the Cartesian product {1,...,6}². Each ordered pair has probability1/36, and order matters even if the event is symmetric: (2,6) and(6,2) are distinct elementary outcomes. An average constraint (X+Y)/2=a is equivalent to the sum constraint X+Y=2a. Counts of dice sums rise from1 at sum2 to6 at sum7 and then decrease to1 at sum12. The equal likelihood applies to ordered pairs, not to the eleven possible sums. Listing feasible pairs or intersecting the constraints1≤X≤6 and1≤s−X≤6 gives a reliable count.',
[('Find probability that two fair dice have average3.','Sum6 gives(1,5),(2,4),(3,3),(4,2),(5,1), so probability5/36.'),('Find probability that two fair dice sum to7.','Pairs(1,6) through(6,1) give six outcomes, so6/36=1/6.')])
add(15,'The square of the geometric mean of two positive integers is30. What is the smallest possible sum of the integers?',['10','11','13','17'],'B',['The square of the geometric mean is the product.','List integer factor pairs of30 and choose the pair closest together.'],
'If integers are a,b>0, geometric mean√(ab) has square ab=30. Factor pairs(1,30),(2,15),(3,10),(5,6) have sums31,17,13,11. The minimum is11, B. A=10 is impossible, also by a+b≥2√30>10; C and D are feasible sums but not the minimum.',
'The geometric mean of two positive numbers is√(ab). Fixing it fixes their product. The arithmetic-geometric mean inequality says a+b≥2√(ab), with equality exactly when a=b. For integer variables, equality may be impossible, and one must examine divisor pairs. Among pairs a≤b with ab=P, the sum a+P/a decreases as a approaches√P from below, so the closest factor pair minimizes it. Positivity is essential for the usual AM-GM inequality. A real-valued minimum2√P is a lower bound, not necessarily an admissible integer answer; the integrality condition must still be checked.',
[('Positive integers have product24. Find their least sum.','Pairs(1,24),(2,12),(3,8),(4,6) give sums25,14,11,10; minimum10.'),('Positive real numbers have product30. Find their least sum.','AM-GM gives2√30, achieved by both numbers√30. The integer restriction would increase it to11.')])
add(16,'A heater uses approximately1 kWh to raise1 L of water by1°C. Its power rating is10 kW. What time does that temperature increase take?',['1 hour','15 minutes','10 minutes','6 minutes'],'D',['Use the supplied energy requirement and power; energy=power×time.','1 kWh divided by10 kW gives0.1 hour.'],
'Using the stated energy requirement, t=E/P=(1 kWh)/(10 kW)=0.1 h=6 minutes, D. At10 kW, the other times would deliver10,2.5 and5/3 kWh, not1 kWh, excluding A,B,C. The numerical energy premise is physically approximate as supplied; the calculation is a dimensional energy-power conversion.',
'Power is energy transferred per unit time. For constant power P, energy E=Pt; hence t=E/P. A kilowatt is a power unit, while a kilowatt-hour is an energy unit equal to the energy delivered by one kilowatt over one hour. Dividing kWh by kW yields hours, not minutes; conversion requires multiplication by60. If efficiency η is specified, useful heat equalsηPt, but no additional efficiency factor should be invented when the energy consumption is directly given. In a quantitative word problem, use the supplied model consistently and separate unit conversion from any external physical estimate.',
[('A2 kW heater must supply0.5 kWh. How long?','t=0.5/2=0.25 h=15 minutes.'),('A3 kW appliance runs20 minutes. How much energy does it use?','20 minutes=1/3 h, soE=3·1/3=1 kWh.')])
add(17,'The plotted X-Y data oscillate about zero, start nearY=1 atX=0 and have decreasing amplitude with roughly constant spacing between peaks. Which function best fits, for some k>0?',['Y=cos(kX)','Y=sin(kX²)','Y=tan(kX³)','Y=e^(−X/k)cos(kX)'],'D',['Look separately at oscillation frequency and amplitude.','The envelope shrinks while the peak spacing stays approximately constant.'],
'D is a cosine with exponential damping: Y(0)=1, peak spacing is approximately2π/k, and |Y|≤e^(−X/k) decreases withX. This matches the graph. A has constant amplitude1. B has constant amplitude and increasing local frequency, andY(0)=0. C has poles and increasing phase speed rather than smooth bounded decaying oscillations. Hence D is the appropriate qualitative model.',
'An oscillatory model combines a phase, controlling zeros and periods, with an amplitude envelope. cos(kX) has constant amplitude and period2π/k. Multiplying by e^(−X/k), withk>0, leaves the sinusoidal phase while producing a decreasing positive envelope. A quadratic phase kX² has derivative2kX, so its oscillations become more closely spaced asX grows; this is a chirp rather than constant-period motion. Tangent has vertical asymptotes where its cosine denominator vanishes. Qualitative graph matching should check initial value, boundedness, changing amplitude and spacing, rather than choosing a formula merely because it oscillates.',
[('A graph starts at1 and has constant amplitude and period4. Give a cosine model.','Y=cos(πX/2), since2π/k=4 givesk=π/2.'),('ForY=e^(−2X)cos(3X), find the envelope and oscillation period.','Envelope is±e^(−2X); the cosine period is2π/3, while its amplitude decays.')],d='Moderate')
add(18,'Ten litres of a milk mixture contains10% water. How much water must be added to make the water proportion20%?',['1 L','1.25 L','2 L','2.25 L'],'B',['The original water volume is1 L.','Addingx litres changes both the water amount and total mixture volume.'],
'Initially water=1 L and total=10 L. After addingx L, water fraction=(1+x)/(10+x). Set it to0.2:1+x=2+0.2x, so0.8x=1 andx=1.25 L, B. For A,C,D the resulting fractions are2/11,3/12,3.25/12.25, none20%.',
'Concentration is component amount divided by total mixture amount. Adding a pure component changes both numerator and denominator, whereas adding another component changes only the denominator. For initial volumeV and component fractionp, addingx units of pure component gives(pV+x)/(V+x); setting this toq yieldsx=V(q−p)/(1−q), forp<q<1. The calculation assumes additive volumes, the ordinary mixture model used in such problems. Percentages must be interpreted as fractions. An increase of ten percentage points does not mean adding ten percent of the initial volume, because the final total differs from the original total.',
[('A20 L mixture contains25% water. Add water to reach40%. Find the amount.','(5+x)/(20+x)=0.4, so0.6x=3 andx=5 L.'),('A10 L mixture contains20% water. How much pure milk makes water10%?','Water stays2 L. Solve2/(10+x)=0.1, givingx=10 L.')])
add(19,'If Asha’s mother is Tanisha’s daughter’s aunt and Tanisha has no nephew, then Asha is Tanisha’s',['mother','niece','grandmother','sister'],'B',['An aunt of Tanisha’s daughter belongs to the parent generation.','Asha is a daughter of that aunt, so lies in the daughter’s generation.'],
'Under the standard family-puzzle convention, the aunt is Tanisha’s sister or the wife of Tanisha’s brother. Her daughter Asha is consequently Tanisha’s niece. The no-nephew condition is consistent with the child being female. Thus B. A and C place Asha above Tanisha, and D puts her in the same generation; neither matches the parent-child links.',
'An aunt is a parent’s sister or, in the usual puzzle convention, the wife of a parent’s brother. The child of one’s sibling is a niece if female and a nephew if male. Track the reference person carefully: the aunt belongs to Tanisha’s generation, but Asha, as her daughter, belongs one generation below. The extra statement that Tanisha has no nephew restricts male children in the relevant sibling families, not the existence of nieces. Such questions presume ordinary direct family relations rather than unspecified step-family or remote marriage constructions. Generation and gender together distinguish niece from sister, mother and grandmother.',
[('Rina is the daughter of Mina’s brother. What is Rina to Mina?','Rina is the female child of Mina’s sibling, so she is Mina’s niece.'),('Arun’s mother is Bela’s sister. What is Arun to Bela?','Arun is a male child of Bela’s sister, so Arun is Bela’s nephew.')])
add(20,'A5 cm ×4 cm chocolate bar is cut into1 cm ×1 cm pieces, taken one by one. One can start by cutting along length or width before removing pieces one by one. What minimum number of cuts is required?',['20','19','18','10'],'B',['There are20 unit pieces. A cut of one existing piece creates one extra piece.','Starting from one piece, reaching20 pieces needs at least19 such cuts.'],
'There are5·4=20 unit squares. With individual pieces cut without stacking, each cut increases the total number of pieces by one. Starting from1 piece, at least19 cuts are required. Achieve this by making4 cuts to obtain five1×4 strips, then3 cuts per strip, giving4+5·3=19. Equally,3+4·4=19 by the other orientation. Thus B; A uses one extra cut, while C,D cannot create20 pieces under the stated procedure.',
'For repeated binary subdivision of one piece at a time, each cut replaces one existing piece by two and therefore increases the piece count by exactly one. Starting with one piece, N final pieces require N−1 cuts, regardless of the order of subdivision. A rectangularm×n grid can realize this bound bym−1 strip cuts followed bym(n−1) cuts within the strips, totalingmn−1. The conclusion depends on the individual-piece rule: cutting stacked strips or making one stroke through several separated pieces could create more than one new piece per stroke. Always distinguish the number of grid lines from the number of individual cuts.',
[('Cut a3×3 bar into unit squares, one existing piece per cut. Minimum cuts?','Nine pieces require8 cuts. Make2 strip cuts and then2 cuts in each of3 strips:2+6=8.'),('Starting with4 pieces, how many binary cuts produce15 pieces?','Every cut adds one piece, so15−4=11 cuts, assuming all desired shapes can be realized.')])
print('Saved',len(w.packs),'questions')
def math(n,p,o,c,h,s,t,e,d='Moderate',topic='Real Analysis',status='reviewed',note=''):
 add(n,p,o,c,h,s,t,e,d,topic,'Mathematics',status,note)
math(22,'A real sequence(x_n) has a decreasing subsequence(x_{n_k}) with limit2025. Which statement is necessarily true?',['liminf x_n ≥2025','limsup x_n ≤2025','liminf x_n ≤2025','liminf x_{n_k} >2025'],'C',['Every subsequential limit lies between the liminf and limsup of the full sequence.','A convergent subsequence has liminf equal to its limit, regardless of approaching from above.'],
'For everyN, sufficiently late subsequence terms lie in the tail {x_n:n≥N}. Hence inf_{n≥N}x_n≤2025 after taking the subsequence limit. TakingN→∞ givesliminf x_n≤2025: C. A fails ifx_{2k}=2025+1/k andx_{2k−1}=0. B fails if the odd terms are3000 instead. D is false because the subsequence converges, so its liminf is exactly2025, although its individual terms can all exceed2025.',
'The lower limit of a real sequence isliminf x_n=lim_N inf_{n≥N}x_n, with extended real values permitted; the upper limit is defined analogously by tail suprema. Every finite subsequential limitL satisfiesliminf x_n≤L≤limsup x_n. The proof uses the fact that each sufficiently late subsequence term lies in each fixed tail. A monotone convergent sequence approaches its limit from one side, but its lower and upper limits still equal that limit. Information about one subsequence does not constrain all omitted terms. In necessary-statement questions, interleaving the specified subsequence with a second sequence is an effective way to build counterexamples.',
[('x_{2k}=1+1/k andx_{2k−1}=−2. Findliminf andlimsup.','The odd terms are−2 and even terms approach1, so the limits are−2 and1.'),('A sequence has a subsequence tending5. Can itslimsup be3?','No: every subsequential limit is at mostlimsup, so5≤limsup contradicts3.')])
math(23,'Let a_n=−2√n+Σ_{k=1}^n1/√k and b_n=−2√(n+1)+Σ_{k=1}^n1/√k. Which statement is true?',['a_n converges butb_n does not','b_n converges buta_n does not','Both converge','Neither converges'],'C',['Compare1/√k with integrals ofx^(−1/2).','Showa_n is decreasing and bounded below; then usea_n−b_n→0.'],
'a_{n+1}−a_n=1/√(n+1)−2/(√(n+1)+√n)<0. Sincex^(−1/2) decreases, Σ_{k=1}^n1/√k≥∫₁ⁿ⁺¹x^(−1/2)dx=2√(n+1)−2. Thus a_n≥2(√(n+1)−√n)−2>−2. The monotone convergence theorem gives convergence ofa_n. Furthermorea_n−b_n=2(√(n+1)−√n)=2/(√(n+1)+√n)→0, sob_n converges to the same limit. C is correct, excludingA,B,D.',
'The monotone convergence theorem says that a real monotone sequence bounded on the relevant side converges to a finite limit. Comparing a decreasing positive function with rectangles gives∫₁ⁿ⁺¹f(x)dx≤Σ_{k=1}^nf(k)≤f(1)+∫₁ⁿf(x)dx. These estimates can show that subtracting the leading integral growth leaves a bounded sequence. Rationalization, √(n+1)−√n=1/(√(n+1)+√n), makes increments and asymptotic differences transparent. Ifa_n converges andb_n−a_n→0, thenb_n converges to the same limit. Merely knowing both constituent terms diverge does not settle the convergence of their difference; cancellation can leave a finite remainder.',
[('ShowH_n−log n converges, whereH_n=Σₖ₌₁ⁿ1/k.','Its increment1/(n+1)−log(1+1/n)<0 because the logarithm equals∫ₙⁿ⁺¹dx/x>1/(n+1). AlsoH_n≥log(n+1), so the difference is positive and bounded below.'),('Ifa_n→L andb_n=a_n+1/√n, findlimb_n.','The added term tends0, so the sum rule givesb_n→L.')],d='Hard')
math(24,'Letf:ℝ→ℝ be nonconstant and continuous. Which statement is necessarily true?',['For every boundedA⊆ℝ,f⁻¹(A) is bounded','Every Cauchy sequence(x_n) inℝ has Cauchy image sequence(f(x_n))','There existsx withf(x)=x','There existsx withf(x)=0'],'B',['A Cauchy sequence inℝ converges to a real number.','Apply continuity at its limit; test the other statements with simple continuous functions.'],
'If(x_n) is Cauchy, completeness ofℝ givesx_n→x∈ℝ. Continuity yieldsf(x_n)→f(x), hence the image sequence is Cauchy. B is necessary. A fails forf(x)=sinx and boundedA={0}, whose preimage contains everykπ. C fails forf(x)=x+1, which has no fixed point. D fails forf(x)=e^x, which is everywhere positive. All counterexamples are nonconstant and continuous.',
'Completeness ofℝ means every Cauchy sequence converges to a point ofℝ. A continuous function preserves convergent sequences and their limits, so on a complete domain it also sends Cauchy sequences to Cauchy sequences. This conclusion does not require global uniform continuity: a Cauchy sequence eventually remains close to its single limit. Continuity guarantees preimages of closed sets are closed, not bounded, and the intermediate value theorem gives a zero only when suitable opposite signs are available. A fixed point requires information aboutf(x)−x. Counterexamples must satisfy every premise, particularly nonconstancy and continuity on the entire real line.',
[('Doesf(x)=x² send every real Cauchy sequence to a Cauchy sequence?','Yes. Ifx_n→x by completeness, thenx_n²→x² by continuity, hence the images are Cauchy.'),('On(0,1), does continuousf(x)=1/x preserve all Cauchy sequences?','No. x_n=1/(n+1) is Cauchy in the domain but has no limit there; f(x_n)=n+1 is not Cauchy.')])
math(25,'Letf:ℝ→[0,∞) be bijective. Which statement is true?',['f is monotone','f is continuous but not strictly monotone','f is not continuous','f is continuous but not uniformly continuous'],'C',['A continuous injective function on an interval is strictly monotone.','Since0 must be attained at an interior point ofℝ, strict monotonicity would force a negative value on one side.'],
'Assumef is continuous. Injectivity on the intervalℝ makesf strictly monotone. Surjectivity givesf(a)=0 for somea. If increasing, anyx<a hasf(x)<0; if decreasing, anyx>a hasf(x)<0. Both contradict the codomain[0,∞). Thusf cannot be continuous, C, excludingB andD. In fact even an arbitrary monotone bijection is impossible: injectivity makes a monotone map strict, and the same minimum argument excludesA.',
'A continuous one-to-one real function on an interval is strictly monotone. Otherwise there are three ordered points forming a rise followed by a fall, or a fall followed by a rise; the intermediate value theorem then gives two points with the same value. A strictly monotone map onℝ cannot attain a least value because every point has points on both sides. Consequently a bijection fromℝ onto a half-closed interval with a minimum cannot be continuous. Set-theoretic bijections nevertheless exist; cardinality alone does not preserve topology. The issue is the attained endpoint0, not the fact that the range is unbounded.',
[('Is there a continuous bijectionℝ→(0,∞)?','Yes:f(x)=e^x is continuous, strictly increasing and onto the positive open ray.'),('Can a continuous injective mapℝ→[0,1] attain0?','No. It is strictly monotone; points on one side of a point attaining0 would have negative values.')])
math(26,'On[−1,1], letf_n(x)=(−1)^n(x²+n)/n² andg_n(x)=(−1)^n(x²+n²)/n³. Which series statement is true?',['Σf_n andΣg_n both converge uniformly','Σf_n converges uniformly butΣg_n does not','Σg_n converges uniformly butΣf_n does not','Neither converges uniformly'],'A',['Split each series into an alternating scalar series and anx² multiple of an absolutely convergent scalar series.','Use|x²|≤1 for uniform control of the latter tails.'],
'We haveΣf_n=Σ(−1)^n/n+x²Σ(−1)^n/n² andΣg_n=Σ(−1)^n/n+x²Σ(−1)^n/n³. The first series in each expression is independent ofx and converges by the alternating-series test, so its tail is uniformly small. The second converges uniformly by the WeierstrassM-test with bounds1/n² or1/n³. Sums of uniformly convergent series are uniformly convergent. ThusA;B,C,D are excluded. Neither original series is absolutely convergent atx=0, but absolute convergence is not necessary.',
'Uniform convergence of a function series means that its tails are small simultaneously for all points of the domain. The WeierstrassM-test provides a sufficient condition: if|h_n(x)|≤M_n everywhere andΣM_n<∞, thenΣh_n converges uniformly and absolutely. A convergent scalar series viewed as a series of constant functions is automatically uniform, even when conditional. Finite sums of uniformly convergent series remain uniform. Here splitting isolates a conditionally convergent alternating harmonic part and an absolutely controlledx² part. A failedM-test does not prove nonuniform convergence, and confusing uniform convergence with absolute convergence would miss this decomposition.',
[('DoesΣₙ₌₁∞(−1)^n(1/n+x/n²) converge uniformly on[−2,2]?','Yes. The scalar alternating harmonic part is uniform;|x/n²|≤2/n² gives anM-test for the remaining part.'),('DoesΣx/n² converge uniformly on allℝ?','Pointwise it equalsxπ²/6, but each nonzero tail isx times a positive constant and is unbounded overℝ, so convergence is not uniform.')],d='Hard')
math(27,'LetV be a real vector space andT₁,T₂∈Endℝ(V), withT₁+T₂ andT₁−T₂ linearly independent. Statement(I):T₁,T₂ are independent. Statement(II):there existT₃,T₄ such that{T₁+T₂,T₁−T₂,T₃,T₄} is independent. Which is true?',['I true,II false','II true,I false','Both true','Both false'],'C',['RecoverT₁,T₂ as half the sum and difference.','Independence rules outdimV≤1; ifdimV≥2,End(V) has at least four independent maps.'],
'LetU=T₁+T₂,W=T₁−T₂. ThenaT₁+bT₂=((a+b)/2)U+((a−b)/2)W=0 forcesa+b=a−b=0, soI is true. IfdimV≤1,End(V) has dimension at most1, contradicting independentU,W. ThusdimV≥2. Choose two basis vectors ofV; the four maps sending one of these to one of the two and all other basis vectors to0 are independent, soEnd(V) has dimension at least4. Any independent pair extends to an independent four-element set, provingII. ThereforeC; the alternatives fail.',
'Linear transformations themselves form a vector space under pointwise addition and scalar multiplication. An invertible change of coefficients preserves linear independence, explaining why replacing a pair by its sum and difference is reversible overℝ. For a finite-dimensionalV of dimensiond,End(V) has dimensiond², with matrix units as a basis. For arbitraryV with at least two basis vectors, four matrix-unit-type maps still give a four-dimensional subspace. The independent-set extension theorem allows additional vectors to be selected until the desired size is reached, provided the ambient space has sufficient dimension. The relevant dimension is that ofEnd(V), not merely that ofV.',
[('Ifu+v andu−v are independent overℝ, proveu,v are independent.','au+bv=0 becomes((a+b)/2)(u+v)+((a−b)/2)(u−v)=0; both coefficients vanish, givinga=b=0.'),('How many independent endomorphisms canℝ² support?','End(ℝ²) has dimension4, realized by the four2×2 matrix unitsE₁₁,E₁₂,E₂₁,E₂₂.')],topic='Linear Algebra',d='Hard')
math(28,'Anℝ-linearT:ℝ⁴→ℝ⁴ satisfies(T²+T+I)(T−2I)=0 and(T²+T+2I)(T²−4I)=0. Which statement is FALSE?',['T is diagonalizable overℝ','The characteristic polynomial is(x−2)⁴','The characteristic polynomial is(x²+x+2)(x²−4)','Every endomorphismS ofℝ⁴ satisfiesST=TS'],'C',['The minimal polynomial divides both annihilating polynomials.','Find their greatest common divisor.'],
'Letp=(x²+x+1)(x−2) andq=(x²+x+2)(x−2)(x+2). Their only common factor isx−2: the two quadratics differ by1, and neither vanishes at±2. Thusm_T dividesx−2, forcingT=2I. ConsequentlyT is diagonalizable(A),χ_T=(x−2)⁴(B), andT commutes with everyS(D). C has roots and coefficients incompatible with2I and is false. This checks every option.',
'The minimal polynomial of a linear map is the monic polynomial of smallest positive degree that annihilates it. Polynomial division shows it divides every annihilating polynomial, hence also their greatest common divisor by Bézout’s identity. A degree-one minimal polynomialx−λ forces the map to equalλI. A scalar map on ad-dimensional space has characteristic polynomial(x−λ)^d and commutes with every endomorphism. In general an annihilating polynomial need not be the characteristic polynomial: its degree or factors may contain unnecessary terms. Using all supplied polynomial identities can eliminate those extra factors and reveal a much stronger conclusion.',
[('If(T−I)(T+I)=0 and(T−I)(T−2I)=0, determineT.','The gcd of the polynomials isx−1, soT−I=0 andT=I.'),('DoesA²=I implyχ_A=x²−1?','No. ForA=I₃, the identity holds butχ_A=(x−1)³. Annihilating and characteristic polynomials differ.')],topic='Linear Algebra')
math(29,'LetA be a3×3 complex matrix withA³=I. Which statement is true?',['A is diagonalizable','A has at least two distinct eigenvalues','The characteristic polynomial isx³−1','The minimal polynomial cannot have degree2'],'A',['The minimal polynomial dividesx³−1.','Overℂ this polynomial splits into distinct linear factors.'],
'x³−1=(x−1)(x−ω)(x−ω²), whereω=e^(2πi/3), has distinct roots. The minimal polynomial ofA divides it and is therefore a product of distinct linear factors. HenceA is diagonalizable:A. B andC fail forA=I₃, with a single eigenvalue andχ=(x−1)³. D fails forA=diag(1,1,ω), whose minimal polynomial is(x−1)(x−ω) of degree2.',
'A finite-dimensional matrix over a field is diagonalizable precisely when its minimal polynomial splits into distinct linear factors over that field. IfA satisfiesp(A)=0, thenm_A dividesp, so a square-free split annihilating polynomial guarantees diagonalizability. Repeated eigenvalues in the characteristic polynomial are permitted: a diagonal matrix can repeat diagonal entries without acquiring Jordan blocks. The characteristic polynomial records algebraic multiplicities, while the minimal polynomial records the largest Jordan-block sizes. Overℂ, roots of unity are available; overℝ a polynomial may be square-free but fail to split, so the field must remain part of the conclusion.',
[('A complex matrix satisfiesA⁵=I. Must it be diagonalizable?','Yes.x⁵−1 has no repeated roots in characteristic0 because its derivative5x⁴ has no common root with it.'),('GiveA³=I with minimal polynomial of degree1.','A=ωI hasm_A=x−ω and satisfiesA³=ω³I=I.')],topic='Linear Algebra')
math(30,'ForA=[[1,1,0],[1,2,1],[1,1,2]], which statement is true? Pᵗ denotes transpose.',['There is real invertibleP withPAP⁻¹ diagonal andPᵗP=I₃','There is real invertibleP withPAP⁻¹ diagonal andPᵗP≠I₃','One eigenvalue ofA is nonreal','A has only real eigenvalues and is not diagonalizable overℝ'],'B',['Compute the characteristic polynomial and check whetherA is symmetric.','Three distinct real eigenvalues give real diagonalization; orthogonal diagonalization would force symmetry.'],
'χ_A(x)=det(xI−A)=(x−1)((x−2)²−2). The eigenvalues1,2+√2,2−√2 are distinct and real, soA is diagonalizable overℝ, excludingC,D. ButA is not symmetric sinceA₁₃=0 whileA₃₁=1. IfP were orthogonal andPAP⁻¹=D diagonal, thenA=PᵗDP would be symmetric. ThusA has no orthogonal diagonalization. Its existing diagonalizingP must satisfyPᵗP≠I, makingB true andA false.',
'Distinct eigenvalues yield linearly independent eigenvectors, so a real matrix withd distinct real eigenvalues is diagonalizable overℝ. Orthogonal diagonalization is stronger: the real spectral theorem states that a real matrix is orthogonally diagonalizable exactly when it is symmetric. In the conventionPAP⁻¹=D, the rows ofP are arranged from a suitable inverse eigenvector matrix; for orthogonalP the inverse isPᵗ. A nonsymmetric matrix can still have entirely real eigenvalues and a full eigenbasis, but that basis cannot be chosen orthonormal. Checking symmetry before seeking an orthogonal eigenbasis prevents confusing these two forms of diagonalization.',
[('Can[[1,1],[0,2]] be diagonalized overℝ and orthogonally?','Its distinct real eigenvalues1,2 give diagonalization. It is nonsymmetric, so it cannot be orthogonally diagonalized.'),('Orthogonally diagonalize[[2,1],[1,2]].','Normalized eigenvectors(1,1)/√2 and(1,−1)/√2 give eigenvalues3 and1. Using them as rows ofP yieldsPAPᵗ=diag(3,1).')],topic='Linear Algebra')
math(31,'Inℝ⁴ with the standard inner product, V=span{(1,0,0,1),(0,1,0,1),(0,0,1,0)}. Which is NOT an orthonormal basis?',['{(−1/√2,0,0,−1/√2),(−1/√6,√2/√3,0,1/√6),(0,0,1,0)}','{(1/√2,0,0,1/√2),(−1/√6,√2/√3,0,1/√6),(0,0,1,0)}','{(1/√2,0,0,1/√2),(−1/√6,√2/√3,0,−1/√6),(0,0,1,0)}','{(1/√2,0,0,1/√2),(1/√6,−√2/√3,0,−1/√6),(0,0,1,0)}'],'C',['DescribeV by the equationx₄=x₁+x₂.','In the third option, test the dot product of the first two vectors.'],
'V consists of(a,b,c,a+b) and has dimension3. InC the first two vectors have dot product−2/√12=−1/√3≠0. Moreover the second vector hasx₁+x₂=(−1+2)/√6=1/√6 butx₄=−1/√6, so it is not inV. ThusC is not an orthonormal basis. InA,B,D all vectors lie inV, have norm1, and are mutually orthogonal: the second vector is±(−1,2,0,1)/√6 and the first is±(1,0,0,1)/√2. Three such independent vectors form a basis, excludingA,B,D.',
'An orthonormal basis must satisfy three requirements: every vector belongs to the subspace, each has norm one, and distinct vectors have inner product zero. Orthogonal nonzero vectors are automatically linearly independent, so a set with the subspace’s dimension then spans it. A parametric description can be converted to a simple linear membership equation, making verification faster than solving separate span systems. Changing the sign of an entire basis vector preserves orthonormality and membership; changing only one coordinate generally does not. Gram-Schmidt constructs orthogonal vectors by subtracting projections, after which normalization divides by their positive norms.',
[('Find an orthonormal basis ofspan{(1,0,1),(0,1,1)}.','Takeu=(1,0,1)/√2. Subtract the projection of(0,1,1) on u to get(−1/2,1,1/2); normalize to v=(−1,2,1)/√6.'),('If{u,v} is orthonormal, is{−u,v} orthonormal?','Yes. Norms are unchanged and⟨−u,v⟩=−⟨u,v⟩=0; their spans are identical.')],topic='Linear Algebra')
print('Saved',len(w.packs),'questions')
math(32,'LetA=[[0,0,1],[0,1,0],[1,0,0]] andB(v,w)=vᵗAw onℝ³. Which statement is true?',['B(v,v)=0 iff v=0','For everyλ∈ℝ there existsv withB(v,v)=λ','There existsv≠0 withB(v,w)=0 for allw','IfB(v,w)=0 thenv=0 orw=0'],'B',['Write the quadratic form as2v₁v₃+v₂².','Choosev=(1,0,λ/2) to realize an arbitraryλ.'],
'Forv=(a,b,c),B(v,v)=2ac+b². Settingv=(1,0,λ/2) givesλ, provingB. A is false becausee₁≠0 butB(e₁,e₁)=0. A is invertible(A²=I), soB(v,w)=0 for everyw impliesvᵗA=0 andv=0; C is false. ForD, takev=w=e₁, both nonzero, withB(v,w)=0. Thus onlyB holds.',
'A bilinear formB(v,w)=vᵗAw is nondegenerate when its matrixA is invertible. Nondegeneracy says no nonzero vector pairs to zero with every vector; it does not say that every pair of nonzero vectors has nonzero pairing. For symmetricA, the associated quadratic formq(v)=B(v,v) can be positive definite, negative definite or indefinite. An indefinite form can attain positive and negative values and may have nonzero isotropic vectors withq(v)=0. Expanding the formula in coordinates distinguishes these notions directly. In this example the positive and negative directions arise from the exchange of the first and third coordinates.',
[('Forq(x,y)=x²−y², find a nonzero isotropic vector and realize anyλ.','(1,1) is isotropic. Forλ≥0 use(√λ,0); forλ<0 use(0,√(−λ)).'),('Can a nondegenerate inner product have two nonzero orthogonal vectors?','Yes. Inℝ², standard dot product pairs e₁ ande₂ to0, although it is nondegenerate.')],topic='Linear Algebra')
math(33,'Letf(z)=u(x,y)+iv(x,y) be entire. Defineg(z)=u(x,−y)−iv(x,−y) forz=x+iy. Supposev(x,0)=0 for all realx, andE={z:f(z)=g(z)}. Which is true?',['E is the real axis','E is the imaginary axis','E contains an open set butE≠ℂ','E=ℂ'],'D',['Observeg(z)=overline{f(overline z)}.','The reflected function is entire and agrees withf onℝ; apply the identity theorem.'],
'If f(z)=Σa_nz^n, then g(z)=overline{f(overline z)}=Σoverline{a_n}z^n, so g is entire. Onℝ, v(x,0)=0 givesf(x)=overline{f(x)}=g(x). The entire functionf−g vanishes onℝ, a set with accumulation points insideℂ. By the identity theorem it vanishes everywhere. HenceE=ℂ, D. A andB give proper axes andC explicitly excludesℂ, so all are false.',
'The identity theorem states that holomorphic functions on a connected open domain agreeing on a set with an accumulation point in that domain agree everywhere. Their agreement set need not contain an open set; a line segment is enough. The reflectionh(z)=overline{f(overline z)} is holomorphic whenf is holomorphic on a conjugation-invariant domain, as its power series has conjugated coefficients. If an entire function takes real values on the real axis, it satisfies this reflection symmetry throughoutℂ, equivalently its Taylor coefficients at0 are real. Complex conjugatingf(z) alone would generally produce an antiholomorphic function, so both conjugations matter.',
[('An entiref equalsz² on every realx. Determinef.','f(z)−z² is entire and zero onℝ; the identity theorem givesf(z)=z² for allz.'),('Doesf(z)=iz satisfyf(z)=overline{f(overline z)}?','No. The reflected function is−iz. Alsof(x)=ix is not real except at0, so the reflection premise fails.')],topic='Complex Analysis')
math(34,'LetR₊={z:Re z>0},R₋={z:Re z<0},D={z:|z|<1},T₁(z)=(z−1)/(z+1),T₂(z)=(z+1)/(z−1). Which statement is true?',['T₁,T₂ mapR₊,R₋ respectively conformally ontoD','T₁,T₂ mapR₋,R₊ respectively conformally ontoD','T₁,T₂ mapD ontoR₊,R₋ respectively','T₁,T₂ mapD ontoR₋,R₊ respectively'],'A',['Compare|z−1| and|z+1| usingRe z.','For the maps onD, calculate the real parts directly to check the alternatives.'],
'|z+1|²−|z−1|²=4Re z. Thus|T₁(z)|<1 exactly whenRe z>0, and|T₂(z)|<1 exactly whenRe z<0. Their poles−1 and1 lie outside those respective domains, and their nonzero derivatives ensure conformality. Inverses(1+w)/(1−w) and(w+1)/(w−1) have the required positive and negative real parts for|w|<1, proving onto. A is true;B reverses the domains. For|z|<1,Re T₁=(|z|²−1)/|z+1|²<0 andRe T₂=(|z|²−1)/|z−1|²<0, soC,D are false.',
'A fractional linear or Möbius map(az+b)/(cz+d), withad−bc≠0, is one-to-one on the extended complex plane and has nonzero derivative away from its pole. It maps circles or lines to circles or lines. To establish an exact disk image, a modulus inequality gives the correct side of the boundary, while the inverse verifies surjectivity. Cayley-type transforms relate half-planes to disks. Multiplying out squared moduli often reduces complex inequalities to the sign of a real part. Formula signs and inverse maps must be checked explicitly: superficially similar Möbius transformations can send the same disk to the same half-plane rather than opposite ones.',
[('ShowC(z)=(z−i)/(z+i) sends the upper half-plane to the unit disk.','|z+i|²−|z−i|²=4Im z>0, hence|C|<1. Its inversei(1+w)/(1−w) has positive imaginary part for|w|<1.'),('FindRe((1+w)/(1−w)) for|w|<1.','Multiply by1−overline w: the real part is(1−|w|²)/|1−w|²>0.')],topic='Complex Analysis')
math(35,'γ is the counterclockwise circle|z|=3 andf is entire. For whichA does∮γ[A/(z−1)−f(z)/(z−2)²]dz=0?',['f(1)','f(2)','f′(1)','f′(2)'],'D',['Both1 and2 lie insideγ.','The double denominator invokes Cauchy’s derivative formula.'],
'By Cauchy’s formulas,∮γA/(z−1)dz=2πiA and∮γf(z)/(z−2)²dz=2πif′(2). Their difference vanishes iffA=f′(2), D. A,B,C evaluate the wrong quantity or point. For examplef(z)=z² gives the requiredA=4, whereas those three proposals are1,4,2; B happens to coincide for this onef, but is not the general formula (takef(z)=z³).',
'Cauchy’s integral formula applies whenf is holomorphic on and inside a positively oriented simple closed contour and the evaluation pointa lies inside: ∮f(z)/(z−a)dz=2πif(a). Its derivative version is∮f(z)/(z−a)^(m+1)dz=(2πi/m!)f^(m)(a). The denominator order determines which derivative appears. A constant numerator at a simple pole contributes2πi times that constant. Orientation reversal changes the sign of both terms; subtraction signs still need careful tracking. Entiref automatically supplies all needed holomorphicity assumptions. A formula must hold for arbitraryf, so an accidental match for one polynomial does not validate an option.',
[('Evaluate∮_|z|=3z³/(z−1)²dz counterclockwise.','Cauchy’s derivative formula gives2πi·3=6πi.'),('Evaluate∮_|z|=2e^z/z³dz counterclockwise.','Here m=2 and(e^z)″ at0 is1, so the value is(2πi/2!)·1=πi.')],topic='Complex Analysis')
math(36,'Letf(z)=z²(e^z−e^(−z)) andg(z)=z²/(e^z−e^(−z)), interpreted meromorphically. Which statement atz=0 is true?',['f has a zero of order3 andg a pole of order1','f has a zero of order2 andg a pole of order1','f has a zero of order3 andg a zero of order1','f has a zero of order2 andg a zero of order1'],'C',['Expand the odd exponential difference at0.','It begins2z; compare numerator and denominator vanishing orders.'],
'e^z−e^(−z)=2z+z³/3+O(z⁵)=z h(z), withh holomorphic andh(0)=2. Thenf=z³h(z), so its zero has order3. Alsog=z/h(z) extends holomorphically at0 and has a simple zero there. ThusC. A incorrectly declares a pole after cancellation;B,D also give the wrong order off.',
'A holomorphic function has a zero of orderm ata when it factors as(z−a)^m h(z), withh holomorphic andh(a)≠0. For meromorphic functions the order of a product adds and the order of a quotient subtracts. Positive order means a zero, negative order a pole, and zero order a nonzero regular value. If numerator and denominator both vanish, cancellation may give a removable singularity instead of a pole. Taylor series expose the first nonzero coefficient, which determines the exact order. In the odd exponential difference the constant terms cancel and the linear terms add; overlooking that cancellation changes both answers.',
[('Classifyz²/sinz at0 after extension.','sinz=z(1−z²/6+⋯), soz²/sinz=z/(1−z²/6+⋯) has a simple zero.'),('Find the order at0 of(sinz)²/z³.','The numerator has order2 and denominator order3, so the quotient has order−1: a simple pole.')],topic='Complex Analysis')
math(37,'For a primep, letS_p be the number of primitive roots in(ℤ/pℤ)× andφ Euler’s totient. Which statement is true?',['For eachp<100,Σₙ₌₁∞(S_p/φ(p))^n converges','For each100≤p≤200,the series diverges','For eachp>200,the series converges','4 mod101 is a primitive root'],'C',['The multiplicative group modulo a prime is cyclic of orderp−1 and hasφ(p−1) generators.','For oddp,φ(p−1)/(p−1)≤1/2; separately examinep=2.'],
'S_p=φ(p−1) andφ(p)=p−1. For oddp, p−1 is even, so0<S_p/φ(p)≤1/2<1; its geometric series converges. ThereforeC is true andB false. A fails atp=2, whereS₂=φ(2)=1 and the seriesΣ1 diverges. D is false because4=2² mod101 has4⁵⁰=2¹⁰⁰=1 by Fermat’s theorem, so its order divides50 and cannot be100.',
'The multiplicative group of a finite prime field is cyclic withp−1 elements. A cyclic group of orderm hasφ(m) generators: ifg is a generator, g^a generates exactly when gcd(a,m)=1. Thus counting primitive roots reduces to Euler’s totient. The geometric seriesΣr^n converges exactly when|r|<1; the boundaryr=1 diverges even if many nearby cases converge. For evenm, at most half the integers1,...,m are coprime tom, givingφ(m)≤m/2. A square modulo an odd prime has order dividing(p−1)/2, so it cannot generate the whole group. Small exceptional primes must be checked in universal assertions.',
[('How many primitive roots are there modulo7?','The group has order6, soφ(6)=2 generators, namely3 and5.'),('Can9 mod17 be primitive?','No:9=3² and9⁸=3¹⁶=1, so its order divides8 rather than the required16.')],topic='Number Theory')
math(38,'LetG be a finite group of ordern>3 andH a subgroup with1<|H|<n. SetX=⋃_{g∈G}gHg⁻¹. Which statement is true?',['IfG is abelian,|X|=n','If|X| dividesn,thenG is abelian','|X|<n','|X| dividesn'],'C',['All conjugate subgroups contain the identity.','Their number is[G:N_G(H)]≤[G:H]; bound the union using its shared identity.'],
'Writeh=|H| andr for the number of conjugates. SinceH⊆N_G(H),r=n/|N_G(H)|≤n/h. Every conjugate contains e, so|X|≤1+r(h−1)≤1+(n/h)(h−1)=n−n/h+1<n becausen/h>1. ThusC. IfG is abelian, X=H, soA fails. ForB use nonabelianS₃,H=A₃: X=H has size3 dividing6. ForD useS₃ and a transposition subgroup: X consists of the identity and three transpositions, size4, not dividing6.',
'Conjugation sends a subgroupH to an isomorphic subgroupgHg⁻¹. The number of distinct conjugates is the index of the normalizerN_G(H)={g:gHg⁻¹=H}; this follows from the orbit-stabilizer theorem for the conjugation action. The normalizer containsH, providing an upper bound by[G:H]. A union is not usually a subgroup, so Lagrange’s divisibility theorem cannot automatically be applied to its size. The common identity creates enough overlap to prevent all conjugates of a proper subgroup from covering a finite group. Normal subgroups give a single conjugate; abelian groups make every subgroup normal.',
[('InS₃, find the union of conjugates ofH={e,(12)}.','The conjugates are{e,(12)},{e,(13)},{e,(23)}, so their union has4 elements.'),('In a group of order12, a subgroup of order3 has at most4 conjugates. Bound their union.','All sharee, hence union size≤1+4(3−1)=9<12.')],topic='Abstract Algebra',d='Hard')
math(39,'Letψ:ℂ[x,y]→ℂ[t] beψ(f)=f(t²,t³). Which statement is true?',['ψ is surjective','Ifp₁(x)y+p₂(x)∈kerψ forp₁,p₂∈ℂ[x],thenp₁=p₂=0','There are nonzero suchp₁,p₂ withψ(p₁y+p₂)=0','There existsf withψ(f)=0 butψ(f²)≠0'],'B',['Monomials map tot^(2a+3b), so the image cannot containt.','In p₁(t²)t³+p₂(t²), one part has odd powers and the other even powers.'],
'A is false: exponents2a+3b witha,b≥0 never equal1, sot is absent from the image. ForB, ψ(p₁y+p₂)=p₁(t²)t³+p₂(t²)=0. The first summand has only odd exponents and the second only even exponents. Coefficient comparison forces both to vanish, hencep₁=p₂=0. ThusB true andC false. D contradicts multiplicativity: ψ(f²)=ψ(f)²=0 wheneverψ(f)=0. Althoughkerψ is nonzero (y²−x³ lies in it), no nonzero relation linear iny occurs.',
'A polynomial substitution defines a ring homomorphism, preserving sums, products and1. Its image here isℂ[t²,t³], and its kernel contains the algebraic relationy²−x³. Distinct polynomial monomials are linearly independent, so separating even and odd exponents is a rigorous coefficient comparison. The substitutionx↦t² is injective onℂ[x], since distinct powers ofx become distinct even powers oft. A kernel is an ideal and is closed under multiplication by every polynomial; in particular it is closed under squaring. Surjectivity requires every target polynomial, includingt, to be obtainable, not merely infinitely many powers.',
[('Find a nonzero element ofkerψ forψ(x)=t²,ψ(y)=t³.','y²−x³ maps tot⁶−t⁶=0 and is a nonzero polynomial.'),('Forη(x)=t²,η(y)=t⁴, is there a relation linear iny?','Yes:y−x² maps tot⁴−t⁴=0. The parity argument no longer separates the two parts.')],topic='Abstract Algebra')
math(40,'Withℕ the positive integers andℝ² Euclidean, setA={(n,1/n):n∈ℕ} andB={(n,1/m):n,m∈ℕ}. Which statement is true?',['A is closed butB is not closed','B is closed butA is not closed','Both are closed','Neither is closed'],'A',['For a convergent sequence of points ofA, the integer first coordinates must eventually be constant.','InB, holdn=1 fixed and letm tend to infinity.'],
'If(n_j,1/n_j) converges inℝ², thenn_j converges as a sequence of positive integers and is eventually a constantn. Its limit is(n,1/n)∈A. By the sequential closedness criterion,A is closed. But(1,1/m)∈B converges to(1,0), which is absent fromB. HenceB is not closed, givingA and excludingB,C,D. The fact1/n→0 does not produce a finite accumulation point ofA because its first coordinate tends∞.',
'In a metric space, a subset is closed exactly when it contains the limits of all its convergent sequences. A convergent sequence of integers is eventually constant: once its terms lie in a sufficiently short interval around the limit, there is only one possible integer. For sets of ordered pairs, both coordinates must converge to finite values for a limit inℝ². One coordinate tending0 while another tends∞ does not yield an accumulation point in the plane. Separating independent indices from coupled indices is decisive: B allows a fixed first coordinate while its second coordinate approaches0, whereas A does not.',
[('Is{(n,0):n∈ℕ} closed inℝ²?','Yes. Any convergent sequence has eventually constant integer first coordinate and limit in the set.'),('Find the closure of{(1,1/m):m∈ℕ}.','It is the set itself together with(1,0), the only additional accumulation point.')],topic='Topology')
print('Saved',len(w.packs),'questions')
