from pack_writer import Writer
w=Writer('2024-june','-q001-060')
def add(n,topic,prompt,opts,key,hints,sol,theory,ex,diff='Moderate',track=None,status='reviewed',note=''):
 w.add(n,track or ('Shared' if n<=20 else 'Mathematics'),topic,diff,prompt,opts,key,hints,sol,theory,ex,status,note)
add(1,'Aptitude',r'The diagrams show numbers of trees in 25 quadrats of each of two forest patches. In A all 25 entries are 1. In B the rows are $(2,0,0,0,0)$, $(0,0,0,0,0)$, $(0,0,0,7,0)$, $(0,10,0,0,0)$, $(0,0,0,0,6)$. Which statement about the means $\mu$ and standard deviations $\sigma$ is true?',
[r'$\mu(A)=\mu(B),\ \sigma(A)=\sigma(B)$',r'$\mu(A)>\mu(B),\ \sigma(A)>\sigma(B)$',r'$\mu(A)=\mu(B),\ \sigma(A)<\sigma(B)$',r'$\mu(A)<\mu(B),\ \sigma(A)<\sigma(B)$'],'C',
['Find the sum of all quadrat counts in each patch before comparing their variability.','Patch A has no variation. Patch B has the same total count but several unequal entries.'],
r'Both totals are 25: A has 25 ones, and B has $2+7+10+6=25$. Hence both means equal 1. A has variance 0. B has population variance $(2^2+7^2+10^2+6^2)/25-1^2=189/25-1=164/25>0$, so $\sigma(B)=\sqrt{164}/5$. Therefore C is true. A fails because standard deviations differ; B and D fail because the means are equal. Using sample rather than population standard deviations leaves the comparison unchanged.',
r'The arithmetic mean of $N$ values is their sum divided by $N$. Population variance is $N^{-1}\sum(x_i-\bar x)^2=N^{-1}\sum x_i^2-\bar x^2$; standard deviation is its nonnegative square root. It measures dispersion rather than the total amount. A constant list has variance zero, and a nonconstant list has positive variance. Two equal-length lists with equal totals necessarily have equal means, even if one is highly clustered. For a sample variance, divide the squared deviations by $N-1$ instead; comparisons here are unchanged because the list lengths match. Count zero entries as observations: omitting empty quadrats would change the mean and the ecological interpretation. The diagram represents one observation per quadrat, not one per tree.',
[(r'Compare means and population variances of $(2,2,2,2)$ and $(0,0,4,4)$.',r'Both sums are 8 and both means are 2. The first variance is 0. The second is $(4+4+4+4)/4=4$, with standard deviation 2.'),(r'Find the mean and population variance of $(0,0,0,8)$.',r'The mean is $8/4=2$. The second moment is $64/4=16$, so the variance is $16-2^2=12$ and standard deviation $2\sqrt3$.')],diff='Easy')
add(2,'Aptitude','Among both male and female finches, 50% have red heads, 30% blue and 20% yellow. Males and females pair randomly. In 10000 pairs, what is the expected number with a red male and a yellow female?',['2500','1500','1000','600'],'C',
['Random pairing makes the male and female colours independent for one pair.','Multiply the red-male proportion by the yellow-female proportion, then multiply by the number of pairs.'],
r'The probability for the specified ordered colour pairing is $0.50\times0.20=0.10$. Let $I_j$ indicate that pair $j$ has a red male and yellow female. Then $E\sum_{j=1}^{10000}I_j=10000(0.10)=1000$. Thus C is correct; the other three counts do not equal this expectation. Do not add yellow-male/red-female pairs, since the requested sexes are fixed.',
r'For independent categories, the probability of a joint specification is the product of its marginal probabilities. Random mating is the relevant independence assumption; it would fail under colour preference. An indicator takes value 1 when an event occurs and 0 otherwise, so its expectation equals the event probability. Linearity of expectation then gives $Np$ expected occurrences among $N$ trials. Independence between all the pair indicators is unnecessary for this expectation, which also makes the method valid for random matching without replacement in a large population with fixed proportions. An expected count need not be an observed count, or even an integer. Ordered sex-colour specifications should not be doubled unless both orders are requested.',
[('In 2000 random pairs, 40% of males are blue and 25% of females are red. Find the expected blue-male/red-female count.',r'Each pair has probability $.4(.25)=.1$, so the expected count is $2000(.1)=200$.'),('In 500 random pairs, both sexes have red proportion 0.6 and yellow proportion 0.4. Find the expected mixed red/yellow count in either order.',r'The mutually exclusive orders have probabilities $.6(.4)$ and $.4(.6)$. Their sum is .48, giving expected count $500(.48)=240$.')],diff='Easy')
add(3,'Aptitude','The length of bristlemouth fish is uniformly distributed between 2 and 4 inches. If a fisherman randomly catches 5 such fishes, what is the probability that at least one is 3 inches or longer?',['0.03125','0.15625','0.84375','0.96875'],'D',
['For one fish, compare the lengths of the intervals [3,4] and [2,4].','Use the complement: all five fish are shorter than 3 inches.'],
r'Under independent random catches, $P(L<3)=(3-2)/(4-2)=1/2$. Hence $P(\text{at least one }L\ge3)=1-P(\text{all five }L<3)=1-(1/2)^5=31/32=0.96875$. D is correct. A is the complementary event; B and C are neither the requested probability nor its complement.',
r'A continuous uniform variable on $[a,b]$ assigns probability equal to interval length divided by $b-a$. Individual points have probability zero, so using $\ge$ rather than $>$ at an interior threshold has no effect. For independent trials whose success probability is $p$, the number of successes is binomial and $P(\text{at least one})=1-(1-p)^n$. The complement is often much easier than adding probabilities for one, two, up to $n$ successes. Independence is needed to multiply failure probabilities; identical marginal distributions alone would not justify that multiplication. Keep the event direction clear: the probability that all fish are below the threshold is the quantity subtracted from one, not the final answer.',
[(r'Four independent lengths are uniform on $[1,5]$. Find the chance at least one exceeds 4.',r'One failure has probability $(4-1)/4=3/4$. The answer is $1-(3/4)^4=175/256$.'),(r'Six independent fair coin tosses are made. Find the probability of at least one head.',r'All six tails have probability $2^{-6}=1/64$. Therefore the answer is $1-1/64=63/64$.')],diff='Easy')
add(4,'Aptitude',r'The source graph shows three exponential growth curves $N(t)=N_0e^{rt}$. Initially A is below B, which is below C; the curves cross, and later A is above B, which is above C (A solid, B dashed, C dotted). For their intrinsic growth rates, which statement is true?',
[r'$r_A=r_B=r_C$',r'$r_A>r_B=r_C$',r'$r_A=r_B>r_C$',r'$r_A>r_B>r_C$'],'D',
['Compare relative growth rather than just initial population sizes.','If two positive exponential curves change their order, the initially smaller one has the greater exponent.'],
r'For any two populations, $N_A(t)/N_B(t)=(N_{0,A}/N_{0,B})e^{(r_A-r_B)t}$. Since A starts below B and later lies above B, this ratio increases through 1, requiring $r_A-r_B>0$. Similarly B overtakes C, so $r_B-r_C>0$. Thus $r_A>r_B>r_C$, option D. Equal exponents keep the ratio constant and cannot produce the crossings, ruling out A, B and C.',
r'In exponential growth the intrinsic rate $r$ is a relative rate: $N^\prime(t)/N(t)=r$, not the absolute slope $N^\prime(t)$. On a logarithmic population scale, $\log N(t)=\log N_0+rt$ is a straight line with slope $r$. A larger population can have a steeper ordinary graph even when its intrinsic rate is smaller, so absolute slopes at arbitrary unequal population levels are unreliable. Instead compare ratios, order reversals, or slopes at a common population value. Two positive exponential curves with the same exponent never cross unless they coincide throughout. For different exponents their ratio is strictly monotone, so they cross at most once. The graph supplies order reversals sufficient to compare all three rates.',
[(r'$A(t)=2e^{3t}$ and $B(t)=8e^t$. When does A overtake B?',r'Solve $2e^{3t}=8e^t$, giving $e^{2t}=4$ and $t=\log2$. A has rate 3 versus 1, so it is greater after that time.'),(r'$A(t)=5e^{.2t}$ and $B(t)=10e^{.2t}$. Can they cross?',r'The ratio $A/B=1/2$ is constant. They never cross despite both growing; their intrinsic rates are equal.')],diff='Easy')
add(5,'Aptitude','Four fair coins are tossed independently. An outcome is favourable if the number of heads exceeds the number of tails. Find the probability of a favourable outcome.',[r'$1/2$',r'$3/16$',r'$5/16$',r'$3/4$'],'C',
['With four coins, more heads than tails means three or four heads.','Count the outcomes for exactly three heads and for four heads among 16 equally likely outcomes.'],
r'There are $2^4=16$ equiprobable sequences. Favourable sequences have 3 or 4 heads, numbering $\binom43+\binom44=4+1=5$. Therefore the probability is $5/16$, C. A incorrectly treats ties as impossible; B omits some favourable outcomes; D is too large. Alternatively symmetry gives $(1-P(H=2))/2=(1-6/16)/2=5/16$.',
r'For $n$ independent fair coin tosses, each ordered outcome has probability $2^{-n}$ and exactly $k$ heads occurs in $\binom nk$ outcomes. Thus the head count is binomial. When $n$ is even, heads and tails can tie; symmetry gives $P(H>T)=P(T>H)=(1-P(H=T))/2$, rather than one half. When $n$ is odd, a tie is impossible and the probability is one half. Translate verbal conditions into integer inequalities before counting: here $H>4-H$ means $H>2$. Counting only unordered patterns loses their multiplicities. For biased coins use $\binom nkp^k(1-p)^{n-k}$ instead of equal-probability counting.',
[('Find the chance of more heads than tails in six fair independent tosses.',r'$P(H=3)=\binom63/64=20/64$. Symmetry gives $(1-20/64)/2=22/64=11/32$.'),('Find the chance of more heads than tails in five fair independent tosses.',r'No tie is possible. Complementary head/tail reversal pairs have equal probabilities, so the probability is $1/2$.')],diff='Easy')
add(6,'Aptitude','An athlete falls 10 m short of the finish when running at a constant speed for a given time. Increasing her speed by 20% makes her overshoot by 20 m in the same time. Find the track length.',['134 m','156 m','160 m','164 m'],'C',
['Write the original distance as track length minus 10.','In equal time, multiplying speed by 1.2 multiplies distance by 1.2.'],
r'Let the track length be $L$. The original distance is $L-10$, and the increased-speed distance is $1.2(L-10)=L+20$. Thus $.2L=32$, so $L=160$ m. Check: 150 m initially and 180 m afterwards give exactly the stated shortfall and overshoot. C is correct; substituting 134, 156 or 164 does not satisfy the equation.',
r'At constant speed, distance is speed times time. If time is unchanged, a percentage change in speed produces the same percentage change in distance. Shortfall and overshoot are measured relative to the target, not relative to the original distance. If the shortfall is $a$, overshoot is $b$, and fractional speed increase is $p$, then $(1+p)(L-a)=L+b$, giving $L=a+(a+b)/p$. This equation also shows that the distance gained is $a+b$ and equals $p$ times the original distance. Convert percentages to fractions, such as 20% to 0.2, before substituting. Verify the computed length by evaluating both distances, which catches sign mistakes.',
[('A runner falls 5 m short; a 10% speed increase in the same time overshoots by 7 m. Find the track length.',r'The distance increase is 12 m, so original distance is $12/.1=120$ m. The track is $120+5=125$ m.'),('A 200 m track is attempted. The original run is 180 m and the faster run is 225 m in equal time. Find the percentage speed increase.',r'The ratio is $225/180=1.25$, so speed increased by 25%. The shortfall and overshoot are 20 and 25 m.')],diff='Easy')
add(7,'Aptitude','What is the minimum number of notes needed for Rs 4849 when only Rs 2, 5, 20, 50 and 500 notes are available?',['19','20','21','22'],'B',
['Use large notes to construct a candidate, but check whether the small remainder can be made more efficiently.','For fewer than 20 notes, show that exactly nine Rs 500 notes would be necessary, then analyse the remainder 349 modulo 5.'],
r'A construction uses $9(500)+6(50)+2(20)+1(5)+2(2)=4849$, with $9+6+2+1+2=20$ notes. Suppose at most 19 notes suffice. Ten 500 notes already exceed 4849. With at most eight 500 notes, the maximum possible value is $8(500)+11(50)=4550$, too small. Thus nine are necessary, leaving 349 for at most ten smaller notes. If $d$ denotes the number of Rs 2 notes, reduction modulo 5 gives $2d\equiv4$, so $d=2$ or 7 (within ten notes). Seven leaves 335 for at most three notes, impossible. Two leave 345 for at most eight notes of 50,20,5. Dividing by 5 gives $10a+4b+c=69$, $a+b+c\le8$. Since $a\le6$, if $a=6$ the remaining two notes supply at most 8, below 9; if $a\le5$, the maximum is $10a+4(8-a)\le62$. Thus 19 is impossible. B is the minimum; A is impossible and C,D exceed the achieved minimum.',
r'Coin-change minimization is an integer optimization problem. Greedily taking the largest denomination sometimes works, but not for every denomination system: a proof must exclude smaller note counts. Upper bounds on the value of a fixed number of notes can force how many largest notes are needed. Modular arithmetic then restricts the number of small denominations, especially when all but one are divisible by a common divisor. For computer verification, dynamic programming uses $M(0)=0$ and $M(v)=1+\min_d M(v-d)$ for allowed denominations $d\le v$, treating unattainable values as infinite. Here a construction and a sharp impossibility argument establish optimality without relying on a greedy rule. Always add both values and note counts separately.',
[('Using denominations 1,3,4, find the minimum number of coins for 6.',r'Two coins, $3+3=6$, suffice. One cannot suffice because 6 is not a denomination. Greedy $4+1+1$ uses three, illustrating why greedy needs justification.'),('Using notes 2,5,20,50, find the minimum number for 99.',r'$50+20+20+5+2+2=99$ uses six. If five notes sufficed, modulo 5 requires two Rs 2 notes (or seven, impossible), leaving 95 for three notes of 5,20,50. No sum of three of these is 95: with one 50 the other two would sum45, impossible; two 50 exceed95; no50 gives at most60. Hence six is minimal.')],diff='Hard')
add(8,'Aptitude',r'A cylindrical container with a tiny bottom hole is initially full. If $T$ is its emptying time, which source diagram best approximates water height versus time? Diagram A decreases linearly; B stays constant then drops; C decreases with increasingly steep slope; D decreases steeply at first and then flattens to zero.',
['A (linear decrease)','B (constant until sudden emptying)','C (decreasing with increasingly steep slope)','D (decreasing and flattening)'],'D',
['The outflow slows as the water pressure at the hole decreases.','Torricelli flow is proportional to the square root of the water height; integrate the resulting height equation.'],
r'For tank area $A$ and effective outlet constant $k>0$, Torricelli\'s law gives $A h\prime=-k\sqrt h$. Thus $\sqrt{h(t)}=\sqrt{h_0}(1-t/T)$ and $h(t)=h_0(1-t/T)^2$ for $0\le t\le T$. This is decreasing and convex upward: the negative slope approaches zero. Diagram D, option D, is closest. A would require constant outflow, B would require no gradual drainage, and C predicts increasing outflow as pressure decreases.',
r'A small bottom outlet drains water under hydrostatic pressure. With negligible outlet losses absorbed into a discharge coefficient, Torricelli\'s law makes outlet speed proportional to $\sqrt{2gh}$. For a cylinder the cross-sectional area is constant, so volume conservation yields $h\prime=-c\sqrt h$. Separating variables gives a quadratic height profile and finite emptying time $T=2\sqrt{h_0}/c$. Although the graph flattens, it reaches zero at finite time; it is not an exponential decay. Different tank shapes change the relation between volume and height and therefore change the profile. The model assumes a vented tank, a small outlet and ordinary gravity flow. Comparing curvature and slope direction is enough to choose among schematic diagrams.',
[(r'A cylindrical tank follows $h\prime=-2\sqrt h$, $h(0)=9$. Find its emptying time and height at time 1.',r'$\sqrt h=3-t$ until empty. Thus $T=3$ and $h(1)=4$.'),(r'Two otherwise identical cylindrical tanks start with heights H and 4H. Compare emptying times.',r'$T=2\sqrt{h_0}/c$ for the common outlet constant. Hence the second takes $\sqrt4=2$ times as long, not four times.')])
add(9,'Aptitude','Every second chemistry teacher also teaches physics, and every third physics teacher also teaches chemistry. Find the ratio of chemistry-only teachers to physics-only teachers.',['3:2','1:2','2:3','2:1'],'B',
['Let the number teaching both subjects be x.','Express each total in terms of x, and then subtract the overlap.'],
r'If $x$ teach both, the chemistry total is $2x$ and physics total $3x$. Chemistry-only is $2x-x=x$; physics-only is $3x-x=2x$. The ratio is $1:2$, B. A and C confuse totals with exclusive counts; D reverses the required order.',
r'Overlapping categories require keeping the intersection separate from the totals. If a fraction $p$ of category C also belongs to P and a fraction $q$ of P also belongs to C, the common count $I$ satisfies $I=p|C|=q|P|$. The exclusive counts are $|C|-I$ and $|P|-I$, so their ratio is $(1/p-1):(1/q-1)$. This is independent of the overall population size. The two percentages use different denominators and therefore need not be equal. A Venn diagram or a three-cell table (C only, both, P only) makes the accounting transparent. The question presupposes nonzero teacher counts; otherwise a ratio would be undefined.',
[('One third of mathematics teachers teach biology; one fourth of biology teachers teach mathematics. Find the mathematics-only:biology-only ratio.',r'With overlap x, totals are 3x and4x. Exclusive counts are 2x and3x, giving2:3.'),('There are 60 chemistry teachers and 40 teach both chemistry and physics. Those 40 are half the physics teachers. Find the exclusive ratio.',r'Physics total is80. Chemistry-only is20 and physics-only is40, so the ratio is1:2.')],diff='Easy')
add(10,'Aptitude','A ring rolls clockwise without slipping to the right; its initially topmost point is marked. The source options show the centre shifted about one diameter to the right. Which marked position is possible? A: bottom; B: lower right; C: top; D: upper left.',
['A (marked point at bottom)','B (marked point at lower right)','C (marked point at top)','D (marked point at upper left)'],'B',
['For rolling without slipping, centre displacement equals radius times rotation angle.','A one-diameter displacement gives 2 radians of clockwise rotation from the top.'],
r'Let the radius be R. The depicted shift is about $2R$, so rolling without slipping rotates the ring clockwise by $\theta=2$ radians, about $114.6^\circ$. Starting from the top, the marked point has centre-relative coordinates $(R\sin2,R\cos2)$. The horizontal coordinate is positive and vertical coordinate negative, so it lies on the lower right, diagram B, option B. Bottom would require displacement $\pi R$, top a full circumference $2\pi R$, and upper left a much greater clockwise turn; none matches the diagram.',
r'Rolling without slipping links translation and rotation by $s=R\theta$, with the angle in radians. A material point on a rolling rim changes position relative to the centre as the wheel turns; its full trajectory is a cycloid. For a point initially at the top of a wheel rolling right, relative coordinates are $x_{rel}=R\sin\theta$, $y_{rel}=R\cos\theta$. The centre itself moves right by $R\theta$ and remains height R above the ground. One radius of translation is one radian, not a quarter-turn; one diameter gives two radians, not a half-turn. The no-slip assumption is essential for inferring the rotation from the pictured shift. Estimate the quadrant before trying to interpret exact visual angles.',
[(r'A wheel moves right by $\pi R/2$. Where is a point initially at its top relative to the centre?',r'The clockwise angle is $\pi/2$. Relative coordinates are $(R,0)$, so the point is at the rightmost position.'),(r'A rolling wheel moves right by $\pi R$. Where is its initially topmost point?',r'The angle is $\pi$. Relative coordinates are $(0,-R)$, so the point reaches the bottom and touches the ground.')])
add(11,'Aptitude','On a one-way road, four lanes are demarcated by painted 3.5 m line segments alternating with 3.5 m gaps. What total length of painted lines lies over a 350 m stretch?',['300','400','525','700'],'C',
['Four lanes need three internal separator lines.','In each seven-metre pattern, half the length is painted.'],
r'Four adjacent lanes require three separating lines. Each line has period $3.5+3.5=7$ m, and 350 m contains 50 complete periods. Its painted length is $50(3.5)=175$ m. The total is $3(175)=525$ m, C. A and B use incorrect lengths; D counts four separators instead of three.',
r'Dividing a strip into $k$ adjacent lanes requires $k-1$ internal boundaries. Count boundaries, not the regions they separate. For a periodic dashed marking with painted length $p$ and gap $g$, the painted fraction of every complete period is $p/(p+g)$. A stretch containing an integer number of periods therefore has painted length $Lp/(p+g)$ per separator, independent of the starting phase (apart from endpoint conventions of zero length). Multiply by the number of separators to obtain the total amount of paint line. In this question 350 is exactly divisible by7, so no partial-period correction is needed. Edge lines of the road are not included in the stated lane demarcation.',
[('Five lanes have 2 m dashes and 3 m gaps over 100 m. Find total internal painted length.',r'There are four separators. Each has $100/5=20$ dashes, painted length40 m. Total is160 m.'),('Three lanes have 4 m dashes and 4 m gaps over 240 m. Find total painted length.',r'There are two separators, each painted half of240 m, or120 m. Total is240 m.')],diff='Easy')
add(12,'Aptitude','Choose the best alternative: CURRY is to SPICE as ______ is to COLOUR.',['CANVAS','PAINTING','BRUSH','BRIGHTNESS'],'B',
['Identify the relation between the finished item and a constituent used to make it.','Look for a finished visual work made with colours.'],
'Curry is a prepared dish in which spice is an ingredient. A painting is a finished work in which colour is a constituent, so B preserves the relation. A canvas is a surface that may remain unpainted; a brush is a tool; brightness is a property of colour. Those relations differ from finished product to ingredient.',
'Verbal analogies test a relation, not just an association. First express the original pair in a short sentence: curry is made using spice. Then apply the same sentence and direction to each candidate. A good analogy preserves the roles of both words at comparable levels of description. Tools, surfaces, constituents and properties can all be associated with an activity but are different semantic categories. Here spice contributes to the finished food, as colour contributes to the finished painting. Reject a candidate if matching it would require changing the original relation, such as ingredient to container or object to attribute. The instruction asks for the best correspondence among the available alternatives.',
[('BREAD is to FLOUR as STATUE is to what: CHISEL, MARBLE, MUSEUM, HEIGHT?','Flour is a material used to make bread. Marble is a material used to make a statue. CHISEL is a tool, MUSEUM a location, and HEIGHT a property, so MARBLE is the matching answer.'),('PEN is to WRITE as BRUSH is to what: CANVAS, PAINT, FRAME, COLOUR?','A pen is a tool used to write. A brush is a tool used to paint. PAINT as a verb preserves the tool-to-action relation; the other choices are objects or materials.')],diff='Easy')
add(13,'Aptitude','In a class of 100 students, everyone speaks at least one of English and Hindi. Exactly 41 speak English and 21 speak both. How many speak Hindi?',['58','80','59','38'],'B',
['The entire class is the union of the English and Hindi sets.','Add the two set sizes and subtract the double-counted intersection.'],
r'Inclusion-exclusion gives $100=41+H-21$, hence $H=80$. B is correct. Equivalently 20 speak English only, so the other80 all speak Hindi. The59 students who do not speak English are Hindi-only, not the complete Hindi group; A and D likewise fail the union identity.',
r'For two finite sets, $|E\cup H|=|E|+|H|-|E\cap H|$. Adding both totals counts bilingual students twice, so subtract their intersection once. When everyone belongs to at least one set, the union is the whole population; if some belong to neither, subtract those from the population before applying the identity. Exclusive counts are $|E|-|E\cap H|$ and $|H|-|E\cap H|$, whereas a language total includes bilingual students. A useful check is that the union must be at least as large as either set and that all three disjoint Venn cells are nonnegative. Do not equate Hindi speakers with students who do not speak English.',
[('Of80 students,50 know French,40 know German and everyone knows at least one. How many know both?',r'$80=50+40-I$, so $I=10$. French-only is40 and German-only30, which sum with10 to80.'),('In120 people,10 know neither language,70 know English and25 know both. How many know Hindi?',r'The union has110 people. Thus $110=70+H-25$, so $H=65$.')],diff='Easy')
add(14,'Aptitude','Two items are sold at the same selling price. There is a20% gain on one and a20% loss on the other. What is the overall result?',['Neither loss nor gain','5% loss','4% loss','4% gain'],'C',
['Equal selling prices do not mean equal cost prices.','If each sells for S, the costs are S/1.2 and S/0.8.'],
r'Let each selling price be S. The costs are $5S/6$ and $5S/4$, so total cost is $25S/12$ and total sales are $2S=24S/12$. Loss is $S/12$; loss percentage is $(S/12)/(25S/12)\times100=4\%$. C is correct. A incorrectly cancels percentages with different cost bases; B uses an incorrect denominator; D reverses loss to gain.',
r'Profit and loss percentages are measured relative to cost price. A profit of fraction p means selling price $(1+p)C$, and a loss of fraction p means $(1-p)C$. For equal selling prices S at equal opposing rates, total cost is $S/(1+p)+S/(1-p)=2S/(1-p^2)$; comparing with sales2S gives loss fraction $p^2$. Thus20% opposing rates produce a4% overall loss. The familiar cancellation only applies when the two cost prices are equal, not when the selling prices are equal. Always compute aggregate profit divided by aggregate cost rather than averaging the two individual percentage rates.',
[('Two items sell for the same price, one at10% profit and the other at10% loss. Find overall loss percent.',r'The equal-selling-price formula gives loss fraction $.1^2=.01$, hence1% loss.'),('Two items each cost100 and sell at20% profit and20% loss respectively. Find overall result.',r'Selling prices are120 and80, totalling200 against total cost200. There is neither gain nor loss; here equal costs make the percentage cancellation valid.')],diff='Easy')
add(15,'Aptitude','A group of540 persons is seated in rows so that each row has4 fewer persons than the preceding row. Which number of rows is impossible?',['5','6','8','9'],'C',
['Use the arithmetic progression sum formula with first row size a and common difference −4.','Solve for a at each proposed row count, and require positive integers.'],
r'For n rows, $540=\frac n2[2a-4(n-1)]$, so $a=540/n+2(n-1)$. For n=5, a=116 and last row100; for n=6, a=100 and last row80; for n=9, a=76 and last row44. All are positive integers, so A,B,D are possible. For n=8, a=67.5+14=81.5, not an integer. Hence C is impossible.',
r'Row sizes with a fixed difference form an arithmetic progression. Its nth term is $a+(n-1)d$, and the sum is $n[2a+(n-1)d]/2$. A seating arrangement imposes extra constraints beyond solving the sum equation: every term must be a positive integer. For negative difference, checking the first and last terms guarantees positivity of the intermediate terms. A nonintegral first term rules out an arrangement because person counts cannot be fractional. When several proposed values of n are supplied, substitution is often shorter than deriving all possible n. The total number divided by n is the average row size, which can be half-integral even when all individual row sizes are integers; therefore test the derived first term rather than the average alone.',
[('A total of120 people sit in5 rows decreasing by2 each row. Find all row sizes.',r'$a=120/5+1(5-1)=28$. The rows are28,26,24,22,20 and sum120.'),('Can100 people sit in6 rows decreasing by4 each row?',r'$a=100/6+2(5)=80/3$, not an integer. Thus this arrangement is impossible, even though the arithmetic progression could be written with fractional terms.')])
add(16,'Aptitude','In a class of30 students, roll numbers1–20 average72%, roll numbers11–30 average75%, and the entire class averages70%. Find the average of roll numbers11–20.',['68','74','78','84'],'D',
['The middle ten students occur in both twenty-student totals.','Add those two totals and subtract the thirty-student total.'],
r'Let A,B,C be total percentage marks for rolls1–10,11–20,21–30. Then $A+B=20(72)=1440$, $B+C=20(75)=1500$, and $A+B+C=30(70)=2100$. Subtracting the third equation from the sum of the first two gives $B=840$. The middle ten average $840/10=84\%$, D. A,B,C do not satisfy the three totals.',
r'An average becomes a total after multiplication by the number of observations. When two groups overlap, their combined totals count shared observations twice. Subtracting the total over their union leaves exactly the overlap total, a numerical version of inclusion-exclusion. Here the two twenty-student groups cover all30 students and share ten. Group averages cannot generally be added or subtracted directly; convert to totals first, because group sizes may differ. After obtaining the overlap sum, divide by its own size. A check can reconstruct the other groups: here A=600 and C=660, with averages60% and66%, consistent with the lower overall mean.',
[('In30 observations, the first20 average50, last20 average60, and all30 average55. Find the middle10 average.',r'The middle total is $20(50)+20(60)-30(55)=550$. Dividing by10 gives55.'),('Two groups of15 and20 students overlap in5; averages are80 and70. Their union of30 averages75. Find overlap average.',r'Overlap total is $15(80)+20(70)-30(75)=350$. The five shared students average70.')],diff='Easy')
add(17,'Aptitude','A son was born when his mother was28. His father is4 years older than his mother. Their current father:mother age ratio is9:8. Find the son’s current age.',['2','3','4','5'],'C',
['Represent the parent ages as9k and8k.','The parents differ by4 years, and the mother exceeds the son by28 years.'],
r'The difference $9k-8k=k$ is4, so father and mother are36 and32. The mother-son age difference is permanently28, giving son age $32-28=4$. Thus C is correct; the other ages violate the stated mother-son difference.',
r'Age differences remain constant as time passes because all people age at the same rate. Age ratios generally change with time, so apply a ratio only at the specified date. If ages are in ratio m:n, write them as mk and nk; their known difference determines k. A birth statement supplies another permanent difference, not a current ratio. Solve these linear relationships and check all ages are nonnegative and plausible within the given data. Years need not always be integers unless stated, but this problem gives an exact integer result. Avoid assigning the parent age difference to the child or using the ratio at the child’s birth without translating the date.',
[('A father is5 years older than the mother; their current ratio is8:7. The mother was25 at her child’s birth. Find child age.',r'$8k-7k=5$ gives k=5 and mother35. The child is $35-25=10$.'),('A mother is30 years older than her son. Their current ages are in ratio5:2. Find both ages.',r'Let ages be5k and2k. Then3k=30, k=10, so mother50 and son20.')],diff='Easy')
add(18,'Aptitude','Among boys, B is taller than10 and shorter than13. Among girls, G is taller than6 and shorter than8. Exactly two boys and three girls are shorter than B but taller than G. No heights are equal. In the whole class, B is:',
['Taller than21, shorter than18 others','Taller than20, shorter than18 others','Taller than20, shorter than19 others','Taller than19, shorter than19 others'],'B',
['Include B and G when counting the total numbers of boys and girls.','Girls below B consist of girls below G, G herself, and the three girls between them.'],
r'There are $10+1+13=24$ boys and $6+1+8=15$ girls, hence39 students. B is above10 boys. Because G is below B, girls below B are the6 below G, G herself and the3 between G and B:10 girls. Hence B is taller than20 students and shorter than $39-1-20=18$, option B. A has too many below; C and D imply an incorrect rank. The two boys between G and B are already among the10 boys below B.',
r'Ranking problems count subjects separately from the people above and below them. If a person is taller than a and shorter than b in a group with distinct heights, the group size is a+b+1. When transferring a rank between two groups, split one group around the reference person: below, the reference, between, and above. Distinct heights make these intervals disjoint and eliminate ties. Here the three girls between G and B must be added to the six below G and G herself; omitting G causes an off-by-one error. Total counts give an independent check because people below B, B, and people above B must partition the class. Information about intermediate boys does not add new boys below B.',
[('There are20 boys and10 girls. B is above7 boys. G is above3 girls, and two girls are strictly between G and B, with G below B. How many are below B?',r'Girls below B number $3+1+2=6$. Add7 boys to get13 below B; above B are $30-1-13=16$.'),('In a line of25 distinct-height students, a student is taller than9. What is the rank from tallest?',r'There are $25-1-9=15$ taller students. The rank from tallest is16, while the rank from shortest is10.')])
add(19,'Aptitude','A right triangle has integer side lengths and hypotenuse17 cm. Find its area in square centimetres.',['Insufficient information','60','68','225'],'B',
['Find positive integer legs satisfying a²+b²=289.','The Pythagorean triple with hypotenuse17 is8,15,17.'],
r'Let $a\le b$ be the positive integer legs. Then $a^2+b^2=17^2=289$ and $a\le12$. Among $289-a^2$ for $1\le a\le12$, the only square is225 at a=8 (the next candidate a=12 gives145). Thus the legs are8 and15. Area is $8(15)/2=60$, B. A fails because the integer constraint determines the legs up to interchange; C and D are not the area. Alternatively the primitive-triple parametrization uses $17=4^2+1^2$, giving legs $4^2-1^2=15$ and $2(4)(1)=8$.',
r'A right triangle satisfies $a^2+b^2=c^2$ and has area ab/2. Without the integer restriction, a fixed hypotenuse does not determine the area. Integer triples can be found by testing squares or by Euclid’s parametrization: primitive legs are $m^2-n^2$ and2mn, with hypotenuse $m^2+n^2$, where m>n are coprime and of opposite parity. A nonprimitive triple is an integer multiple of a primitive one. With prime hypotenuse17 and positive legs, the triple is primitive; the square-sum representation17=16+1 gives the unique triple. Do not use the hypotenuse as a perpendicular leg in the area formula. Checking both the Pythagorean identity and the area multiplication avoids common errors.',
[('An integer right triangle has hypotenuse13. Find its area.',r'$13=3^2+2^2$ gives legs $9-4=5$ and $2(3)(2)=12$. Check25+144=169; area is30.'),('Find the area of the integer right triangle with hypotenuse10 and legs in ratio3:4.',r'Write legs3k,4k, hypotenuse5k. Then k=2, so legs6,8 and area24.')])
add(20,'Aptitude','Rajesh visits Sunil’s house1 km North-East of his own house, then Arjun’s house707 m south of Sunil’s. Find the distance from Rajesh’s current position to his own house, to the nearest metre.',['800 m','600 m','707 m','1000 m'],'C',
['North-East means equal east and north components at45°.','Subtract707 only from the north component, then use the Euclidean distance.'],
r'Place Rajesh’s house at(0,0), east as positive x and north as positive y. Sunil is at $(1000/\sqrt2,1000/\sqrt2)$. After707 m south, Rajesh is at $(1000/\sqrt2,1000/\sqrt2-707)\approx(707.1068,.1068)$. Distance is $\sqrt{(707.1068)^2+(.1068)^2}\approx707.1068$ m, rounding to707 m. C is correct; A,B,D fail this vector calculation.',
r'Compass directions translate naturally into Cartesian vectors. A displacement of length L at North-East has components $(L/\sqrt2,L/\sqrt2)$, whereas a southward displacement affects only the north coordinate. Add successive displacement vectors to find the final position; then apply the Pythagorean distance formula. Path length is different from straight-line distance, so adding1000 and707 would answer another question. Keep sufficient precision until the final rounding:1000 divided by the square root of2 is not exactly707. The near-cancellation in the north component explains why the final distance nearly equals the east component. Convert all distances to the same unit before calculating.',
[('A person walks500 m North-East and then500/√2 m south. Find distance from the start.',r'The first components are both $500/\sqrt2$. Southward motion cancels the north component, leaving distance $500/\sqrt2=250\sqrt2$ m east.'),('A person walks300 m east and400 m north. Find distance and path length.',r'The displacement is(300,400), with distance $\sqrt{300^2+400^2}=500$ m. The path length is300+400=700 m.')],diff='Easy')
add(22,'Real Analysis',r'Let $S=\{x\in\mathbb R:x>1\text{ and }(1-x^4)/(1-x^3)>22\}$. Which statement is true?',
['S is empty',r'There is a bijection between S and $\mathbb N$',r'There is a bijection between S and $\mathbb R$','There is a bijection between S and a nonempty finite set'],'C',
['Simplify the quotient for x>1, where its denominator is nonzero.','Show that S contains a nonempty open interval and use its containment in R.'],
r'For $x>1$, $(1-x^4)/(1-x^3)=(x^4-1)/(x^3-1)=x+(x-1)/(x^3-1)=x+1/(x^2+x+1)>x$. Therefore $(22,\infty)\subset S\subset\mathbb R$. The interval has the same cardinality as R, so these inclusions and Cantor–Schröder–Bernstein give $|S|=|\mathbb R|$. Thus C is correct. S is nonempty and uncountable, eliminating A,B,D. An exact threshold for the inequality is unnecessary.',
r'A bijection is a one-to-one and onto correspondence. Countably infinite sets admit a bijection with the natural numbers; real intervals are uncountable and have continuum cardinality. Any nondegenerate interval has a bijection with R, for instance a suitable tangent transformation for a bounded open interval, or the logarithm for a positive half-line. If an interval is contained in a set S which is itself contained in R, there are injections in both directions between S and R, and the Cantor–Schröder–Bernstein theorem yields a bijection. This cardinality argument can avoid solving a complicated inequality exactly. When simplifying rational expressions, verify the denominator is nonzero on the specified domain.',
[(r'Find the cardinality of $\{x\in\mathbb R:x^2>9\}$.',r'The set is $(-\infty,-3)\cup(3,\infty)$. It contains a real interval and is contained in R, so its cardinality is continuum.'),(r'Find the cardinality of $\{x\in\mathbb Q:x^2>9\}$.',r'It is a subset of the countable set Q and contains infinitely many positive integers. Thus it is countably infinite; replacing R by Q changes the cardinality.')],diff='Easy')
add(23,'Real Analysis',r'Let C be the collection of all sets S whose power set is countably infinite. Which statement is true?',
['C contains a nonempty finite set','C contains a countably infinite set','C contains an uncountable set','C is empty'],'D',
['If S is finite, its power set is finite.','If S is infinite, compare S and its power set using Cantor’s theorem.'],
r'If $|S|=n<\infty$, then $|\mathcal P(S)|=2^n$, finite. If S is countably infinite, Cantor\'s theorem makes its power set uncountable. If S is uncountable, the injection $s\mapsto\{s\}$ already makes its power set uncountable. These cases exhaust all S, so none has a countably infinite power set. C is empty, option D; A,B,C each assert an impossible member.',
r'The power set consists of all subsets, including the empty set and the set itself. For a finite n-element set, each element has two independent inclusion choices, producing2^n subsets. Cantor’s theorem says no map from S onto its power set exists: for any proposed map f, the diagonal set $D=\{s:s\notin f(s)\}$ differs from f(s) at s for every s. Together with the singleton injection, this shows the power set has strictly larger cardinality. In particular the power set of a countably infinite set is uncountable. The empty set has power set $\{\varnothing\}$ of size1, so it also fails the countably infinite requirement. Distinguish countably finite from countably infinite.',
[(r'How many subsets does a five-element set have?',r'Each of five elements can be included or excluded, so there are $2^5=32$ subsets, including the empty and full sets.'),(r'Prove $\mathcal P(\mathbb N)$ is uncountable.',r'If its subsets were listed as $A_1,A_2,\ldots$, form $D=\{n:n\notin A_n\}$. D differs from every A_n at n, so the list omits D, a contradiction.')],diff='Easy')
add(24,'Real Analysis',r'Let $(a_n)_{n\ge1}$ be a bounded real sequence. Which statement is FALSE?',
[r'If $\liminf a_n=\limsup a_n$, then $(a_n)$ converges',r'If $\inf\{a_n:n\ge1\}=\limsup a_n$, then $(a_n)$ converges',r'If $\sup\{a_n:n\ge1\}=\liminf a_n$, then $(a_n)$ is constant',r'If $\sup\{a_n:n\ge1\}=\inf\{a_n:n\ge1\}$, then $(a_n)$ is constant'],'C',
['Use inf≤liminf≤limsup≤sup.','Convergence to the supremum does not require every term to equal that supremum.'],
r'For a bounded sequence, $\inf a_n\le\liminf a_n\le\limsup a_n\le\sup a_n$. Thus A is true by the convergence criterion, and B forces equal liminf and limsup, also true. C is false: $a_n=1-1/n$ has supremum1 and liminf1 but is not constant. D is true because every term lies between equal global infimum and supremum. Therefore C is the required false statement.',
r'The liminf and limsup describe eventual lower and upper behaviour: $\liminf a_n=\lim_N\inf_{n\ge N}a_n$ and $\limsup a_n=\lim_N\sup_{n\ge N}a_n$. Tail infima increase and tail suprema decrease, so boundedness makes these limits finite. Equality of the two means convergence to their common value. Global extrema concern all terms, including finitely many early terms, while liminf and limsup ignore such finite changes. A sequence may approach its global supremum without ever attaining it; this does not make it constant. Only equality of the global infimum and supremum forces all entries to agree. When an option claims necessity, one explicit bounded counterexample is enough to refute it.',
[(r'Compute infimum, supremum, liminf and limsup for $a_n=1/n$.',r'Infimum0, supremum1, liminf0 and limsup0. The sequence converges to0 but is not constant.'),(r'Compute liminf and limsup for $a_n=(-1)^n+1/n$.',r'Even terms tend to1 and odd terms to−1. Thus liminf=−1 and limsup=1, so the sequence does not converge.')])
add(25,'Real Analysis',r'What is the cardinality of the real solution set of $e^x+x=1$?',
['0','1','Countably infinite','Uncountable'],'B',
['Check whether x=0 is a solution.','Use strict monotonicity to show there can be no second solution.'],
r'At x=0, $e^0+0=1$, so there is a solution. The function $F(x)=e^x+x$ has derivative $F^\prime(x)=e^x+1>0$ everywhere and is strictly increasing. Consequently it takes the value1 at most once. The solution set is exactly $\{0\}$, with cardinality1, option B. A fails existence, and C,D fail uniqueness.',
r'A strictly monotone real function can meet a horizontal line at most once. If a differentiable function has positive derivative throughout an interval, the mean value theorem proves strict increase there. Existence is a separate matter: it may be shown by finding a root directly or by the intermediate value theorem after checking continuity and endpoint signs. Counting solutions is often easier than solving them in closed form. For $e^x+x=c$, the function tends to−∞ as x tends to−∞ and to∞ as x tends to∞, so every real c has exactly one solution. Avoid assuming that an exponential equation must have no elementary solution; the requested cardinality only needs monotonicity and existence.',
[(r'How many real roots does $e^x+2x=3$ have?',r'The derivative $e^x+2$ is positive. The function tends from−∞ to∞, so by continuity it crosses3 exactly once.'),(r'How many real roots does $x^3+x=0$ have?',r'The derivative $3x^2+1>0$ makes the function strictly increasing. Since x=0 is a root, it is the unique root.')],diff='Easy')
add(26,'Real Analysis',r'For $n\ge1$ define $f_n(x)=x^2/\sqrt{x^2+1/n}$ on R, with the nonnegative square root. Wherever the pointwise limit exists call it f(x). Which statement is true?',
[r'f is undefined at some real x',r'$f(x)=0$ for every real x',r'$f(x)=x$ for every real x',r'$f(x)=|x|$ for every real x'],'D',
['Handle x=0 separately before dividing by the limit of the denominator.','For nonzero x, the denominator tends to √(x²)=|x|.'],
r'If x=0, every $f_n(0)=0$, so f(0)=0. If $x\ne0$, the denominator tends to $\sqrt{x^2}=|x|>0$, and $f_n(x)\to x^2/|x|=|x|$. Thus f exists everywhere and equals |x|, option D. A fails because zero is also covered; B fails at x=1; C fails at any negative x, e.g. f(−1)=1, not−1.',
r'Pointwise convergence fixes x and lets n tend to infinity. Continuous operations preserve limits when their inputs converge and denominators have nonzero limits. A denominator tending to zero requires separate examination; here at x=0 the numerator is identically zero and direct substitution resolves the value without a 0/0 argument. The nonnegative square root of x² is |x|, not x on all of R. This distinction is crucial for negative inputs. Pointwise convergence does not generally imply uniform convergence or differentiability of the limit. In this example the limit has a corner at zero even though every f_n is smooth. Always include exceptional parameter values rather than assuming a formula derived by division applies there.',
[(r'Find the pointwise limit of $g_n(x)=\sqrt{x^2+1/n}$.',r'Continuity of the nonnegative square root gives $g_n(x)\to\sqrt{x^2}=|x|$ for every x, including0.'),(r'Find the pointwise limit of $h_n(x)=x/\sqrt{x^2+1/n}$.',r'At0 the value is0. For nonzero x, the limit is $x/|x|$, so1 for x>0 and−1 for x<0.')],diff='Easy')
add(27,'Linear Algebra',r'Let $A:\mathbb R^m\to\mathbb R^n$ be a nonzero linear transformation. Which statement is true?',
['If A is injective but not onto, then m>n','If A is onto but not injective, then m<n','If A is bijective, then m=n','If A is injective, then m=n'],'C',
['Relate injectivity and surjectivity to the rank.','Injectivity forces rank m; surjectivity forces rank n.'],
r'By rank-nullity, injectivity gives rank A=m≤n; if not onto, rank A<n, hence m<n, refuting A. Onto gives rank A=n≤m; if not injective, nullity m−n>0, hence m>n, refuting B. Bijectivity gives both rank=m and rank=n, so m=n, proving C. D is false: the map $t\mapsto(t,0)$ injects R into R².',
r'For a linear map from an m-dimensional domain, rank plus nullity equals m. Its image lies in the n-dimensional target, so rank is at most n. Injectivity means kernel0 and nullity0; surjectivity means the image has full target dimension n. A bijective linear map is an isomorphism and preserves dimension. Equal dimensions alone do not make a given map bijective, but in equal finite dimensions injectivity and surjectivity are equivalent. Dimensional inequalities give necessary conditions, not guarantees: m≤n permits an injection but a particular map can still have a nontrivial kernel. Keep domain and target dimensions in the right order when applying the theorem.',
[(r'Can a linear map R³→R² be injective?',r'Rank is at most2, so nullity is at least3−2=1. It cannot be injective, though $(x,y,z)\mapsto(x,y)$ is onto.'),(r'A linear map R⁴→R⁶ has rank4. Determine injectivity and surjectivity.',r'Nullity is4−4=0, so it is injective. Rank4<6 means it is not onto.')],diff='Easy')
add(28,'Linear Algebra',r'A is a real10×10 matrix of rank7. Which assertion is necessarily true?',
[r'There is v with $Av\ne0$ and $A^2v=0$',r'There is v with $A^2v\ne0$','A has a nonzero eigenvalue',r'$A^7=0$'],'B',
['Use the rank inequality for a product of two10×10 matrices.','Rank(A²)≥2rank(A)−10=4.'],
r'Sylvester\'s rank inequality gives $\operatorname{rank}(A^2)\ge7+7-10=4>0$. Thus A² is a nonzero map and some v has $A^2v\ne0$, proving B. For $A=\operatorname{diag}(I_7,0_3)$, A²=A and $A^2v=0$ implies Av=0, refuting A; also A⁷=A≠0 refutes D. For C, $J_8(0)\oplus0_2$ has rank7 but all eigenvalues0. No nonzero eigenvalue is forced.',
r'For compatible matrices with an inner dimension n, Sylvester’s inequality is rank(AB)≥rank(A)+rank(B)−n. For a square A this gives rank(A²)≥2rank(A)−n. One proof restricts A to im(A): its kernel there has dimension at most dim ker(A), so the image dimension is at least rank(A)−nullity(A). In particular A²=0 implies im(A)⊂ker(A), forcing rank(A)≤n/2. Rank does not determine eigenvalues or nilpotency: a nilpotent Jordan block of size k has rank k−1 despite all eigenvalues being zero. To refute necessity, select a matrix with exactly the specified rank. Diagonal projections and nilpotent Jordan blocks provide contrasting examples.',
[(r'A6×6 matrix has rank4. Can its square be zero?',r'Rank(A²)≥8−6=2, so A² cannot be zero.'),(r'Construct a4×4 rank2 matrix whose square is zero.',r'Take $A=J_2(0)\oplus J_2(0)$, where $J_2(0)=\begin{pmatrix}0&1\\0&0\end{pmatrix}$. Each block has rank1 and square0, so rank A=2 and A²=0.')])
add(29,'Linear Algebra',r'The real matrix $\begin{pmatrix}2&a\\b&c\end{pmatrix}$ has eigenvalue6. Which relation is necessary?',
[r'$24-ab=4c$',r'$a+b=8$',r'$c=6$',r'$ab=0$'],'A',
['An eigenvalue makes A−6I singular.','Expand the2×2 determinant and rearrange.'],
r'$0=\det(A-6I)=(-4)(c-6)-ab=24-4c-ab$, giving $24-ab=4c$, A. The matrix with a=b=4,c=2 has eigenvalues6 and−2 and satisfies A, but a+b=8 happens only accidentally. To refute B use a=2,b=8,c=2: its determinant condition holds, while a+b=10. The a=b=4,c=2 example refutes C and D because c≠6 and ab=16≠0.',
r'A scalar λ is an eigenvalue exactly when A−λI is singular, equivalently det(A−λI)=0. For a2×2 matrix this determinant is a quadratic polynomial whose roots are the eigenvalues. A specified eigenvalue normally gives one algebraic constraint on several entries, not their individual values. Expand signs carefully: subtract λ only from diagonal entries, leaving off-diagonal entries unchanged. Trace equals the sum of eigenvalues and determinant their product, but knowing only one eigenvalue does not determine the other unless another invariant is given. Testing proposed necessary conclusions with a matrix satisfying the determinant constraint distinguishes true consequences from special cases.',
[(r'$\begin{pmatrix}1&a\\b&4\end{pmatrix}$ has eigenvalue5. Find ab.',r'$\det(A-5I)=(-4)(-1)-ab=4-ab=0$, so ab=4.'),(r'$\begin{pmatrix}3&2\\4&c\end{pmatrix}$ has eigenvalue7. Find c and the other eigenvalue.',r'$(-4)(c-7)-8=0$ gives c=5. Trace is8, so the other eigenvalue is8−7=1.')],diff='Easy')
add(30,'Linear Algebra',r'On the real vector space V of2×2 matrices, let $T(B)=AB$ with $A=\begin{pmatrix}2&0\\0&1\end{pmatrix}$. Find the characteristic polynomial of T.',
[r'$(x-2)(x-1)$',r'$x^2(x-2)(x-1)$',r'$(x-2)^2(x-1)^2$',r'$(x^2-2)(x^2-1)$'],'C',
['V has dimension4; track T on the four standard matrix units.','Left multiplication scales first-row units by2 and second-row units by1.'],
r'In the basis $(E_{11},E_{12},E_{21},E_{22})$, T acts as diag(2,2,1,1). Therefore $\chi_T(x)=(x-2)^2(x-1)^2$, C. A has degree2 instead of4. B introduces zero eigenvalues although A and T are invertible. D has roots ±√2 and±1, not the eigenvalues of T.',
r'The vector space of m×n matrices has dimension mn, with the matrix units E_ij as a basis. Left multiplication by a square m×m matrix acts independently on each of the n columns. Thus its representing matrix, in a column-wise basis, is block diagonal with n copies of A, and characteristic polynomial $(\chi_A)^n$. For diagonal A, each E_ij is an eigenvector with eigenvalue equal to the ith diagonal entry. Right multiplication instead acts independently on rows and yields a corresponding repeated characteristic polynomial. Distinguish the matrix A from the linear operator on a larger matrix space; the latter has dimension4 here. The degree of the characteristic polynomial is a useful preliminary check.',
[(r'On3×2 matrices, left multiplication by diag(1,2,3) defines T. Find χ_T.',r'Each of two columns is transformed by A. Therefore $\chi_T=(x-1)^2(x-2)^2(x-3)^2$, of degree6.'),(r'On2×2 matrices, T(B)=3B. Find its trace and determinant as a linear operator.',r'T is3I on a4-dimensional space. Its eigenvalues are four copies of3, so trace12 and determinant3⁴=81.')])
